### ISSUE TITLE
Cannot ping my machine when I use --ip option

### ISSUE THREAD

**Issue by kadogo** [netblue30/firejail#1076]
Hello everyone.
I need to test something from 2 differents IP on a virtualbox machine.
I want avoid running 2 VMs so I would use my computer and an instance with firejail.

My vbox interface is vboxnet0 (192.168.10.1).
I run the following command.

`firejail --noprofile --net=vboxnet0 --ip=192.168.10.2 bash`
`ping 192.168.10.1`

When I do my ping it says my host is unreachable.
Maybe I missed something, so I come here to ask some help ^^

Thanks

**Comment by netblue30** [comment]
It is by design, from inside the sandbox you cannot reach the host. An exploit would be for a crook to take control of the sandbox and then starting a dictionary attack on the host ssh server.

This happens only if --net is an Ethernet interface, for bridge interfaces the host is still accessible on the IP address of the bridge interface.

**Comment by kadogo** [comment]
Ok thanks for the information.
I will look how do it with a bridge interface then ^^

**Comment by netblue30** [comment]
The bridge is quite easy, take a look here: https://firejail.wordpress.com/documentation-2/basic-usage/#routed

You only enable ip forwarding and set netfilter if you need to forward traffic from your sandboxes out on the network.
