### ISSUE TITLE
firejail 0.9.32 fails to execute tor browser with --detach argument

### ISSUE THREAD

**Issue by pitchforks** [netblue30/firejail#109]
tor browser 5.0.3

I run tor browser by navigating to `~/tor-browser_en-US/Browser/` directory, then starting it with `./start-tor-browser`

`firejail ./start-tor-browser` works. `firejail ./start-tor-browser --detach` does not. It does not work even if I quote the command and its arguments: `firejail './start-tor-browser --detach'`.

**Comment by netblue30** [comment]
Indeed, I can only start it as "firejail Browser/start-tor-browser". I think I have a more general problem with processes detaching from the terminal. Thank you for the bug report.

**Comment by netblue30** [comment]
**Workaround:**

Tor browser *--detach* option uses *bash disown* feature to prevent the browser from closing when the terminal is closed. The workaround is to apply disown directly to firejail:
`````
$ cd tor-browser_en-US
$ firejail Browser/start-tor-browser & disown
`````
If you can close the terminal now, the browser will continue running.

I am closing the request. Firejail needs to monitor the process running in the sandbox in order to do some cleanup during shutdown.
