### ISSUE TITLE
Where is Downloads folder for --private option?

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#1199]
Where is Downloads folder for `--private` option? I want to copy contents I've downloaded to the local filesystem. If I use `--private=<DIR>`, I can access it, but I can't find it with `--private`. Or is this not possible? I assumed it is because I can download files and they are still seen by FIrefox. It's not in /tmp.

**Comment by chiraag-nataraj** [comment]
If I understand your setup correctly, Firefox creates a new Downloads directory inside the temporary home directory. As for how to get the data out...I suppose you can use `firejail`'s `--get` option (see the manpage for more details). I personally use `whitelist` to only allow the directories Firefox absolutely needs so that data transfer is easy.

**Comment by rieje** [comment]
`--whitelist` works with `--private`? I get:

    *** Warning: cannot whitelist Downloads directory
    *** 	Any file saved will be lost when the sandbox is closed.
    *** 	Please create a proper Downloads directory for your application.

**Comment by chiraag-nataraj** [comment]
No, I use `--whitelist` _instead_ of `--private`.
