### ISSUE TITLE
Error fcopy: invalid file

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1243]
I'm getting `Error fcopy: invalid file` whenever I try to use `private-etc` or `private-bin`. This is happening on Debian Sid/Experimental with Firejail 0.9.46~rc1.

More specifically, I'm running into errors with this line:
`private-etc Muttrc.d/,Muttrc,alternatives/,resolv.conf,ssl/,mime.types,proxychains.conf`
but not this line:
`private-etc Muttrc,resolv.conf`.

Similarly, I'm running into errors with: `private-bin sh,mutt,mutt_dotlock,bash,emacsclient,elinks,gpg,gpg-agent,pinentry,dig,awk` but not `private-bin sh,mutt,bash,emacsclient,elinks,gpg,gpg-agent,pinentry,dig,awk`.

**Comment by reinerh** [comment]
I was able to reproduce the private-bin error:
```
$ firejail --noprofile --private-bin=bash,mutt_dotlock
Parent pid 12801, child pid 12802
Error fcopy: invalid file /usr/bin/mutt_dotlock
Error: failed to run /usr/lib/x86_64-linux-gnu/firejail/fcopy
Error: proc 12801 cannot sync with peer: unexpected EOF
Peer 12802 unexpectedly exited with status 1
```
The reason seems to be that mutt_dotlock is a suid binary.
It might be not allowed to copy it because of security reasons, but I'm not completely sure about that.
At least a more telling error message would be good.

**Comment by chiraag-nataraj** [comment]
> The reason seems to be that mutt_dotlock is a suid binary.
It might be not allowed to copy it because of security reasons, but I'm not completely sure about that.

That's almost certainly not the problem - otherwise, the problem would only show up in `private-bin` but it shows up with `private-etc` as well.

**Comment by reinerh** [comment]
On Sun, Apr 23, 2017 at 07:13:15PM -0700, ಚಿರಾಗ್ ನಟರಾಜ್ wrote:
> > The reason seems to be that mutt_dotlock is a suid binary.
> It might be not allowed to copy it because of security reasons, but I'm not completely sure about that.
> 
> That's almost certainly not the problem - otherwise, the problem would only show up in `private-bin` but it shows up with `private-etc` as well.

There seem to be two cases where it can fail:
 https://github.com/netblue30/firejail/blob/master/src/fcopy/main.c#L199-L204

If the file is not there or can't be stat'ed, or if the real uid/gid don't
match the file to copy.

**Comment by netblue30** [comment]
There are two different bugs, one with the trailing '/' char (firejail --private-etc=alternatives/) and one with the group ownership.

Fixes: https://github.com/netblue30/firejail/commit/bff77f44afcdf43e69053dc2a3e4b45514810952 and https://github.com/netblue30/firejail/commit/df8c4e9cd15bfc2c5cb4c854a8f876c02c2eb1d6

**Comment by miszr** [comment]
The issue still persists.

My system is configured with `systemd-networkd `and `systemd-resolved`.

The file `/etc/resolv.conf` is symlinked to `/run/systemd/resolve/resolv.conf` with the following permissions:
`-rw-r--r-- systemd-resolve systemd-resolve /run/systemd/resolve/resolv.conf`

So the file is world readable, but fcopy still refuses to copy it.

The issue is that fcopy only checks the `uid` of the file, not respecting the actual permissions set on it.

An example where this would fail terribly is if a file owner had no permissions.

**Comment by eomanis** [comment]
The problem described by @miszr in the preceding comment is currently preventing me from launching Steam, which I have set up to be launched in a --private= home dir.

```
[myuser@mysystem ~]$ ls -la /etc/resolv.conf
lrwxrwxrwx 1 root root 32 15. Sep 21:51 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf
[myuser@mysystem ~]$ ls -la /run/systemd/resolve/resolv.conf 
-rw-r--r-- 1 systemd-resolve systemd-resolve 536 15. Sep 14:36 /run/systemd/resolve/resolv.conf
```
Launching Steam:
```
[myuser@mysystem Steam]$ /usr/bin/firejail --profile=/etc/firejail/steam.profile --private="/home/myuser/sandboxes/Steam" -- /usr/bin/steam-runtime %U
Reading profile /etc/firejail/steam.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-common.local
Reading profile /home/myuser/.config/firejail/disable-common.local
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: noroot option is not available
Parent pid 26240, child pid 26241
Error fcopy: invalid file /etc/resolv.conf
Error: failed to run /usr/lib/firejail/fcopy
Error: proc 26240 cannot sync with peer: unexpected EOF
Peer 26241 unexpectedly exited with status 1
```
Possibly fcopy takes offense to /etc/resolv.conf being a symlink.
The weird thing is, why does this surface now? I have moved from NetworkManager to systemd-networkd and systemd-resolved recently because of some NetworkManager regression, but with NetworkManager I also had /etc/resolv.conf symlinked to the respective NetworkManager-generated file, and Steam worked back then.
