### ISSUE TITLE
Firejail in PHP exec() results in "Error: user .config directory is not owned by the current user"

### ISSUE THREAD

**Issue by tobltobs** [netblue30/firejail#1264]
I am trying to jail the command I use in PHPs exec() with firejail.

The commands I tried:
```
firejail [cmd]
firejail --profile=/etc/firejail/default.profile [cmd]
```
But I always get the following error:
```
Error: user .config directory is not owned by the current user
Error: cannot establish communication with the parent, exiting...
```

**Comment by SpotComms** [comment]
Because the www-data or httpd user doesn't have a home directory. And using firejail in PHP might not be the best idea. You might want to instead wrap your command with escapeshellarg() and wrap your user input with noHTML(). If you haven't, using a framework like Cake or Laravel might be worth looking into, it'll handle all that stuff for you (to an extent). There is also an old program called Skipfish which can detect some common mistakes in your PHP, its worth giving it a run.

> //Credit: https://paragonie.com/blog/2015/06/preventing-xss-vulnerabilities-in-php-everything-you-need-know
function noHTML($input, $encoding = 'UTF-8') {
	return htmlentities($input, ENT_QUOTES | ENT_HTML5, $encoding);
}

**Comment by tobltobs** [comment]
I am trying to reduce the risk of feeding user uploads to external programs like ghostscript or imagemagicks convert. Hardening PHP or escaping arguments is already done, but doesn't help with this attack vector.

> And using firejail in PHP might not be the best idea. 

I am evaluating firejail as a chroot alternative and from the offered feature it looks superior to me. Is there a special reason why using firejail in PHP might not be the best idea?

I could avoid calling firejail by www-data as the the my processing could also be done by background queue which can use a user with a home. However, I am having problems setting up a firejail for a command with one recursively white-listed directory where changes are persisted. I guess I will have to try harder.

**Comment by netblue30** [comment]
I would put all the server in a sandbox. Both apache and nginx are supported.

**Comment by tobltobs** [comment]
@netblue30 That might be an option. But restricting the calls to external programs could be more strict than the restrictions I could apply to the server. Eg. I could use --net=none for calls to ghostscript, but my PHP scripts require the ability to download a file.
