### ISSUE TITLE
Profiles missing in firecfg.config

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#1349]
I noticed that quite a number of existing profiles are not included in /usr/lib/firejail/firecfg.config:

```
7z
cpio
curl
gimp-2.8
git
gnome-contacts
gpa
gpg-agent
gpg
gtar
guayadeque
gzip
kino
less
lxterminal
mcabber
nemo
openbox
pcmanfm
qupzilla
snap
ssh-agent
strings
tar
thunar
Thunar
unrar
unzip
uudeview
uzbl-browser
vim
wget
xonotic
xz
xzdec
zoom
Fossamail
Telegram
VirtualBox
Wire
```
`Cyberfox` is commented but `cyberfox` is missing.

`wesnot` should be `wesnoth`.

A profile for `spectacle` doesn't exist.

**Comment by Fred-Barclay** [comment]
Thanks @curiosity-seeker 

@netblue30 I can handle this but I want to check that none of this is on purpose first. 😁

**Comment by SpotComms** [comment]
gnome-contacts, strings should be added

FossaMail, gimp-2.8, Telegram, VirtualBox, Wire should be added as they are aliases to already added programs

7z, cpio, gtar, gzip, tar, unrar, unzip, xz, xzdec shouldn't be added due to potetential root breakage

curl, gpg, gpg-agent, less shouldn't be added due to potetential root breakage

git, ssh-agent, wget should be considered to be added

lxterminal, should not be added

nemo, pcmanfm, thunar, Thunar should not be added due to #1261

openbox should not be added due to #1178

xonotic is already added in the form of xonotic-{glx,sdl}

gpa, mcabber, qupzilla, uudeview, uzbl-browser I think can be added


That just leaves guayadeque, kino, snap, vim, zoom

**Comment by SpotComms** [comment]
@netblue30 git should probably be removed as it causes extremely long delays when using a PS1 that shows the status of a git repository. Everything else in 1acfd077b124cbfc8ed257f0c0aacf4f4cbaba38 seems fine.

**Comment by curiosity-seeker** [comment]
@netblue : Thanks for the fix. However, `spectacle` is still in that file but there isn't a profile for it.
