### ISSUE TITLE
Whitelist not working?

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#1353]
I run firefox in firejail sandbox and when I play videos using mpv from it, it's not using my mpv config. So I guess I have to whitelist my mpv config files. I have the `~/.config/mpv` folder but in it contains all my configs that are symlinked from my git repo, so this may be the problem.

In my firefox.profile, I have:

    noblacklist ~/.config/mpv

Is this not enough?

**Comment by netblue30** [comment]
You would also add a whitelist in your firefox.profile for mpv config:
`````
whitelist ~/.config/mpv
`````

> but in it contains all my configs that are symlinked from my git repo

It shouldn't be a problem.

**Comment by rieje** [comment]
@netblue30 It doesn't appear to be working--when I download a video and run it from Firefox, it's using default mpv settings instead of my customized ones. To be clear, here's what my config structure [looks like](https://ptpb.pw/ACh-CZr_60X1o9tP1BjiR6KTR0Ny.png). `~/.config/mpv` is an actual folder, while all the config files inside are symlinked to under that folder, as you can see.

In my `~/.config/firejail/firefox.profile` I have the [following](https://ptpb.pw/AA4bZBd4Sj9ktuAeoOvUmZvqLnae.profile) (my attempted settings are in the 2 blocks of text from the start of the config.

Let me know what other information may be needed.

**Comment by liloman** [comment]
Hi rieje,

I can't see your images but I hope it helps you.

I've just fixed a similar very long standing issue with my .mplayer/ dir.  I don't use mpv [but a custom Bash script that uses youtube-dl](https://github.com/liloman/dotfiles/blob/master/Scripts/Scripts/descarga.sh) but I think It's related. ;)

The issue was:
 
1. I need the .mplayer/ folder be accessible from firefox (it's really a symlink to ~/dotfiles/mplayer/.mplayer in my settings but firejail whitelistes the target dir automatically)

2. I enabled it with:
whitelist ~/.mplayer
read-only ~/.mplayer

3. But I couldn't get to the target dir and when I launched mplayer from firefox It couldn't parse the config files and It was really annoying cause I disable the screensaver while playing from my mplayer config among other things.

What I did:

1. Launching a ls from vimperator console I realized that: 
!ls ~/dotfiles/mplayer  permissions were:
/home/user/dotfiles/mplayer:
total 4
dr---------. 2 nfsnobody nfsnobody 4096 mar  5 19:15 .mplayer

2. I fixed then with:
noblacklist ~/.mplayer

3. Now:
!ls ~/dotfiles/mplayer  permissions are:
/home/user/dotfiles/mplayer:
total 4
drwxrwxr-x. 2 user user 4096 mar  5 19:15 .mplayer


Cheers

**Comment by rieje** [comment]
@liloman Thanks for the response. Do you use `--private` or `--private <dir>`? In my particular scenario I'm using `--private <dir>` for my Firefox profile and when I launch firejail, I get `Warning: "whitelist ~/.config/mpv" disabled by --private` so maybe `--private <dir>` is not supported for some reason.

To be clear, my `~/.config/mpv` symlink structure looks like [this](https://ptpb.pw/AAS0fKQE7WHjQo-iesv8UIbORT5s.png) and in my firefox.profile I have the following:

    whitelist ~/.config/mpv
    read-only ~/.config/mpv
    noblacklist ~/.config/mpv

**Comment by liloman** [comment]
No, I don't. I'm using this:

```bash
firejail --name=firefox firefox -P default
```

Maybe with:

```bash
firejail --debug firefox
```
you could get help. 

Anyway for this kind of issues you can debug with 3 methods:

1. Using file:///home in the browser and seeing what looks like.

2. If you are using vimperator/X you can spawn a terminal inside the firejailed firefox with:
:!youterminal-name

3. I think you can also join a terminal inside a firefjail process with --join. :)


See if your files are there, obviously they aren't, and see what it really looks like and find out why. I will test with different scenarios from the more basic to the more restricted, kind git bisect. ;) 


Cheers

**Comment by chiraag-nataraj** [comment]
@rieje Is this still an issue?

**Comment by rieje** [comment]
Unfortunately yes. I am using the latest version of firejail and removed any custom profile settings. [Here's](https://ptpb.pw/AA2A5It1oEw_UHl_UC52W3NsAmsl.profile) the contents of `/etc/firejail/firefox.profile`, the only file I've touched. The only custom settings are:

    noblacklist ~/.config/mpv
    whitelist ~/.config/mpv
    read-only ~/.config/mpv

I use firejail like so: `firejail --seccomp --private=<path> /usr/bin/firefox -no-remote`.

**Comment by rusty-snake** [comment]
@rieje can you do what @liloman say to look if the files are there?

**Comment by rieje** [comment]
They are not there. On Arch Linux, firejail version 0.9.60. My [firefox.profile](https://pastebin.com/GyAA59vK).

**Comment by rusty-snake** [comment]
@rahiel confirming that `--private` + `--whitelist` didn't work, but why do you use `--private`.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
