### ISSUE TITLE
seccomp and ignore

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#1371]
Hi,

In order to make Firefox's CDM work with Netflix I had to get rid of `chroot` in `seccomp`.
Since `seccomp` is in an included profile, I use `ignore` then `seccomp.drop`. e.g.:
```
ignore seccomp
include block.inc         #where seccomp is
seccomp.drop list_of_syscalls
```
The problem is `ignore` blocks both `seccomp` and `seccomp.drop`.
Can you fix this, please?

**Comment by startx2017** [comment]
This is a bug, I am working on a fix, I'll have it by tomorrow.

Until the fix is in, @nick75e try this in your profile:
`````
seccomp.drop list_of_syscalls
include block.inc         #where seccomp is
`````

Looking in the code, in the presence of multiple seccomp definitions, firejail will pick only one, in the following order:
`````
seccomp.keep
seccomp.drop
seccomp call_list
seccomp
`````
Also, if a --appimage, --chroot, or --overlay command is present, seccomp will always run the default seccomp filter.  (--seccomp). I'll document them in man page.

**Comment by nick75e** [comment]
Thanks but your workaround doesn't work.
This is what I get (only an excerpt):
```
configuring 12 seccomp entries from /run/firejail/mnt/seccomp.protocol
firejail: seccomp.c:176: seccomp_filter_drop: Assertion `0' failed.
Error: proc 29935 cannot sync with peer: unexpected EOF
Peer 29936 unexpectedly killed (Segmentation fault)
```
I'll wait for the fix. In the meantime, I've imported into the profile the options from the `include`

**Comment by netblue30** [comment]
> firejail: seccomp.c:176: seccomp_filter_drop: Assertion `0' failed.

This is the old code, you didn't update or didn't install the new version. The fix is in. Do like this:
`````
$ git pull
$ make && sudo make install
`````
