### ISSUE TITLE
Archive Managers can't acces network folders

### ISSUE THREAD

**Issue by Utini2000** [netblue30/firejail#1419]
Hello everyone,
I am on Archlinux and due to the network restriction the following archive managers aren't able to access/extract to/from network shared folders:

file-roller
xarchiver
ark

I can manually edit the .conf but it will be overwritten after each update? Or to .local files always trump .profile files? Besides that I think it should still be possible for those application to exttract to network folders?

Thanks in advance !

**Comment by chiraag-nataraj** [comment]
You can always put
````
include /etc/firejail/file-roller.profile
ignore net
````
or something in a profile in `~/.config/firejail/file-roller.profile`.

I do disagree, though, that archive managers should have access to the network. If you need it to extract something on the network, the right way (IMHO) is to mount that filesystem to a local mount point (e.g. using sshfs) and then treat it as a local resource. Because the sshfs process is running outside the sandbox, you won't have any problems regarding actually writing the files.

**Comment by Utini2000** [comment]
Hmm I am on Arch + Gnome and mounted an locally shared hdd via SMB in Nemo. That didnt work

**Comment by chiraag-nataraj** [comment]
Interesting. I know that it works for `sshfs`. I `ssh` in and mount a certain directory to `/media/ccv`. Then I can open up a jailed `x-terminal-emulator` (`urxvt` in my case) _which does not have internet access_ and still read from/write to `/media/ccv`.

**Comment by SpotComms** [comment]
The gvfs-* providers seem to be incompatible compared to sshfs. Most likely because sshfs creates an actual mount instead of just a weird virtual directory. See https://askubuntu.com/a/87702

**Comment by chiraag-nataraj** [comment]
Huh...I see. Yeah, I guess I stopped using gvfs stuff a long time ago xD

**Comment by Utini2000** [comment]
Hmm so even grqnting network access wont help?
How to fix this then? :o

**Comment by chiraag-nataraj** [comment]
@Utini2000, are you using `smbnetfs`? You could give that a try rather than `gvfs` (I think `smbnetfs` uses FUSE instead).

**Comment by GeoffK59** [comment]
I'm having the same issue atm, where or what do I edit to have this working again, I need access to my drive asap.

**Comment by chiraag-nataraj** [comment]
@GeoffK59 See if #1560 helps.

**Comment by GeoffK59** [comment]
@chiraag-nataraj I read that thread but I'm still a bit confused as to what or where to edit and or be able to restrict access at will.

**Comment by chiraag-nataraj** [comment]
@GeoffK59 `firejail` is just restricting based on its profile. It doesn't care about whether you're root or another user (unless you're trying to use a feature which is restricted to root, of course). 

If you're using a FUSE filesystem (e.g. sshfs), try mounting with `-o allow_others`.

**Comment by chiraag-nataraj** [comment]
I think allowing archive managers to access the network is bad as a default. In general, a more secure workflow is copying the file to a shared directory (say, `~/Downloads`) and using the archive manager there. Of course, if people want to locally allow network access, that makes sense. But I don't think we should do that by default.

@GeoffK59 I'm going to close this due to no response. If you try that and still can't get it to work, please feel free to reopen.
