### ISSUE TITLE
Allow private-dev to accept aditional devices

### ISSUE THREAD

**Issue by VladimirSchowalter20** [netblue30/firejail#1446]
Currently `private-dev` create default device whitelist which can't be adjusted. I think it would be good to allow expanding it with additional devices similar as in `private-bin` option. Example:
`private-dev dvb`

Above will allow default `/dev` whitelist + `/dev/dvb`. It will allow adding `private-dev` to much more apps which need one or two specific devices. It would be way easier than maintaining app specific device whitelists and more secure than disabling `private-dev` altogether, see https://github.com/netblue30/firejail/pull/1445 . Also this will lose pressure for adding additional devices to default whitelist, see https://github.com/netblue30/firejail/issues/608

**Comment by smitsohu** [comment]
I guess that would also allow us to better integrate Yubikey-enabled apps

**Comment by SpotComms** [comment]
@smitsohu for Yubikey it'd still require whitelisting hidraw*, unless you could filter using vendor id.

**Comment by VladimirSchowalter20** [comment]
A I understand `private-dev hidraw*` would be enough.

**Comment by startx2017** [comment]
Support for dvb is on mainline, give it a try, I don't have a dvb card.

/dev/dvb will be allowed by default in private-dev.

If it is working, I'll add a --notv command (notv in profile files), similar to novideo and nosound.

**Comment by VladimirSchowalter20** [comment]
Isn't better and easier to adjust `private-dev`? As I stated above it'll eliminate pressure for adding new devices to default list, which 90% apps doesn't ever need and introducing dozens of `no3d,novideo,notv, no*` options which will clutter profiles?

**Comment by smitsohu** [comment]
@startx2017 I don't have TV signal in the moment :-p But I can confirm that the /dev/dvb tree is availabe inside the sandbox, with `private-dev` enabled, in real life.

From all media players that have Firejail support currently, I think only VLC and MPlayer/Gnome-Player are DVB-capable. Which means that an option `notv` should go to all other profiles with `private-dev`.

**Comment by netblue30** [comment]
Thanks @smitsohu!

Let's go for --notv. I'll add it to all profiles after the current round of merges from @SpotComms.

I'm not too worried about cluttering, we'll clean them later. I think we can collapse several of them into something like "service sound,video,tv,3d" the way we did we "protocol inet,inet6,unix..."

**Comment by smitsohu** [comment]
@startx2017 Thanks for fixing!

**Comment by VladimirSchowalter20** [comment]
@netblue30 

> I'm not too worried about cluttering, we'll clean them later. I think we can collapse several of them into something like "service sound,video,tv,3d" the way we did we "protocol inet,inet6,unix..."

My proposition will look exactly like this without inventing new config options: `private-dev dri,video,dvb...`

I don't see the point of creating many new options which purpose is to blacklist one single file. It weakens `private-dev` as it's default whitelist is getting bigger and bigger, therefore adding it would involve need to add most `no*` options at the same time to counter this effect. I bet many new profile submissions will miss some of those which means that maintainers would have to constantly monitoring and adjusting new profiles.

Is there something I miss? Why you are reluctant to adjust `private-dev` instead?

**Comment by netblue30** [comment]
> I don't see the point of creating many new options which purpose is to blacklist one single file.

It is more than a single file. For  example --nosound has some files in /dev and also PulseAudio. For --novideo (videocamera) there are files in /dev and they are already taking about doing something similar to PulseAudio, bringing in daemons and sockets. --notv and --no3d are strictly based on /dev but this can also change. Going forward we can also start integrating them with private-bin and private-lib. 

Yes, in the short run we'll clutter the profile files, but we'll clean them at some point and collapse all of them on a single line, something like "service sound,video,tv,etc...", or "subsystem sound,video,tv..." to give it a better name. My feeling is we should target subsystems in the profile files instead of individual files - the files are changing all the time. I am looking now at /dev/dvd and /dev/cdrom - it is quite a mess, no two distributions are the same.

Anyway, we can always go back to managing individual files under /dev as you propose, we already have support for /dev under --whitelist command.
