### ISSUE TITLE
Question regarding specific case where qutebrowser can launch without access to ~/.local and ~/.cache

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#1497]
https://github.com/qutebrowser/qutebrowser/issues/2927

This is pretty much a crosspost since I thought at first that this is qutebrowser related but then I noticed that if I specifically block .cache and .local with blacklist it will no longer starts. 

What happens in the initial case ?

**Comment by SpotComms** [comment]
So if you don't explicitly blacklist it, but whitelist something, it'll see a blank home dir with just the things you whitelisted. Meaning it can create a .local and .cache itself, which will be deleted once exited. However when you blacklist those they do exist in the sandbox, but nothing has permission to write to them, which causes it to crash since it can't create or open them.

**Comment by ahsis** [comment]
Ok, so qutebrowser works thanks to the lines whitelisting stuff in .cache and .local from /etc/firejail/whitelist-common.inc.

>A temporary file system is mounted on the top directory, and the whitelisted files are mount-binded inside. Modifications to whitelisted files are persistent, everything else is discarded when the sandbox is closed. The top directory could be user home, /dev, /media, /mnt, /opt, /srv, /var, and /tmp.

How does the temporary filesystem work ?
