### ISSUE TITLE
Logging for violations of blacklisted directories

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#152]
A Debian user is requesting the enhancement that firejail logs or warns the user when an application is trying to access a blacklisted directory.
I also think this would be a good idea.
Would it be possible to watch the blacklisted files/directories with inotify?

Link to the bug report: https://bugs.debian.org/794837

**Comment by avoidr** [comment]
I also think this is a good idea. Maybe even more generally logging every attempt of using forbidden functions, if this doesn't yet exist.

**Comment by netblue30** [comment]
I'll implement it for the next release, thanks.

**Comment by netblue30** [comment]
I ended up implementing it using library calls interposition (there is a new libtracelog.so in /usr/lib/firejail). With inotify, the kernel will emit notifications only on files the user has permissions to access, and since they are already blacklisted, there will be no notification.

The new option is --tracelog. These are some sample syslog messages (using LOG_INFO):
`````
Dec  3 11:43:25 debian firejail[70]: blacklist violation - sandbox 26370, exe firefox, syscall open64, path /etc/shadow
Dec  3 11:46:17 debian firejail[70]: blacklist violation - sandbox 26370, exe firefox, syscall opendir, path /boot
`````
The solution is not perfect, it can be bypassed if the file access is implemented outside glibc. However, regular programs such as Firefox always use glibc for access.
````

**Comment by reinerh** [comment]
Can this be made the default? So that you don't have to always include the cmdline flag?
I think if there is a blacklist violation, the users are interested in this.
Or is the performance impact too high to make it a default?

**Comment by netblue30** [comment]
I'll add support for it in profile files. For Firefox wouldn't be a problem. There could be a problem for programs that access files all the time. I'll make it default for browsers, mail, bittorrent and chat.

**Comment by netblue30** [comment]
I ended up with default logging in firefox, chromium, thunderbird and transmission. I'll go with this in the next release, I need more testing from users.

**Comment by reinerh** [comment]
Awesome, thanks! :)

**Comment by netblue30** [comment]
You're welcome!
