### ISSUE TITLE
Firefox no longer works after update--works again when downgraded

### ISSUE THREAD

**Issue by rieje** [netblue30/firejail#1550]
I'm on Arch Linux and updated firejail to 0.9.50 (along with the rest of the system) and `firejail /usr/bin/firefox` results in a Firefox that no longer connects to the internet. I downgraded firejail back to 0.9.48 and I no longer have this issue. Tell me what info you guys need. My [firefox.profile](https://ptpb.pw/AEvZzroTWlU1MBgY8VL8gcSiSJrM.profile).

**Comment by SpotComms** [comment]
Could you go to "Preferences > Advanced > Network > Connection > Settings" and check "No proxy" and see if that makes a difference?
And to confirm that is Firefox 55 yes?

**Comment by rieje** [comment]
I checked "No proxy" and also tried the posted firefox.profile but neither solved the issue. I am on Firefox 55.

**Comment by Fred-Barclay** [comment]
Has your system been fully updated (except for firejail)?

**Comment by rieje** [comment]
I had already updated my system including firejail, then found the latest firejail to have the problem described, so I downgraded just this package while the rest of the system is still upgraded on Arch.

**Comment by eomanis** [comment]
I have been hit by this as well, neither Firefox nor Pidgin in its own --private= home directory can access the internet with firejail-0.9.50-1, but a downgrade to firejail-0.9.48-1 fixed it.

I guess I'll pin the package to the good version with IgnorePkg = firejail in /etc/pacman.conf for the time being.

**Comment by netblue30** [comment]
The fix is in git, or so is believed. there were two other reports: https://github.com/netblue30/firejail/issues/1531 and https://github.com/netblue30/firejail/issues/1547. You need to comment out (add a #) in front of "blacklist /var/lib/systemd" line in /etc/firejal/disable-common.inc. This is the merge: https://github.com/netblue30/firejail/commit/1e879f1199fb3a3647a5eefd7a8f34bbdc8b8098

**Comment by eomanis** [comment]
@netblue30 Commenting out "blacklist /var/lib/systemd" does not solve the issue for me, but it does seem that #1547 is spot on and not having DNS resolution if done by systemd-resolved is the culprit, because my sandboxes cannot access the target of the /etc/resolv.conf symlink with firejail-0.9.50-1, however they can do so with firejail-0.9.48-1.

Please note that on Arch, if systemd-resolved is used, /etc/resolv.conf symlinks to /run/systemd/resolve/resolv.conf, and **not** anywhere below /var/lib/systemd.

I grepped everything in /etc/firejail and looked into my own stuff in ~/.config/firejail, and I could not find any blacklist directive for /run that would explain why the sandboxes cannot access /run/systemd/resolve/resolv.conf, and that weirds me out a bit.

**Comment by eomanis** [comment]
Okay now, what worked for me was this:

- make sure that /etc/resolv.conf links to /var/run/systemd/resolve/resolv.conf (and **not** to /run/systemd/resolve/resolv.conf)
- Comment out "blacklist /var/run/systemd" in /etc/firejail/disable-common.inc (note, **not** "blacklist /var/lib/systemd")

@netblue30 I suspect when you suggested to comment out the blacklisting directive for "/var/lib/systemd" you actually meant "var/run/systemd"?

**Comment by netblue30** [comment]
Yes, I meant "/var/run/systemd".

/var/lib/systemd is still blacklisted. The code is here: https://github.com/netblue30/firejail/blob/master/etc/disable-common.inc#L81, one line below is the blacklist to /var/run/systemd commented out. I think this fixes the problem.

/run and /var/run are the same thing - /var/run is a symlink to /run.
