### ISSUE TITLE
read-only/whitelist bug

### ISSUE THREAD

**Issue by avoidr** [netblue30/firejail#158]
When I whitelist a subdirectory, --read-only=~/ now includes the parent of the subdirectory.

The example explains it better:
```
$ mkdir -p a b/c

$ firejail --whitelist=~/a/ --whitelist=~/b/ --read-only=~/
[anon@jail ~]$ touch f a/f b/f
touch: cannot touch ‘f’: Read-only file system
[anon@jail ~]$ rm a/f b/f 
[anon@jail ~]$ exit

$ firejail --whitelist=~/a/ --whitelist=~/b/c/ --read-only=~/
[anon@jail ~]$ touch f a/f b/f
touch: cannot touch ‘f’: Read-only file system
touch: cannot touch ‘b/f’: Read-only file system
[anon@jail ~]$ rm a/f 
[anon@jail ~]$ exit
```

**Comment by netblue30** [comment]
The reason for the problem is you have a tmpfs mounted on ~/ and ~/a and ~/b are bind-mounted as separate filesystems. Each filesystem will have to be made read-only independently, in your case:
`````
$ firejail --whitelist=~/a/ --whitelist=~/b/ --read-only=~/ --read-only=~/a --read-only=~/b
`````
A fix is possible, however, it will be very complicated. I documented the behavior in the man page in the upcoming version, maybe I'll revisit the issue in the feature. Thanks!
