### ISSUE TITLE
Firejail breaks the ssh-agent launch semantics

### ISSUE THREAD

**Issue by lhernanz** [netblue30/firejail#1616]
Hi,

the most common way of launching ssh-agent is by using:
```bash
eval `ssh-agent`
```

That works because ssh-agent prints the environment information before getting into background. Unfortunately, when using the firejail profile this is not the case and the process just blocks as it never gets into background. This breaks some of the most common shell launch scripts and some programs like _ssh-ident_. 

If you try to solve this by putting firejail in the background, the problem is that you miss the information that is sent to the terminal before getting into the background. You can try to fix this by using the `--output` option in firejail, but you still need to use an sleep to get the output in the file. A hack on top of a hack.

Wouldn't be possible for firejail to detect that the controlled process has got into the background so that it could imitate the same behavior? Is there any other way to simulate this?

I think that firejail is a great addition to ssh-agent. It would be a pity not to be able to use it.

Thanks

Regards

**Comment by Adrianzo** [comment]
I'm having the same trouble. Played around a little bit with the profile but got only pain and no gains :stuck_out_tongue_closed_eyes:

**Comment by Adrianzo** [comment]
any news on this?

**Comment by laomaiweng** [comment]
I have a workaround for this issue. Basically I do the following in my `~/.bashrc`:

    SSH_AUTH_SOCK="$(mktemp -d --tmpdir ssh-XXXXXXXX)/S.ssh-agent"
    ssh-agent -s -D -a "$SSH_AUTH_SOCK" >~/.ssh/agent & disown
    export SSH_AUTH_SOCK SSH_AGENT_PID=$!

The idea is that I don't let the agent decide the path to its socket, this way I don't need it to tell me where it is. As for the PID, it's actually the PID of the parent Firejail, but it works since it's only ever used to signal the agent.

The problem remains that the agent isn't available right after the command runs and is put in the background. However, for interactive use, that's not really an issue.

**Comment by chiraag-nataraj** [comment]
I'm going to mark this with "workaround" and close this for now. @lhernanz, please feel free to re-open if you have more questions or if the workaround does not work for you.
