### ISSUE TITLE
Thunderbird not start with .icedove folder - Debian 9

### ISSUE THREAD

**Issue by frank-github** [netblue30/firejail#1686]
thunderbird.profile creates .icedove folder each time

with Debian9 Thunderbird will not start anymore, because an empty .icedove folder will prevent this.
Error: "something wrong with migration to thunderbird" (or something like that, from my memory)

removing line: mkdir .icedove in profile
removing this folder on disk
and thunderbird can start again  :-)

**Comment by netblue30** [comment]
I got the same thing here on my debian stable. It is a Thinderbird bug, there isn't too much we can do about it. Thunderbird starts with this message:

> usr/bin/thunderbird: [profile migration] Couldn't migrate Icedove into Thunderbird profile due existing or symlinked folder '/home/netblue/.thunderbird'!

and it will exit. It happens with or without Firejail.

For me the fix was to remove ~/.thunderbird directory (rm -fr ~/.thinderbird). Before removing it make sure the directory is empty, so you don't scrap your existing emails. Then, you have to start Thunderbird outside the sandbox by running /usr/bin/thunderbird. After importing your old profile from ~/.icedove, shut down Thunderbird and restart it in a sandbox (firejail thunderbird).

**Comment by frank-github** [comment]
Hi,
I can't agree. Problem occurs because a mkdir .icedove is made in the thunderbird.profile. 
if this folder is not removed, problem occurs again without starting through firejail or standalone.

No workaround is needed, only delete this folder .icedove and remove mkdir from thunderbird.profile
that's all  :-)

**Comment by Fred-Barclay** [comment]
@netblue30 I saw this too (around March, I think, when I was running Debian). Since we have a separate icedove profile already, and Debian oldstable and up ship thunderbird instead of icedove, would it hurt to remove the icedove configs from the thunderbird profile?

**Comment by Fred-Barclay** [comment]
I've commented out the icedove lines in the Thunderbird profile. Probably (hopefully) anyone on Debian 8 is running Thunderbird by now, anyone on Debian 9 or higher is definitely using Thunderbird, and Debian 7 users still have the Icedove profile.
