### ISSUE TITLE
transmission-qt freezes on opening dialogs

### ISSUE THREAD

**Issue by hubiqs** [netblue30/firejail#1736]
When trying to open dialogs in transmission-qt, the interface freezes and the application becomes a zombie. This includes using buttons Open, Open URL, and any dialog from the menues. The application must then be terminated manually.

This happens using the default profiles with no changes or .local-files. Running transmission-qt without firejail works fine. This behaviour has been confirmed on two separate systems running Arch, using basically the same config.

I believe this problem came about when KDE Frameworks was upgraded to 5.41.0, but I'm not certain. Might have happened on Qt upgrade to 5.10.0. Downgrading to test is troublesome for me running Arch, I'd rather not mess up my install, as I'm not an expert user. On that note, I'm not sure how to generate any meaningful logs. Nothing appears in the terminal, nor anything in the syslog that I can see.

This is all I get when it freezes and then manually TERMd:
```
$ transmission-qt
Reading profile /etc/firejail/transmission-qt.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 3343, child pid 3344
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 59.02 ms

Child received signal 15, shutting down the sandbox...

Parent is shutting down, bye...
```

If there's any more information I can supply, let me know, it's been quite a while now since I could use transmission-qt in firejail normally. For now I've been starting it outside firejail, adding the URLs I need, closing it, and then doing the downloads inside firejail (while making sure not to open any dialogs.)

firejail 0.9.52-1
transmission-qt 2.92-8
KDE Plasma 5.11.5
KDE Frameworks 5.42.0
Qt 5.10.0
Kernel 4.14.13-1 with CONFIG_USER_NS=y

---
Edit: Adding that ```$ firejail --noprofile /usr/bin/transmission-qt ``` works fine, so the problem is the profile?

---
Edit 2: Sometimes when I click a button, it spits out an error in the console as it freezes:
```UdevQt: unable to create udev monitor connection```

**Comment by hubiqs** [comment]
Commenting out ```memory-deny-write-execute``` in transmission-qt.profile seems to solve the problem. Any ideas what could be wrong?

**Comment by chiraag-nataraj** [comment]
Might be the QT bug again. Try the thing [here](https://github.com/netblue30/firejail/issues/1709#issuecomment-355862576).

**Comment by hubiqs** [comment]
Oh I should have mentioned that I've tried that, I need ```env QML_DISABLE_DISK_CACHE=1``` in order to fix okular anyway. Might still be related perhaps? The okular problems showed up at the same time as the transmission-qt ones.

**Comment by chiraag-nataraj** [comment]
Hmmm, that's weird. `memory-deny-write-execute` breaking it implies that `transmission` is doing some truly weird stuff imo...maybe use a different torrent client? :stuck_out_tongue_winking_eye:

**Comment by hubiqs** [comment]
Haha, maybe. But, it seems ```memory-deny-write-execute``` was added in August to ```transmission-qt.profile``` which means it has been like that since September's firejail 0.9.50 at least, and I definitely haven't had the problem that long, and transmission-qt was not updated during this time. Since okular and transmission-qt started misbehaving at the same time, I would still suspect Qt...

**Comment by netblue30** [comment]
Doing QML_DISABLE_DISK_CACHE=1 and QTWEBENGINE_DISABLE_SANDBOX=1 by default (hardocded).

https://github.com/netblue30/firejail/commit/1e7045b55cc1e189dba6d9ed21c05c90663f3736

@hubiqs - grab the latest from git and give it a try. Also try darktable. Do we still need to remove memory-deny-write-execute? Thanks.

**Comment by chiraag-nataraj** [comment]
@netblue30 I think you misunderstood. I added `memory-deny-write-execute` in my local profile just to see if it worked. It's not in the default profile.

**Comment by hubiqs** [comment]
@netblue30 I tried the latest version from master, and the problem with transmission-qt remains. Removing ```memory-deny-write-execute``` from transmission-qt.profile is still necessary.
Please note that ```env QML_DISABLE_DISK_CACHE=1``` is still present here:
https://github.com/netblue30/firejail/blob/a28fc4b2cd3c459ff87664aa4b761242aa1c2dc7/etc/disable-common.inc#L347
I commented it out, and tested okular, the hard-coded fix works fine for okular.

As far as darktable goes, it works fine in 0.9.52 and master. Adding ```memory-deny-write-execute``` doesn't break it for me (what specific breakage are you seeing @chiraag-nataraj?) but it is probably best left out at this time, since something's going on... But darktable isn't connected to anything Qt, is it?

**Comment by chiraag-nataraj** [comment]
@hubiqs `darktable` fails to start if I include it. Namely, SECCOMP kills `darktable` after it attempts to use `mprotect`. Regardless, that's a separate bug, so let's not pollute this issue with that :slightly_smiling_face:

**Comment by vn971** [comment]
Are there other Qt applications that explicitely need to use `QML_DISABLE_DISK_CACHE` and `QTWEBENGINE_DISABLE_SANDBOX` for them to work in firejail?
If not, I'd say it makes sense to add the rules to transmission-qt profile specifically, instead of disabling qt webengine sandboxing globally for all apps without warning.

**Comment by hubiqs** [comment]
@vn971 okular and viber seem to need ```QML_DISABLE_DISK_CACHE=1```. Probably connected to [this bug](https://bugreports.qt.io/browse/QTBUG-58508).
I'm not aware of any applications that need ```QTWEBENGINE_DISABLE_SANDBOX=1``` to function. It was suggested in the [viber-issue](https://github.com/netblue30/firejail/issues/1709), but never reported to have any effect...? https://github.com/netblue30/firejail/commit/1e7045b55cc1e189dba6d9ed21c05c90663f3736 might have been a bit premature.

transmission-qt doesn't seem to be affected by these options, only negatively by the presence of ```memory-deny-write-execute```, perhaps due to the above Qt bug.

**Comment by netblue30** [comment]
Removed meomory-deny-execute from transmission-qt profile: https://github.com/netblue30/firejail/commit/5cf5ec263660009e86f70b8c6aca156011f7541a

Removed QTWEBENGINE_DISABLE_SANDBOX=1 from the code: https://github.com/netblue30/firejail/commit/5e0daa3cd641e459c313f15d459a336ccd063961

Adding QTWEBENGINE_DISABLE_SANDBOX=1 to Viber profile: https://github.com/netblue30/firejail/commit/edc49d389e7531504aa9d7f2bef7a96080b8ccf0

**Comment by smitsohu** [comment]
Temporarily reopened for discussion of Qupzilla profile (also relevant for Falkon probably).

Firejailed Qupzilla is broken on a number of distros because Qt webengine is running at its core (just confirmed on Fedora), and I would like to extend the approach taken in [KMail](https://github.com/netblue30/firejail/blob/15d9ef1ba68914223fcd4a989c9c6df8b7565a1d/etc/kmail.profile) and [Qutebrowser](https://github.com/netblue30/firejail/blob/ca3964fed3f141e75bf396defaec3dca543ce49f/etc/qutebrowser.profile) profiles to Qupzilla, rather than adding QTWEBENGINE_DISABLE_SANDBOX=1 only to preserve the chroot seccomp filter.

While Firejail is modeled after the Chromium sandbox, it cannot replace it.... for users on a distro like Fedora, the security implications of disabling the built-in sandbox and replacing it with Firejail are non-trivial.

But also users on distros like Debian, where significant parts of the built-in webengine sandbox are not available because of missing support for unprivileged user namespaces, are not left out in the rain without `seccomp chroot`. They have `caps.drop sys_chroot` and `noroot` and indeed don't need the chroot seccomp filter that much, precisely because there are no unprivileged user namespaces.

I'd like to propose to move on, at least for browsers and the like, with dropping the chroot seccomp filter instead of replacing the Qt webengine sandbox altogether. Personally the feeling is rather that firejailing an app should always be a no-brainer.

Do I miss something? Other opinions?

**Comment by Vincent43** [comment]
When user namespaces aren't available chromium uses SUID Sandbox (which has same effect but needs setuid binary). Does Qt webengine do the same?

**Comment by smitsohu** [comment]
No, there is no SUID sandbox in Qt webengine, only seccomp and an unprivileged user namespace.

When the distro doesn't support unpriv user ns, there is only seccomp, IIRC.

**Comment by vn971** [comment]
@Vincent43 also binaries are not SUID if you have `--noroot` working.

**Comment by Vincent43** [comment]
That's why we don't use `noroot` in chromium profile 😀

**Comment by smitsohu** [comment]
@Vincent43 you're right, I will change my approach the next time
