### ISSUE TITLE
Can't combine --private with --whitelist

### ISSUE THREAD

**Issue by eevee** [netblue30/firejail#1743]
With `--private=DIR`, I can replace my entire home directory with a persistent substitute.  With `--whitelist=DIR`, I can preserve _part_ of my home directory while hiding everything else.  But there doesn't seem to be any way to combine these behaviors — e.g., if I want to run a game (which needs all its data files to exist) and still let it write out a save file to some undocumented place elsewhere in my home directory.

This is also troublesome for writing a flexible general-purpose profile.  If I put `private` in the profile, then I can't use `--whitelist` on the command line at all; if I _don't_ put `private` in the profile, then if I don't use `--whitelist` on the command line my entire home directory remains exposed.

In general it would be nice if `--private`, `--whitelist`, and `--overlay` had clearer interactions with each other.

**Comment by netblue30** [comment]
I started adding support for it. So far I have: private-dev, private-tmp and whitelist support for --overlay and --chroot sandboxes. You can try it out.

Support for --private=dir and --private-home is coming soon.

**Comment by qutetemp** [comment]
>whitelist support for --overlay and --chroot sandboxes. You can try it out.
Do I need the latest master because it doesn't seem to work.

**Comment by netblue30** [comment]
Yes, it is only in master. Also, there are some more general fixes related to overlay there. It will go into the next release.

**Comment by Ninlives** [comment]
What's the status for whitelist support for --private now?

**Comment by H8to** [comment]
Also hoping for this feature!
I use firejail as a Firefox profile template engine. For each of my customers the customer-template jail from a fully configured Firefox is copied to "customer-n", which then should be used for customer stuff (--private=customer-n). However I'd like to access e.g. downloads with other applications and this leads to problems as I cannot whitelist paths outside of the jail. Also copying from within the jailed Firefox is not possible as long as I can't whitelist my home/x/Desktop path.

**Comment by Vincent43** [comment]
Perhaps it's not complete solution for you but it's possible to transfer files from/to `--private` sandbox with `--get`/`--put` options. See `FILE TRANSFER` section in manpage.

**Comment by H8to** [comment]
Thank you for your suggestion, I read through it!

I know that's not really the point of a private "jail", but I'd like to be able to download something in the jailed Firefox and then move it to a folder that's shared with the jail via drag and drop. This is the most comforty option. Put and get are demanding to much effort as I could also then just open Nemo and dragNdrop the files or folders from the jail home/downloads folder.

**Comment by chiraag-nataraj** [comment]
@H8to I actually have a similar system for so-called "ephemeral profiles". The script is in my [Firejail Profiles](https://github.com/chiraag-nataraj/firejail-profiles) repo and is called `firefox.common`. If you don't want `firefox` to be able to access other profiles, you can just use a `--whitelist` command to whitelist only that specific profile instead of whitelisting `~/.mozilla/firefox`. You could probably adapt a simpler version of the script for your use.

**Comment by Vincent43** [comment]
Also making  `--whitelist` compatible with `--private` is not that easy. Currently `--private` can be used on top of any existent profile and it always give you separated  and temporary `$HOME` regardless of what rules specific profile contains. If we make it compatible then suddenly all  `--whitelist` rules existent in profile will take effect which make `--private` not effective. Perhaps separated option like `--private-whitelist` may be used if anything to no break existing usage.

**Comment by chiraag-nataraj** [comment]
To add to that, more fundamentally, a "private" jail is not _meant_ to share data with other jails or the host. That's the whole point of a private jail. It's basically meant to act as a chroot for your home directory (which can be set-up by a regular user). If you want to share data, you're probably better off figuring out a solution with `whitelist` and scripts (such as the `firefox.common` script I alluded to in my previous reply).

**Comment by Vincent43** [comment]
Yeah, I fully agree. Should we close this as wontfix? :smile:

**Comment by chiraag-nataraj** [comment]
@Vincent43 Let's close it for now. If it seems like there is a legimate reason to reconsider it, we'll re-open it.

**Comment by modelfe** [comment]
I'm not sure I understand the reasoning for the wontfix here.

In my case, I'm using a firejailed Firefox browser profile for my work. Using --private=~/work is super useful, as it allows me to have a persistent Firefox browser profile setup, while isolating the browser from everything outside the work directory. However, I have a large number of media files in a directory on a separate HDD that I'd like to be able to regularly access from this Firefox profile. Being able to simply whitelist the desired media directory so I could access it would be enormously useful.

Please consider somehow adding this functionality.

**Comment by modelfe** [comment]
To follow up on my last post; it turns out it actually is possible to do this by whitelisting the media directory in a custom firejail profile. But whitelisting the same directory with --whitelist does **not** work.

So including `whitelist /media/<username>/work_media` in a custom firejail profile works, even when launching with --private=~/work
But launching with `--whitelist=/media/<username>/work_media` does not.

Is there a reason for this inconsistency, or is this a bug?

**Comment by rusty-snake** [comment]
@modelfe `--private` "breaks" `whitelist`ing only in $HOME.

> Is there a reason for this inconsistency, or is this a bug?

If you for example run `firejail --whitelist=/media/<username>/work_media firefox`, firejail will load the firejail profile which contains `disable-mnt`. `disable-mnt` `blacklist`s `/mnt`, `/media`, ... .You can try adding `--noprofile` or `--ignore=disable-mnt`.

**Comment by 3ThumbsUp** [comment]
I'd like to voice support for this feature.

One of my use cases is that I use firejail with Steam. As Steam seems to clutter the home directory more than any other program, I've given it its own firejailed home. That way Steam can do whatever it wants to, and all the clutter is out of my way in a separate directory. However, this limits some of the features. For example, I would still like Steam to be able to create desktop shortcuts, but for this to work, it needs access to /usr/share/applications and /usr/share/icons in the real home directory.

The same argument goes for some proprietary video editing software (Davinci Resolve in my case). I want to give it its own home directory to not clutter my personal home, but it obviously still needs access to my Video directory. And I can't just use regular whitelists without private mode, because the files it creates are still important for functionality. I just want to avoid unnecessary clutter in my home directory while still sharing a few important directories with the firejailed application.

I like Vincent43s suggestion of a separate whitelist to not break existing functionality. In any case, not being able to share some directories between the personal home and the firejail home is limiting some functionality.

**Comment by evren320** [comment]
I need this feature too.
A separate permanent home for the app, with some folders of the user home accessible.
As a workaround, mount --bind serves this purpose, but requires root password to run every time launching the app and raises some security concern.

**Comment by hvhaugwitz** [comment]
An option like `--private-whitelist` has legit use cases (see comments above).

Please consider reopen this bug/feature request.

**Comment by pjhfggij** [comment]
Why was this feature rejected? It makes sense to be able to poke holes in --private with --whitelist or --dbus-user filter. I've had to spend an hour just to replicate --private in [librewolf.local profile](https://0x0.st/X0qm.txt
). Once it's work it's fine, but I'm not looking forward having to redo this for other programs.

Flatpak has such a feature and many easy interfaces to poke holes in sandbox? Why not add it to firejail?

**Comment by kolAflash** [comment]
It took me quite some time to figure out how `--noprofile`, --private` and `--whitelist=...` interact.  
**Please add some documentation.**  
Either in the man-page. Or ideally `firejail` should report an error if the user calls `firejail --private --whitelist=/home/$USER/something`.

I saw that `--private` added some helpful blacklisting outside of `/home/`, like `/etc/ssh/`. I'd like to have a way, how I can easily get this additional blacklisting (e.g. `/etc/ssh/`) while having the ability to whitelist directories in `/home/`.  
Currently I'm using:
```bash
firejail \
  --noprofile --disable-mnt --private-dev --private-tmp --whitelist=/home/$USER/Downloads/ \
  $(for i in /etc/apparmor /etc/apparmor.d /etc/chatscripts /etc/cron.d /etc/cron.daily /etc/cron.hourly /etc/cron.monthly /etc/cron.weekly /etc/cron.yearly /etc/default /etc/dkms /etc/grub.d /etc/init.d /etc/kernel /etc/logcheck /etc/logrotate.d /etc/modules-load.d /etc/rc0.d /etc/rc1.d /etc/rc2.d /etc/rc3.d /etc/rc4.d /etc/rc5.d /etc/rc6.d /etc/rcS.d /etc/ssh /opt /srv; do echo --blacklist=$i; done)`
```

**Comment by rusty-snake** [comment]
- it does not
- this is already documented
  - see response in #6639
  - we could make the security implications clearer like "Do not use a security profile. UNSECURE! Only for testing or special use.". On the other hand `default.profile` isn't secure either.
- is half-true and already documented
- send a PR to document it

**Comment by kolAflash** [comment]
@rusty-snake  
>> "--whitelist=" automatically hides "$HOME"
> * is half-true and already documented

Thanks! Can you post a link?

**Comment by rusty-snake** [comment]
manpage:

> Whitelist directory or file. A temporary file system is
mounted on the top directory, and the whitelisted files are
mount-binded inside. Modifications to whitelisted files are
persistent, everything else is discarded when the sandbox
is closed. The top directory can be all directories in /
(except /proc and /sys), /sys/module, /run/user/$UID, $HOME
and all directories in /usr.

and https://github.com/netblue30/firejail/wiki/Creating-overrides

if you have ideas how this can be documented in a better way, send a PR.

**Comment by rusty-snake** [comment]
#6622 had been merged
