### ISSUE TITLE
Most part of messangers can't open links in browsers other than firefox

### ISSUE THREAD

**Issue by dmitryvakulenko** [netblue30/firejail#1770]
I use Mint 18.3. When I change my default browser to google-chrome external links from firejailed messanger stops to open. This behaviour I see in Telegram, Stride, Slack.
In terminal where are single error
`[1:1:0209/174804.713575:ERROR:nacl_fork_delegate_linux.cc(316)] Bad NaCl helper startup ack (0 bytes)`

**Comment by SkewedZeppelin** [comment]
This is a known issue. Its not really an issue just more of a limitation. When the messenger goes to open the link, it launches the browser itself, in the context of itself. Meaning the browser cannot access its files (due to the sandbox) and crashes/throws errors.

As for why links work in Firefox: it uses some weird way of keeping track of its instance and even if you run Firefox from in a sandbox, it'll somehow open the page in a currently running instance outside of the sandbox.

The workaround is to either use Firefox as your default browser, or manually copy/paste links when you need.

I'm sure there are issues that describe both in more detail, but I cannot seem to find any.

**Comment by dmitryvakulenko** [comment]
Thank you for detailed answer!

**Comment by RalfJung** [comment]
> As for why links work in Firefox: it uses some weird way of keeping track of its instance and even if you run Firefox from in a sandbox, it'll somehow open the page in a currently running instance outside of the sandbox.

That was actually quite nice when it lasted, but it has stopped working a while ago.
If anyone has an idea for how to get Firefox to do this again, that'd be great!

**Comment by RalfJung** [comment]
I don't have `nodbus` set in this profile.

But https://github.com/glitsj16/firejail-handler-http looks great, thanks! Though I will have to understand the difference to https://github.com/glitsj16/firejail-handler-extra, they seem to be almost the same.
