### ISSUE TITLE
Konsole forgets theme

### ISSUE THREAD

**Issue by idnovic** [netblue30/firejail#1789]
Konsole forgets the console theme. Not the gui. I am talking about the terminal itself.

I do not know how to explain why it happens or when.
But unter "settings - profiles" new profiles get created "Profile 1" "Profile 2" etc
They increase in the numbering.

The bug is that I configured a theme and it gets ignored.
I tryed to fix it by editing the theme config files in the filesystem (home)
`/home/idnovic/.local/share/konsole/`

I deleted the other profiles. I can not regenerate the error now.

**Comment by SkewedZeppelin** [comment]
We don't provide a profile for Konsole, which profile are you using?

**Comment by idnovic** [comment]
my bad, I think it happend if I open konsole over dolphin.
Yes just tested it. The new Konsole window lost the settings again.
Well I think the dolphin profile is responsible.

Does it make sense to allow `.local/share/konsole/` ?? reading for dolphin
The new konsole window is not sandboxed but opened over dolphin it forgets the settings.

**Comment by idnovic** [comment]
and now the normally opened konsole window lost its thema too.
The konsole window opened over dolphin must have set the "new" thema

**Comment by smitsohu** [comment]
If you go to disable-common.inc and change `blacklist ${HOME}/.local/share/konsole` to `read-only  ${HOME}/.local/share/konsole`, does it fix your issue?

IMHO `read-only` should actually be sufficient from a security perspective.

**Comment by idnovic** [comment]
No it does not.
It seems my default profile does not get loaded. I can select it in the options as default profile and nothing happends (only profile).
If I now click on < Settings - Switch profile - my profile > it loads the profile.

maybe their is an configuretion file stored somewhere else.

**Comment by idnovic** [comment]
I choose "run in single instance" in the options of konsole. Still opens an other instance.
Thema is fine for the time beeing.

**Comment by smitsohu** [comment]
If konsole is launched through dolphin, it runs inside the dolphin sandbox. This makes all custom profiles inaccessible, because they are stored in `~/.local/share/konsole` which is blacklisted. 

The konsole _default_ profile is defined in `~/.config/konsolerc`. It seems that if konsole can't find this default profile in (blacklisted) `~/.local/share/konsole`, it partially resets `~/.config/konsolerc`, leading to described behavior.

The loss of konsole settings can be prevented by `read-only ~.config/konsolerc`, should it not be sufficient to switch from `blacklist ~/.local/share/konsole` to `read-only ~/.local/share/konsole`.

Thank you for the bug!

**Comment by idnovic** [comment]
It is fixed for me with your suggested edits.
Thank you. You can close this now after you fixed it in the source code :+1:
