### ISSUE TITLE
hidepid prevents me from viewing firejail-started processes in e.g. htop

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1798]
So I don't know if this is intended behavior. When I start a sandbox, _sometimes_ the resulting processes do not show up in process monitors like `top`, `htop`, or `ps aux`. I think it has to do with the _noroot_ option, since the only ones that _do_ show up are Electron apps, which I cannot use `noroot` with (`libnode.so not found` or whatever). Is this intended behavior and, if so, why?

**Comment by chiraag-nataraj** [comment]
Oh, and the best part is that the processes are owned by me, so they _should_ show up.

**Comment by netblue30** [comment]
This happens because of --noroot. It installs a new user namespace with a new user, Even if the new user has the same name as your regular user, for the process handling code in the kernel this is a different user. Interesting, the file system still thinks is the same user, so you have access to your files.

Just use firejail --list, --top etc to list the processes. Also with hidepid you would need to be root to run firemon and firetools.
