### ISSUE TITLE
Viewnior will not run with memory-deny-write-execute

### ISSUE THREAD

**Issue by Tanath** [netblue30/firejail#1808]
Using `firejail 0.9.52-1`.
Had to disable `memory-deny-write-execute` to get viewnior to run, else it would hang after `Child process initialized`.

Also, I'd really like to know why the default profile grants access to Steam.

**Comment by SkewedZeppelin** [comment]
See #1803 

As for why Steam is allowed see 6262b3078ce98154a14b1481f71fe378c2dc886b, its meant to allow people to open their screenshots.

**Comment by Fred-Barclay** [comment]
Thanks! Unless someone else beats me to it I'll get a fix in soon. :-)
Can I ask what distro and desktop environment you're using?

We grant access to steam folders so that screenshots taken in steam can be viewed with your default image viewer. There's an issue or pull request somewhere around here with more info, I'll see if I can find it and post a link here.
Cheers!
Fred

**Comment by Tanath** [comment]
Manjaro XFCE.

**Comment by SkewedZeppelin** [comment]
@Tanath are you on kernel 4.15.6 or higher?

**Comment by Tanath** [comment]
I'm on 4.14.
