### ISSUE TITLE
https://firejail.wordpress.com/support/#userns outdated

### ISSUE THREAD

**Issue by polyzen** [netblue30/firejail#1842]
Arch Linux has supported user namespaces in the `linux` package/s [since version `4.14.4-2`](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=e42e6ffc6243370215eb33690b3c68f96f181cdb). The [bug](https://bugs.archlinux.org/task/36969) mentioned is closed.

**Comment by Vincent43** [comment]
It's supported but still [disabled](https://wiki.archlinux.org/index.php/Security#Sandboxing_applications) by default. It's exactly what Debian does for a long time.

**Comment by netblue30** [comment]
Thanks, I modified the web page. The problem was user namespace wasn't compiled in the kernel, so they put it in and disabled it. We can use it even if it is disabled.

**Comment by Fred-Barclay** [comment]
@Vincent43 it's enabled for `root` though (or other similarly-priviledged users), right? Since firejail uses SUID, is it able to use namespaces?
I did noticed that I no longer get the `Warning: noroot option is not available` on Arch. I'm not sure if this is because namespaces are now compiled in but non-accessible to firejail, or if firejail is actually able to use them.

**Comment by Vincent43** [comment]
@Fred-Barclay yes, I should say "restricted" rather than "disabled".  I have no idea if firejail use namespaces when they're restricted to root. Maybe @netblue30 could clear that for us. Also I read that privileged namespaces have no security value.
