### ISSUE TITLE
few questions about firejail

### ISSUE THREAD

**Issue by justme55432** [netblue30/firejail#1921]
first of all thank you guys for the great job on develop firejail i wanted to ask few questions that i didn't find online.

1) If attacker know i use firejail on chrome can he target the fairjail rather than the browser to find vulnerabilities, and use it to try  hack my system ?

2) What are the chances that  firejail contain high risk vulnerabilities than the software it try to protect the system of, e.g chrome browser. ?

3) If i use firejail on chrome and hacker find exploit in chrome and use it to  gain access to whatever he can inside firejail restriction, when i remove and reinstall  chrome did the hacker exploit session remove with it, and  the hacker start in point 0  or whatever he was before taking advantage of the exploit ?

4) Or refer to question 3 the only way is to reinstall the OS ? and i mean in both of the question using the firejail as the default command : firejail google-stable and not firejail -private google-stable. 

thanks in advance and i apologize for my bad English.
hope you can understand if not i will try to rephrase the question,

**Comment by Fred-Barclay** [comment]
G'day @justme55432 ! I'll do my best to answer, but some of these are just my opinion. :smile: 
1. Yes, the attacker could target firejail specifically. After starting the sandbox, though, firejail "goes to sleep" so to speak, meaning that by the time Chrome starts firejail is (mostly) inactive. It should be much harder to attack firejail.
The only "attacks" for firejail that I've seen to date (and they were all proof-of-concept demos rather than real-life attacks) relied on running the proof-of-concept directly through firejail, rather than running the proof-of-concept through a program that was started with firejail.

2. There are no known vulnerabilities in firejail that I'm aware of. We try to be very responsive on patching any known vulnerabilities as soon as they are disclosed.
You can see a list of past vulnerabilities in https://firejail.wordpress.com/download-2/cve-status/

3. Our Chrome profile is pretty restrictive, so most likely removing the whitelisted folders in the profile would be enough. Certainly for an unskilled, drive-by attack I would feel confident with this approach.

It's hard to prove a universal negative though -- possibly a dedicated attacker could manage to break out of firejail, though I am not aware of any methods to do this.

Cheers!
Fred
