### ISSUE TITLE
Firefox version 60 breaks completely with the default Firejail profile or any profile containing seccomp.

### ISSUE THREAD

**Issue by dkwls** [netblue30/firejail#1939]

**Comment by SkewedZeppelin** [comment]
See #1930 and #1937 

The fix (#1935) has been merged and is in master as 64914b7ae78484483dd0f736f3eefcec4342482e

**Comment by dkwls** [comment]
Thanks for the response. I may be missing something but weather or not tracelog is in the profile appears to have no effect at least in version 0.9.52. Commenting out seccomp is the only way I have found to get Firefox to work again. I have tested this problem in Ubuntu 18.04 and 17.10.

**Comment by smitsohu** [comment]
@dkwls Which Firejail version do you use?

**Comment by smitsohu** [comment]
We had to take out chroot from the seccomp filter to get Firefox working. If you replace `seccomp` with the following long line it should work again: 

`seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice` 

This will be fixed in 0.9.54.

**Comment by Vincent43** [comment]
Here's some info about sandboxing in FF 60: https://www.morbo.org/2018/05/linux-sandboxing-improvements-in_10.html

**Comment by Wolf-Italy** [comment]
To your kind attention.

I would like to point out, a problem between firejail and the 
new version of Firefox 60.0

I just installed the new version of Firefox 60.0, 
in Linux Mint 18.3 Sylvia

I use LTS version firejail_0.9.38.12_1_amd64.deb

The Browser starts, but the page remains blank.

See screenshots:

https://imgur.com/a/YE2L2Et

This problem seems to be the same, which happened a while ago,
With the Sandboxie program, the problem was due to 
Multiprocess function.

Translated with www.DeepL.com/Translator

**Comment by dkwls** [comment]
@smitsohu thank you that fixed the problem for me.

**Comment by Queeq** [comment]
I tried using `seccomp.keep` option instead of listing all syscalls explicitly (this is much cleaner), but it then fails to start:
```
Error: cannot establish communication with the parent, exiting...
```
Do I understand its function incorrectly?

**Comment by Vincent43** [comment]
`seccomp.keep` is the opposite of `secomp.drop`, it creates whitelist instead of blacklist. You have to pass explicitly each allowed syscall, probably not what you want.

**Comment by Queeq** [comment]
Right, so I was trying to pass chroot.

**Comment by Fred-Barclay** [comment]
@Wolf-Italy Excellent, that's exactly what we want to hear. Thanks!
