### ISSUE TITLE
[ Information ] Linux Mint 19 “Tara” Cinnamon – BETA Release

### ISSUE THREAD

**Issue by Wolf-Italy** [netblue30/firejail#1982]
I would like to point out that these two warning voices appeared this morning, 
After installing firejail_0.9.54_1_amd64.deb in 
Linux Mint 19 Cinnamon "Tara" - BETA Release under test
in the virtual machine, at the start of Firefox Quantum 60.0.1
---
See screenshot attached:
---
![schermata del 2018-06-07 11-07-50](https://user-images.githubusercontent.com/39192663/41101373-3d6f7cbe-6a64-11e8-995b-f0e50596a910.png)

**Comment by chiraag-nataraj** [comment]
I get the same warning, but nothing seems to be affected. Are you having problems with Quantum or do you just get the warning with no effects?

**Comment by Wolf-Italy** [comment]
To the attention of Mr: chiraag-nataraj

Unfortunately I am not a Technician, so I am not able to 
evaluate any problems.

In use there seems to be no problem.

I have just pointed out these two warnings for information,
appeared for the first time this morning, after having 
installed Firejail and started using it with Firefox and the new 
version of Linux Mint.

It should be the Firejail Team that assesses the two alerts 
and possible solutions to any problems.

Translated with www.DeepL.com/Translator

**Comment by Fred-Barclay** [comment]
Hi @Wolf-Italy 
Thanks for the info. Those appear to be simply harmless messages from fire**fox** reporting that it is unable to access dbus. This is expected as firejail blocs dbus access for firefox since our last release, v0.9.54.
If I understand your last post correctly, there aren't any breakages or instabilities caused by this, so I think we can close.

Cheers!
Fred
