### ISSUE TITLE
profile weechat broken

### ISSUE THREAD

**Issue by cyrinux** [netblue30/firejail#2013]
Hi, weechat profile is broken
```
❯ weechat            
Reading profile /etc/firejail/weechat.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Parent pid 26649, child pid 26650
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Child process initialized in 62.03 ms
Error: unable to create/append to log file (weechat.log)
If another WeeChat process is using this file, try to run WeeChat
with another home using the "--dir" command line option.

Parent is shutting down, bye...
 ```

**Comment by glitsj16** [comment]
@cyrinux For me weechat 2.1 is working fine with latest firejail from git. The error 'unable to create/append to log file (weechat.log)' might prove worthwhile looking into. Have you tried that yet? Something like the below would rule out any WeeChat process conflicts:
```
(1) copy regular weechat config dir to a test dir
$ cp -fr $HOME/.weechat $HOME/.weechat-test
(2) run firejailed weechat using the created test dir
$ firejail --whitelist=$HOME/.weechat-test /usr/bin/weechat
```
After this test you can safely remove the created test dir. If you could provide output of those commands here, together with firejail version info, people would be in a better position to get to the bottom of your issue.

Regards

**Comment by Fred-Barclay** [comment]
Also does `firejail --noprofile weechat` work?

**Comment by cyrinux** [comment]
Hi,
It is with archlinux updated running weechat 2.1 
The two try works which start weechat without configuration.

**Comment by glitsj16** [comment]
If --noprofile is working the issue isn't with the firejail profile. Your error message suggests there were several weechat processes running and apparently one of those had an exclusive lock on ~/.weechat/weechat.log. That's why I suggested to test with a temporary copy of your ~/.weechat dir to confirm all this. But I see now there was an ommision in the commands I gave above, my bad. The last command (to test firejailed weechat with a temp dir) should read:
```
$ firejail --whitelist=$HOME/.weechat-test /usr/bin/weechat --dir $HOME/.weechat-test
```
You could rm -f ~/.weechat-test/weechat.log from the test dir before running that, it should be recreated by WeeChat on a succesful start. Hope this helps.

**Comment by cyrinux** [comment]
Hi @glitsj16, thanks, this try works, without removing the log

**Comment by cyrinux** [comment]
So here the working profile
```
# Firejail profile for weechat
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/weechat.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.weechat
whitelist ${HOME}/.weechat

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc

caps.drop all
netfilter
nodvd
nonewprivs
noroot
notv
protocol unix,inet,inet6
seccomp

# no private-bin support for various reasons:
# Plugins loaded: alias, aspell, charset, exec, fifo, guile, irc,
# logger, lua, perl, python, relay, ruby, script, tcl, trigger, xferloading plugins
```

**Comment by alrayyes** [comment]
This isn't a weechat issue. The default profile doesn't allow writing to the logfile period. The error weechat throws isn't very helpful in this regard.

This is easily fixed with the following profile:

```
include /etc/firejail/weechat.profile
read-write ${HOME}/dotfiles/weechat/.weechat/weechat.log
```

According to the [documentation](https://weechat.org/files/doc/stable/weechat_user.en.html) writing weechat.log to ~/.weechat is default behaviour, therefore the read-write line should be added to the default weechat firejail profile.

**Comment by glitsj16** [comment]
@alrayyes Nobody suggested it was/is a weechat issue.

> If --noprofile is working the issue isn't with the firejail profile.

That remark was related to help the OP in debugging what was going on exactly. Since then the weechat.profile has changed and doesn't have the 'whitelist ${HOME}/.weechat' any longer. But it still has 'noblacklist ${HOME}/.weechat' to counterpart blacklisting done via the included 'disable-programs.inc' (a common practice in firejail profiles). Having `noblacklist ${HOME}/.weechat` already takes care of making ${HOME}/.weechat read-write.

> read-write ${HOME}/dotfiles/weechat/.weechat/weechat.log

As far as I can read in weechat's documentation that isn't weechat's default home dir location. If you use the -d/--dir <path> (or an env var for that matter) with weechat to override its default home dir you should do the same for its firejail profile and add that custom path in a weechat.local file (either in /etc for system-wide support or in ~/.config/firejail for per user support). Is this not working for you?
