### ISSUE TITLE
Snapper - **/.snapshots

### ISSUE THREAD

**Issue by Saren-Arterius** [netblue30/firejail#2030]
I am using default rules for firefox and I discovered that Snapper+btrfs's /.snapshots is unmasked, which means firefox can access it, also the files intended to protect (ssh keys...)

Please `blacklist /.snapshots` or even `blacklist **/.snapshots` if possible in `disable-common.inc`.

**Comment by chiraag-nataraj** [comment]
@Saren-Arterius Since I don't user snapper at all and don't really know how the layout works (one `.snapshots` directory per filesystem? one per mountpoint? one global one?), I just blacklisted `/.snapshots` for now. Honestly, this tells me we should be working towards a generic whitelist-based system in terms of firejail defaults (right now, you can only whitelist stuff with a top directory of `~/`, `/dev`, `/etc`, `/media`, `/mnt`, `/opt`, `/srv`, `/sys/module`, `/usr/share`, `/var`, and `/tmp`). I'm not quite sure why we don't allow a whitelist of arbitrary paths (maybe @netblue30 can answer that?), but that is something I'd like to see (basically, let's give `whitelist` the same level of generality as `blacklist`).

**Comment by Saren-Arterius** [comment]
Hi, .snapshots is per filesystem or subvolumes for btrfs. I dont know about
LVM.

在 2018年7月11日週三 15:47，ಚಿರಾಗ್ ನಟರಾಜ್ <notifications@github.com> 寫道：

**Comment by chiraag-nataraj** [comment]
谢谢! Actually, in this case, an apparmor profile addition may be more warranted, since I'm not _entirely_ certain how globbing works with `blacklist` in firejail. That is, I'm not sure if e.g. `**/.snapshots` would match any `.snapshots` directory on the system or whether it would only match `.snapshots` directories below a top-level directory. With AppArmor, the globbing itself is fairly well documented (as well as with a couple of examples). So we can definitely block `/.snapshots` by default (as I put in), but something more dynamic like what you are looking for may be better served through AppArmor.

**Comment by chiraag-nataraj** [comment]
I could also be entirely mistaken and `**/.snapshots` would match any `.snapshots` directory on the system... :joy:

**Comment by chiraag-nataraj** [comment]
I'll change it to `**/.snapshots` and close this for now.

**Comment by chiraag-nataraj** [comment]
So...`**/.snapshots` will _not_ do what you want. Leaving this open for now until I find a resolution.

**Comment by chiraag-nataraj** [comment]
It will only block `.snapshots` directories at most one level below `/` (e.g. `/home/.snapshots` is blocked, but `/home/<user>/.snapshots` is not). I will look into putting in an AppArmor rule.

**Comment by chiraag-nataraj** [comment]
Okay, the AppArmor glob does what you want - it blocks all .snapshots directories no matter how deep they go. See 6108f459e375151e95bedf7090eb9b84169479e8.
