### ISSUE TITLE
Virtual environements

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2085]
Is it possile to configure Firejail to have access to files in a virtual environment so any changes it does, it doesn't affect the actual files but the changed files are stored in a virtual environment?

**Comment by trialism** [comment]
How would you handle the changes in the original environment?

**Comment by chiraag-nataraj** [comment]
One way you can do this is use `--private-home` (or `--private` or whatever) and manually copy over files if you want to keep changes. If you don't want the files to be changed, `--private` and associated options should be enough.

**Comment by Raj2032** [comment]
Hi @chiraag-nataraj, if I do this `--private-home`, would the changed files be retained in the virtual environment or would they be deleted after program termination?

**Comment by chiraag-nataraj** [comment]
From the man-page:
```
Build  a  new  user home in a temporary filesystem, and copy the files and directories in the list in the new home. All modifications are discarded when the sandbox is closed.
```
The modified files are deleted upon termination.

**Comment by Raj2032** [comment]
Is it possile to some how keep the files in the virtual environment
retained without firejail having to delete these files automatically?

**Comment by chiraag-nataraj** [comment]
Not presently, no. But what exactly are you trying to do? Maybe we can help with the actual usecase.

**Comment by Vincent43** [comment]
I think you are looking for `--overlay` option. It will store your changes persistently in `$HOME/.firejail/<NAME>`, see `man firejail` for details

`firejail --overlay-named=<NAME>1 firefox`

**Comment by chiraag-nataraj** [comment]
@Vincent43 Oops. Completely forgot about `overlay` options :joy:

**Comment by Raj2032** [comment]
One last question guys, is it possible to install applications on a virtual
environment as well?

**Comment by Vincent43** [comment]
No, but there is [AppImage](https://appimage.org/) integration. You may also look at [flatpak](https://flatpak.org/)/[snap](https://snapcraft.io/).

**Comment by chiraag-nataraj** [comment]
> One last question guys, is it possible to install applications on a virtual environment as well?

I guess I'm somewhat confused as to what level of integration you want with the rest of the system.

If you want an _isolated_ environment, what you're really looking for is a "container" solution (e.g. [Docker](https://www.docker.com/), [LXC](https://linuxcontainers.org/), etc) or a "virtual machine" (e.g. [QEMU](https://www.qemu.org), [VirtualBox](https://virtualbox.org), etc). If you want to restrict what programs can do within your _already existing system_, that's where "sandboxes" come in (e.g. firejail, AppArmor, SELinux).

Your initial question made sense within the context of sandboxing, since it's basically ensuring that you always have a known "good" base (that is, if something happens, you can wipe the overlay and start over). But your second question seems to imply that you almost want this virtual environment to function like a full system, in which case you're probably better off with a container solution.

**Comment by chiraag-nataraj** [comment]
@Raj2032 Sorry, this is the wrong forum for that. I haven't really done much with containers and you're better off doing your own research. As with all other software, "best" really depends on what you want to accomplish.

As for encryption, I don't know, but I don't see why it would be out of the question. Worst case, just use [encfs](https://vgough.github.io/encfs/) to create an encrypted mount and setup the container within that (the docs for encfs are pretty good).

I'm going to go ahead and close this issue now, since we're _way_ off the original topic.

**Comment by Raj2032** [comment]
Thanks for your help.

**Comment by Raj2032** [comment]
Sorry again to distrube you I just really want to get a really good setup,
something that will work for me. On EncFS, it is not clear, is it a linux
container or not?

**Comment by Raj2032** [comment]
Oh sorry yeah it is a Linux container thanks then.
