### ISSUE TITLE
Split up disable-mnt

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#2154]
We should split `disable-mnt` into two different directives (`disable-mnt` and `disable-media`) to make things more granular.

**Comment by chiraag-nataraj** [comment]
Alternate proposal by @smitsohu: Turn `disable-mnt` into a set of ordinary `blacklist` commands, which can be overridden as usual with `noblacklist`.

**Comment by smitsohu** [comment]
Adding some advertisement for my own proposal: I doesn't change the meaning of an existing option and hence doesn't create a need to update existing profiles.
Also I recall people actually trying to noblacklist /media or /mnt in order to get their setup working, and posting to the bug tracker because that didn't work.

**Comment by startx2017** [comment]
We have disable-mnt in firetools GUI. Replacing it with blacklists in profile files should be fine.

**Comment by Fred-Barclay** [comment]
@smitsohu Would `disable-mnt` just blacklist /mnt  as a whole?

**Comment by smitsohu** [comment]
@Fred-Barclay Like it does currently, yes.

**Comment by Vincent43** [comment]
I think splitting `disable-media` will only add maintenance burden as there will be yet another option to add to each profile. Changing it behavior to work as  `--blacklist=/media` `--blacklist=/run/media` `--blacklist=/mnt` which will be overridsble with `--noblacklist` sounds much better.
