### ISSUE TITLE
whitelist globbing

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#216]
I was trying to rewrite/streamline my Firejail profile for LibreOffice. One rule which I tried was

whitelist ~/*.odt

but that doesn't work. It does work, though, in the form

whitelist ~/Example.odt

So it seems that placeholders are not supported. This would be a very useful enhancement in Firejail, indeed!

**Comment by netblue30** [comment]
I'll implement it, thanks for the idea!

**Comment by curiosity-seeker** [comment]
Great - thank you very much in advance! 

BTW, it would be nice if one could add several file suffixes in one line if possible. Something like

whitelist ~/*.odt, *.doc, *.docx

or

whitelist ~/*.odt | *.doc | *.docx

just to keep the profile more readable.

**Comment by netblue30** [comment]
I'll try that one also.

**Comment by avoidr** [comment]
Maybe in Bash syntax:
whitelist ~/*.{odt,doc,docx}

**Comment by netblue30** [comment]
several similar requests to follow:

**Comment by netblue30** [comment]
Also allow [](){}

**Comment by vn971** [comment]
Even more important for me personally: `[]`.

**Comment by msva** [comment]
Any updates on this?

**Comment by julianschacher** [comment]
I'm currently working on enhancing the Thunderbird profile, so that Thunderbird can set itself as the default mail-program (and other things).
Thunderbird needs to modify the `~/.config/mimeapps.list`-file for that. It does that by first creating a file named `~/.config/mimeapps.list.randomBit` (where `randomBit` are 6 random characters `[a-zA-Z0-9]`) and then renaming this temporary file to `~/.config/mimeapps.list` to make the change.

For that enhancement to be done, whitelist globbing would be needed I think.

**Comment by rusty-snake** [comment]
@julianschacher  #2874

**Comment by julianschacher** [comment]
> @julianschacher #2874
@rusty-snake Thanks for the link! That's really an unfortunate issue.

**Comment by rusty-snake** [comment]
601df2f

**Comment by danielkrajnik** [comment]
is it possible to use it resursively, that is all *.mp4 files in a directeory and its subdirectories?

**Comment by rusty-snake** [comment]
`man 7 glob`:

> Globbing is applied on each of the components of a pathname separately.  A '/' in a pathname cannot be matched by  a  '?' or  '*'  wildcard

**Comment by danielkrajnik** [comment]
I see, so glibc doesn't provide a way to do it? Is there no other way to whitelist all files of specific format (e.g. *.mp4) in all subdirectories?

**Comment by rusty-snake** [comment]
If the (sub)directory structure isn't to deep, you can

```
whitelist ${HOME}/Downloads/*.mp4
whitelist ${HOME}/Downloads/*/*.mp4
whitelist ${HOME}/Downloads/*/*/*.mp4
```

**Comment by danielkrajnik** [comment]
Thanks, it is quite deep unfortunately (network mount). Ideally there would be a way to whitelist only certain files in such large directories rather than all of it.

**Comment by glitsj16** [comment]
@danielkrajnik Maybe you could write a shell script from where you pre-select the (*.mp4) files you want to whitelist and bind mount them in a specific location. That way you can blacklist your network mount and only whitelist the new mount path. Have you tried that yet?

**Comment by rusty-snake** [comment]
You can use find+xargs:

```bash
find ~/Videos -type f -name "*.mp4" -printf "--whitelist=%p\0" | xargs -0 -x -s 65536 /bin/sh -c 'firejail "$@" /usr/bin/totem'
```

_I'm not sure if you can perform injections with this command (spaces in filenames work), but if this is an untrusted network mount, you should check this._

**Comment by danielkrajnik** [comment]
Thanks, that may work, but a cron job for this script would need to run regularly as well, because files will change. It may lead to a situation where the program won't be able to access a file, because script didn't run yet. I've heard about inotify interface, but I don't know if it works on network shares. Hope that makes sense.
