### ISSUE TITLE
unable to authorize user to use firejail

### ISSUE THREAD

**Issue by millerthegorilla** [netblue30/firejail#2225]
my user exists in /etc/firejail/firejail.users but I get the following message:
> Error: the user is not allowed to use Firejail. Please add the user in /etc/firejail/firejail.users file, either by running "sudo firecfg", or by editing the file directly.
> See "man firejail-users" for more details.

I am running fedora 28 with gnome 3.  my userid is normal at 1000, and the uid_min is 1000.
uname - 4.18.16-200.fc28.x86_64
Thanks

**Comment by SkewedZeppelin** [comment]
What version of firejail are you using and where did you install it from (git, sourceforge, copr)?

**Comment by millerthegorilla** [comment]
I'm using 0.9.56 from https://sourceforge.net/projects/firejail/files/firejail/firejail-0.9.56-1.x86_64.rpm/download
I used an admin user with no home directory to install (for sudo), then removed, and added my normal user to the wheel group and then reinstalled.  Same issue both times.

**Comment by millerthegorilla** [comment]
is there anyway that I can debug this?  Perhaps using a debug enabled version and gdb or similar?

**Comment by millerthegorilla** [comment]
upgraded to fedora 29, no change.

**Comment by smitsohu** [comment]
Do you have two different firejail installations? What does `which -a firejail` say? When you have firejail in /usr/local/bin, you would need to create/edit firejail.users in /usr/local/etc.

Also note that this file is not created by default any more, and firejail only cares when it exists.

**Comment by millerthegorilla** [comment]
Firejail is at /usr/local/bin/firejail.  The usernames are listed in /etc/firejail/firejail.users and also /usr/local/etc/firejail/firejail.users.  There are two users, one of whom has a home partition, and does not have superuser privileges, and a superuser who has no home partition, and who is a member of the wheel group.  They are both listed in the users file.

**Comment by millerthegorilla** [comment]
Could it be a permissions issue?  Is there a way of debugging or a resource anywhere that details how to go about debugging?  Many thanks for your help..

**Comment by smitsohu** [comment]
It shouldn't be a permission issue, but it makes sense to check! Just inspect (or paste here the output of) `ls -l /etc/firejail/firejail.users` and `ls -l /usr/local/etc/firejail/firejail.users`, these files must be world-readable.

Hard to tell what's going wrong. If you are not interested in the user database and just want firejail to work instantly, you can simply delete these files (firejail version 0.9.56 and later).

Otherwise, one thing you might want to try is renaming them (for later inspection) and manually create new files in their place. Regarding the format: a user name in the firejail.users file must match exactly the user name in /etc/passwd, including empty spaces or tabs if there are any, though I doubt this is the issue here... reading and understanding /etc/passwd is quite easy, there exists a man page for it: `man 5 passwd`.

**Comment by smitsohu** [comment]
> When I run a command, such as less, I get the above error but the command runs none-the-less.

Rereading your posts, this sounds interesting... but not sure I understand it right. Can you please run less on a dummy file and paste the output here? Thanks.

**Comment by millerthegorilla** [comment]
less bob
Error: the user is not allowed to use Firejail. Please add the user in /usr/local/etc/firejail/firejail.users file, either by running "sudo firecfg", or by editing the file directly.
See "man firejail-users" for more details.

**Comment by smitsohu** [comment]
Right, my bad, sorry. This is expected behavior, somehow I still had the old behavior in mind.

I'll see if we can add some diagnostic code in git.

**Comment by millerthegorilla** [comment]
Hi, actually, my bad.  Have now checked firejail.users files and they weren't world readable.  I have changed their permissions appropriately to 0644 and everything is fine again.
Thanks!

**Comment by smitsohu** [comment]
I think this should not happen, it is actually a bug.

**Comment by smitsohu** [comment]
@millerthegorilla Thanks for the report!
