### ISSUE TITLE
More complete documentation for -c option

### ISSUE THREAD

**Issue by crass** [netblue30/firejail#2252]
The documentation for the `-c` option for firejail should be more detailed.  Its not clear to me why I would use it.  The manpage says `Execute command and exit.`, which isn't helpful because that's what I would expect firejail to do by default.  Knowing a bit more about firejail, I might expect that it means the firejailed process is forked and the monitor process exits straight away, instead of waiting for the child process to terminate.  However, upon reviewing the code this doesn't seem to be accurate either.

As far as I can tell by looking at `arg_command` usage, the `-c` switch just turns off some extra/debug messages.  So what was/is the intent of this option?  If I've estimated it correctly, then it should be renamed and the documentation should be more accurate/descriptive.  Anyone have ideas about this?

**Comment by netblue30** [comment]
-c is a standard option for shells (bash, dash, etc), it is usually inserted on the command line by some of the login programs. You can use firejail as a restricted login shell (see man firejail-login) from a ssh or telnet server for example. There could be some other login applications,

I'll take a look at the code and clean some of it up. The code has been that way since forever.

**Comment by crass** [comment]
Ahh, ok, makes sense.  I don't have any issue with the code per se, just didn't see its purpose.  The documentation should include these details.
