### ISSUE TITLE
Does --appimage use the default profile under /firejail/etc?

### ISSUE THREAD

**Issue by oositP** [netblue30/firejail#2305]
How would you run KeepassXC if using the Appimage of KeepassXC ?

If you run it with `firejail --appimage --net=none KeepassXC`  will that still use the keepassxc.profile ?
Is the keepassxc.profile still needed if you use the above?

This would be good to know for other apps as well, unless you have already documented the differences between using the profile you have created and the --appimage switch (which i have not come across yet)

**Comment by oositP** [comment]
I made sure and didnt see any documentation explaining the differences with running apps in general and running them with --appimage.
Does running any app with a profile in /etc/firejail normally and using --appimage still use the default profile under /etc/firejail?? can anyone please answer this?

**Comment by crass** [comment]
First, you should be able to see if or what profile is being using by using the `--debug` option.  There isn't much difference in running appimage or not when it comes to profile selection and application.  In the case of `KeepassXC`, the profile `keepassxc.profile` will not be used because profile matching is case-sensitive, regardless of using `--appimage` or not.

On thing to watch out for is that appimages are many times suffixed with `.appimage` (eg. `Firefox.appimage`).  So running `firejail --appimage firefox.appimage` will not use the profile `firefox.profile` because firejail is looking for `firefox.appimage.profile`.  In most cases, you'll want to explicitly specify the profile you want to use for appimages (eg. `firejail --profile firefox firefox.appimage`)

**Comment by oositP** [comment]
Thanks @crass, thats exactly what i needed to know!
