### ISSUE TITLE
CVE-2019-5736

### ISSUE THREAD

**Issue by SkewedZeppelin** [netblue30/firejail#2401]
Is firejail vulnerable to this? It seems to be a common implementation issue when using privileged namespaces.

runc, docker, k8s, lxc, and flatpak have all had patches issued for it.

See
- https://seclists.org/oss-sec/2019/q1/119
- https://github.com/opencontainers/runc/commit/0a8e4117e7f715d5fbeef398405813ce8e88558b
- https://github.com/lxc/lxc/commit/6400238d08cdf1ca20d49bafb85f4e224348bf9d
- https://github.com/flatpak/flatpak/commit/cd2142888fc4c199723a0dfca1f15ea8788a5483

**Comment by smitsohu** [comment]
The [original blog post](https://brauner.github.io/2019/02/12/privileged-containers.html) has some additional details and **seems** to indicate that Firejail is not vulnerable, the key part being

> ...  the kernel will not allow modification of a running binary

Firejail has everything in one binary and in general outlives the sandboxed process. Only killing a master process with SIGKILL (`kill -9 firejail`) might potentially invalidate this assumption. But this is just a guess.

In any case `--noroot` is expected to defend against this.

**Comment by smitsohu** [comment]
After playing with publicly available exploit code, I can confirm there is a problem if following conditions are met:

1. The sandbox must be running exploit code.
2. The sandbox must be running as root.
3. The sandbox parent is killed instantly by an unhandled signal, i.e. something different from SIGTERM (`kill <pid>`) or SIGINT (ctrl+c). This cannot be done from inside the sandbox (because of the pid namespace), and also it cannot be done from the outside without root privileges. As only root him/herself is able to kill the sandbox in this way, this kind of attack is not relevant with regards to Firejail's SUID property.

Because this is a sandbox escape, the obligatory read-only mount and `private-bin` are no mitigations. I couldn't win the race for writing the payload, but it was possible to truncate the Firejail binary to length zero.

So for the time being, if your sandboxes are root and you need to hard kill a sandbox (`kill -9 <pid>`), preferably send the signal to the second firejail process rather than the first one (check `firejail --tree`).

@netblue30 ?

**Comment by glitsj16** [comment]
> So for the time being, if your sandboxes are root and you need to hard kill a sandbox (kill -9 <pid>), preferably send the signal to the second firejail process rather than the first one (check firejail --tree).

@smitsohu Is this what happens currently when using `firejail --shutdown=foo`? Or in other words, is the --shutdown=name/pid construct affected by this in any way? Just trying to understand the code, especially https://github.com/netblue30/firejail/blob/master/src/firejail/shutdown.c

**Comment by SkewedZeppelin** [comment]
@glitsj16 it sends a SIGTERM and if after 10 seconds it hasn't closed it sends a SIGKILL.
I am unsure which process it goes to.

**Comment by glitsj16** [comment]
@SkewedZeppelin I noticed the SIGTERM/SIGKILL routine, thanks for explaining. If I read [shutdown.c](https://github.com/netblue30/firejail/blob/master/src/firejail/shutdown.c) correctly, the SIGKILL goes to the child first. But I'm at best a beginner with C. And I was unsure too if that corrsponded with what smithsohu refers to as first/second firejail process. Currently I don't have any firejail sandbox running as root, so I shouldn't have to worry about this. Sorry for the noise here, it's reassuring to see CVE's are getting proper attention/discussion in firejail!

**Comment by smitsohu** [comment]
@glitsj16 yes, `--shutdown` kills the second firejail process/child first. Also `firejail --shutdown=sth` itself is another running instance of the firejail binary that outlives the sandbox that is being shut down, so I guess this should be safe.

**Comment by smitsohu** [comment]
> so I guess this should be safe.

And that was wrong, `--shutdown` also had this problem (now fixed in shutdown.c)

**Comment by glitsj16** [comment]
:+1:

**Comment by t4777sd** [comment]
> In any case --noroot is expected to defend against this.

For clarification, did profiles with noroot protect against this even if the parent process was killed before the child?

**Comment by smitsohu** [comment]
> For clarification, did profiles with noroot protect against this even if the parent process was killed before the child?

I would say yes, `noroot` defends in any case. The attacker being root is a necessary precondition, otherwise there is no write permission on the Firejail binary.

**Comment by reinerh** [comment]
This issue got CVE-2019-12499 assigned.

**Comment by reinerh** [comment]
@netblue30 Can you please update the CVE status page? https://firejail.wordpress.com/download-2/cve-status/

**Comment by netblue30** [comment]
LTS version also released, CVE status page updated - https://firejail.wordpress.com/download-2/cve-status/
