### ISSUE TITLE
Unknown or unsupported transport “DBUS_SESSION_BUS_ADDRESS=unix”

### ISSUE THREAD

**Issue by anteg** [netblue30/firejail#2407]
When running application like GIMP with firejail i get following message:
Unknown or unsupported transport “DBUS_SESSION_BUS_ADDRESS=unix” for address “DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus”

By checking similar issues I am wondering if this is something I want? =) Is it doing the job right by giving me this message or is this something I need to configure to get rid of? I dont really seem to understand if this message is good or not.

Thanks you for taking your time!

**Comment by Vincent43** [comment]
Gimp has [nodbus](https://github.com/netblue30/firejail/blob/master/etc/gimp.profile#L24) option enabled in profile which should block dbus access and perhaps that's why you see those message.

If you don't see anything broken in app then you may ignore this. If you want to disable it then you may try `firejail --ignore=nodbus gimp` or `echo ignore nodbus > /etc/firejail/gimp.local` as `root` to make it permanent.

**Comment by anteg** [comment]
Big thanks!

**Comment by anteg** [comment]
I know I closed this but I have after some more research anmd according to a hidepid warning on the arch wiki: https://wiki.archlinux.org/index.php/security#hidepid 
And I am using hidepid and that could cause problems with D-Bus. Anyone know if I can like add permissions for firejail to check and thru that get rid of the warning without adding the 'ignore' command?

**Comment by chiraag-nataraj** [comment]
I use `hidepid` with DBus stuff just fine, but I added a `proc` group and added `polkitd` and `systemd-logind` to it. Then again, I pretty much don't _really_ use DBus, so...:man_shrugging:

Anyway, the original question seems to have been answered, so I'm going to go ahead and close this. @anteg, please feel free to re-open if you have more questions.
