### ISSUE TITLE
Typo in firefox-common.profile and chromium-common.profile ?

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#2417]
I just noticed that both profiles contain the line:

`?BROWSER_DISABLE_U2F: nou2f`

I suspect that this is an error as I haven't seen this documented anywhere.

**Comment by glitsj16** [comment]
Not a typo. This is documented in man [firejail-profile](https://github.com/netblue30/firejail/blob/c083a7b737050c532977b46fac6400f1dbc24ff6/src/man/firejail-profile.txt) and code is [here](https://github.com/netblue30/firejail/blob/0d2f252230283ffcd97795b65e5f29ceaf9bf824/src/firejail/profile.c) #L154+.

**Comment by curiosity-seeker** [comment]
Oops - you're right! Sorry!

**Comment by glitsj16** [comment]
No problem. I tended to forget firejail has more than one man page too ;)

**Comment by curiosity-seeker** [comment]
Indeed ;-)

I understand the "?HAS_APPIMAGE: whitelist ${HOME}/special/appimage/dir" example in man firejail-profile. But I must admit that I'm having trouble to understand the purpose of "?BROWSER_DISABLE_U2F: nou2f"  ....

**Comment by SkewedZeppelin** [comment]
> But I must admit that I'm having trouble to understand the purpose of 

u2f devices were disabled for all of the profiles
u2f devices are an important tool and should be as easy as possible to get working

so instead of users having to create local profile files for their browser, I added a config option so they can just edit /etc/firejail/firejail.config to get them working
