### ISSUE TITLE
Running firejail in Docker

### ISSUE THREAD

**Issue by mwz** [netblue30/firejail#2579]
Hi, I'm trying to run firejail in a Docker container, however I'm not having any luck.

I'm using the following:
- base docker image openjdk:8 (Debian Stretch)
- firejail 0.9.44.8-2 (the latest version available)

Running firejail in the following way
```bash
firejail --force --noprofile echo hello
```
results in this error message:
> Error clone: main.c:2519 main: Operation not permitted

I've seen in the release notes that the `--force` flag was removed in 0.9.54 - is it possible to run firejail in Docker? If so, what is the recommended way of doing that?

**Comment by Fred-Barclay** [comment]
Hi @mwz 
As far as I know it's no longer possible to run firejail inside Docker because they both need/use similar features. Sorry -- I know it's not the news you wanted to hear -- maybe someone can correct me if this is actually possible??
https://github.com/netblue30/firejail/issues/1956#issuecomment-391660354

**Comment by KOLANICH** [comment]
I [have run FJ in docker in CI environment](https://gitlab.com/KOLANICH/GraalVM_deb_packages_CI/-/jobs/191684147), IMHO works fine.

**Comment by matu3ba** [comment]
@KOLANICH Please refer your firejail version, if you claim otherwise.
This should be closed due to technical reasons otherwise as explained in #1956.

**Comment by Fred-Barclay** [comment]
Let's close now and reopen later if needed. Thanks everyone! :smile:
