### ISSUE TITLE
Compare to nsjail

### ISSUE THREAD

**Issue by KOLANICH** [netblue30/firejail#2589]
https://github.com/google/nsjail

**Comment by veloute** [comment]
at first glance, they're quite similar in the goals they're trying to accomplish.
a big difference i first noticed is that the profiles in nsjail are nowhere near as easy to read and understand as firejail's.

**Comment by smitsohu** [comment]
I don't know if nsjail was written to run safely as suid root. So just in case this is your plan, I might be a good idea to first ask over there at nsjail. Google was a heavy user of Ubuntu in the past, and since Ubuntu supported unprivileged user namespaces from the beginning, I wouldn't be surprised if nsjail, as an inhouse tool, was written primarily with unprivileged user namespaces in mind.

Other than that, nsjail and Firejail and all these tools try to be convenient interfaces to the same technologies in the kernel. It's not surprising there is a degree of similarity.

**Comment by chiraag-nataraj** [comment]
Going to close since it looks like the OP's question was answered. @KOLANICH, please feel free to re-open if you have more questions.
