### ISSUE TITLE
Evince crashes when 2-page side-by-side is chosen

### ISSUE THREAD

**Issue by pianoslum** [netblue30/firejail#2621]
Arch Linux x64
firejail 0.9.58.2
evince 3.32.0

STR:
* Open any pdf with firejailed evince
* Choose two-sided option from menu
* App crashes

Works as intended with `--no-profile`

**Comment by SkewedZeppelin** [comment]
Can you try using the latest profile from here
https://github.com/netblue30/firejail/blob/master/etc/evince.profile
there were some fixes recently

**Comment by pianoslum** [comment]
I tried and unfortunately, the problem persists.

**Comment by glitsj16** [comment]
What happens when you run without nodbus? It might help to see evince output too (if any) when it crashes. Please post output of:
`$ firejail --ignore=quiet --ignore=nodbus /usr/bin/evince`

**Comment by rusty-snake** [comment]
Just as an note:
```
$ /bin/evince --version
GNOME-Dokumentenbetrachter 3.30.2
$ firejail --version 
firejail version 0.9.57
$ cat /etc/os-release 
NAME=Fedora
VERSION="29 (Twenty Nine)"
```
with [this strict profile](https://gist.github.com/rusty-snake/5f2eebfdcf5c23c9e88791c647682da6) it works.

**Comment by pianoslum** [comment]
Yes `--ignore=nodbus` does the trick. But it does not seem to be a problem for everybody.
I have NVidia drivers (proprietary), maybe that's the reason?

**Comment by glitsj16** [comment]
@pianoslum I can't explain why using NVidia's drivers would need D-Bus for Evince to work properly, but I've seen it before. You can add `ignore nodbus` to a evince.local override file if you haven't already. And receive bonus points for making Evince's settings stick, which (at least for me) is also something nodbus messes with. If you feel your issue is solved, you can close this (and reopen whenever things change). All the best!

**Comment by pianoslum** [comment]
Thank you very much @glitsj16 !
