### ISSUE TITLE
Using systemd-resolved causes DNS to not work

### ISSUE THREAD

**Issue by kalegrill** [netblue30/firejail#266]
I haven't debugged this too much, but I noticed if /etc/nsswitch.conf is set with "resolve" instead of "dns" as per [nss-resolve(8)](http://www.freedesktop.org/software/systemd/man/nss-resolve.html), then in firejail an inaccessible file is attempted to be read (/sys/fs/kdbus/0-system/bus gets an EACCES) and names are not resolved. This is regardless of if systemd-resolved is active, it only needs to be configured in /etc/nsswitch.conf.

**Comment by kalegrill** [comment]
Some tests:
Curl run outside firejail, resolved active or inactive, nsswitch with or without "dns" after "resolve": DNS works.
Curl run inside firejail, resolved active or inactive, nsswitch without "dns": DNS doesn't work.
Curl run inside firejail, resolved active or inactive, nsswitch with "dns" after "resolve": DNS works.

I haven't looked into how exactly this works, but evidently outside of firejail nss-resolve failsover correctly even without the "dns" entry in nsswitch; however, inside firejail it does not failover without "dns" included.

The example in the nss-resolve(8) lacks the "dns" option yet claims that "nss-resolve will chain-load nss-dns if systemd-resolved.service is not running". From my brief look that seems to be the case when the return for /sys/fs/kdbus/0-system/bus is ENOENT but not when it is EACCES. This doesn't look like a firejail issue to me?

The easy fix if one wants to use systemd-resolved is to put dns after resolve on the hosts line in nsswitch.conf. I should have been doing that in the first place.

**Comment by netblue30** [comment]
Thanks for the hint. I'll do a test here and I'll have something in the next release.

**Comment by netblue30** [comment]
Try version 0.9.40, it has lots of fixes. If you  still see the problem, let me know and I'll reopen the bug.

**Comment by aineko** [comment]
I am observing the same issue on version 0.9.48 when trying to access zeroconf-discovered hosts.

If I compare
  $ strace /usr/bin/ping some_intranet_host
and
  $ /usr/bin/firejail --noprofile --allow-debuggers strace /usr/bin/ping some_intranet_host
I can clearly see that nss-resolve abandons resolution when it gets EACCES instead of ENOENT for /sys/fs/kdbus/0-system/bus

Unblacklisting /sys/fs makes the nss-resolve get ENOENT for /sys/fs/kdbus/0-system/bus and then continue by opening /var/run/dbus/system_bus_socket which succeeds:
  $ /usr/bin/firejail --noprofile --noblacklist=/sys/fs /usr/bin/ping some_intranet_host

Still looks like the proper way to fix this is on nss-resolve side.
