### ISSUE TITLE
Allow Spaces in Directory Paths

### ISSUE THREAD

**Issue by ilikenwf** [netblue30/firejail#271]
I have already tried escaping \, as well as encapsulating with both single and double quotes, but due to the fact that Pale Moon's developer thought using "~/.moonchild productions" was ok for the browser's directory, firejail doesn't play nice with it.

Currently I'm using a copy of my firefox.profile for palemoon, modified with ~/.palemoon as the directory, with a custom built version of Pale Moon configured to use ~/.palemoon instead (this isn't JUST because of firejail, I like building this myself)...

Because we like standardization, it would be nice if you could either add space functionality for paths, or educate me if there is one already so we can have a default profile for pale moon as well - it is gaining in popularity as Firefox bloats and adds privacy intrusive features.

**Comment by dshmgh** [comment]
Just put the path in verbatim with the spaces and no type of quoting.  The path parsing is not standard unix shell.  This fooled me too until I accidentally tried without any quoting.  Perhaps the profile man page needs a mention?

**Comment by ilikenwf** [comment]
Ah, that makes sense. It would be extremely helpful if someone would add an example to the manpages.

**Comment by netblue30** [comment]
I'll try to bring in a Pale Moon profile.

**Comment by netblue30** [comment]
Added it to my list of things to do/

**Comment by cipitaua** [comment]
I defined the variable:
```
FIREJAIL="firejail --noprofile --nonewprivs --seccomp --noroot --read-only=$HOME --read-write=$BASEDIR --read-write=$HOME/.cache --net=none"
```
and then I wish to run
```
$FIREJAIL mycommand
```
but if BASEDIR contains spaces I get the `Error: no suitable executable found`

Is there any way to define the variable FIREJAIL so that a `$FIREJAIL mycommand` would work regardless the speces in the path?

I know there are other ways, e.g. with arrays or functions, but the `$FIREJAIL mycommand` is already in a lot of scripts I use, I would like not to change it.

**Comment by kmk3** [comment]
> I defined the variable:
> 
> ```
> FIREJAIL="firejail --noprofile --nonewprivs --seccomp --noroot --read-only=$HOME --read-write=$BASEDIR --read-write=$HOME/.cache --net=none"
> ```
> 
> and then I wish to run
> 
> ```
> $FIREJAIL mycommand
> ```
> 
> but if BASEDIR contains spaces I get the `Error: no suitable executable
> found`
> 
> Is there any way to define the variable FIREJAIL so that a `$FIREJAIL
> mycommand` would work regardless the speces in the path?
> 
> I know there are other ways, e.g. with arrays or functions, but the
> `$FIREJAIL mycommand` is already in a lot of scripts I use, I would like not
> to change it.

The issue seems to be due to shell variable expansion, not firejail.

The obvious solution would be to use a function.

Alternatively, you could put this command in a shell script (such as
`~/bin/myfirejail`) and set `FIREJAIL` to it (such as
`FIREJAIL=~/bin/myfirejail`):

```sh
#!/bin/sh

firejail --noprofile --nonewprivs --seccomp --noroot \
  --read-only="$HOME" \
  --read-write="$BASEDIR" \
  --read-write="$HOME/.cache" \
  --net=none \
  "$@"
```

Then the lines using `$FIREJAIL` probably wouldn't need to be changed.
