### ISSUE TITLE
Switch from Wordpress site to Github Pages

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#2713]
I've seen several requests on here (at the end of issues, for example) to update things on the website. It might be easier to manage if we move from the current Wordpress site to a Github page, since other people can also help maintain it.

Just a thought.

**Comment by smitsohu** [comment]
There is also #2090

**Comment by chiraag-nataraj** [comment]
Yup. But I presume moving our official documentation is slightly different from the website (which provides common usage, etc), so while it's related, I'd regard it as a separate goal.

**Comment by chiraag-nataraj** [comment]
@netblue30, thoughts?

**Comment by chiraag-nataraj** [comment]
Let's move the discussion over to #2729.

**Comment by tredondo** [comment]
> Let's move the discussion over to #2729.

I wasn't around when this decision was made, but it seems the migration to Wordpress is pretty involved, mainly due to the comments, so IMO it would make sense to keep it separate from the meta ticket (#2729).

So regarding the [comments migration](https://github.com/netblue30/firejail/issues/2729#issuecomment-739971836) issue raised by @SkewedZeppelin, we now have GitHub discussions, which can host unanswered comments from Wordpress. For resolved Q&As, I think the best palce would be [the Wiki FAQ](https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions), so I took the liberty to create [some examples](https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions/_history).

I went through all the Wordpress pages, and here are the ones with comment, as well as the date of the most recent comment:
* https://firejail.wordpress.com/download-2/ - May 2020
* https://firejail.wordpress.com/download-2/release-notes/ - August 2020
* https://firejail.wordpress.com/features-3/ - I've added the only relevant Q to the Wiki FAQ
* https://firejail.wordpress.com/features-3/man-firejail/ - August 2020
* https://firejail.wordpress.com/documentation-2/ - created a discussion for the only relevant comment

**Comment by SkewedZeppelin** [comment]
@tredondo

> Perhaps replace the comments feature with a note at the bottom pointing users to the GitHub Discussions?

GitHub (Discussions) requires an account. A comment on the WordPress doesn't.

One of the nice things about GitLab is its 'service desk' feature where anyone can email in and an issue is created.

More wholesome things like traditionally SourceForge or SourceHut is their built-in mailing list.

@rusty-snake put a lot of effort in remaking the site, it is not an easy task at all.
It is sad to see it rot.
