### ISSUE TITLE
Wiki: Home

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#2749]
Issue for discussing non-ToC-related changes to the home page (table of contents updates are trivial).

**Comment by chiraag-nataraj** [comment]
Anything else we want to add to the homepage? I feel like it's fairly complete at this point heh.

**Comment by matu3ba** [comment]
@chiraag-nataraj Proposal to close this.

**Comment by tredondo** [comment]
How do I create a pull request for a wiki page? https://github.com/netblue30/firejail/wiki#editing-an-existing-page says to create one, but I only see an Edit button to edit pages directly.

**Comment by rusty-snake** [comment]
You can not create a PR for a GitHub Wiki ¹. The description is wrong and should be updated. For minor changes like typos just edit the page. For major changes it's better to discuss them in a issue first.

¹ since a GitHub Wiki is at the end a git-repo with markdown/wiki-systax/reStructuredText/... files, it's possible to have a github.com/netblue30/firejail-wiki repo which is synced to the wiki. This repo would support PRs.

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/discussions/4441
