### ISSUE TITLE
[Firefox] Video playback not starting 

### ISSUE THREAD

**Issue by hillbicks** [netblue30/firejail#279]
Hey guys,

I think the latest update broke the video playback, at least on my side. The video (html,webm....) is loading, but the playback simply does not start. Starting firefox without firejail works without problems, so I guess the problems has to be somewhere in firejail, maybe in my config?

Firefox: 44.0
firejail: latest version from git.

Firefox.profile
```
# Firejail profile for Mozilla Firefox (Iceweasel in Debian)
noblacklist ${HOME}/.mozilla
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
caps.drop all
seccomp
protocol unix,inet,inet6,netlink
netfilter
tracelog
noroot
whitelist ${DOWNLOADS}
whitelist ~/.mozilla
whitelist ~/.cache/mozilla/firefox
whitelist ~/dwhelper
whitelist ~/.zotero
whitelist ~/.lastpass
whitelist ~/.vimperatorrc
whitelist ~/.vimperator
whitelist ~/.pentadactylrc
whitelist ~/.pentadactyl
whitelist ~/.keysnail.js
whitelist ~/.config/gnome-mplayer
whitelist ~/.cache/gnome-mplayer/plugin
include /etc/firejail/whitelist-common.inc

# experimental features
#private-etc passwd,group,hostname,hosts,localtime,nsswitch.conf,resolv.conf,gtk-2.0,pango,fonts,iceweasel,firefox,adobe,mime.types,mailcap,asound.conf,pulse
```

**Comment by netblue30** [comment]
I'll look into it, thanks!

**Comment by chiraag-nataraj** [comment]
Video playback works just fine for me with this as my profile file.
````
include /etc/firejail/firefox.profile
whitelist /home/chiraag/.mozilla
whitelist /home/chiraag/Downloads/
whitelist /home/chiraag/.pulse/
whitelist /home/chiraag/.config/pulse/
whitelist /home/chiraag/.config/gtk-3.0/
whitelist /home/chiraag/.config/google-googletalkplugin/
whitelist /home/chiraag/.gtkrc-2.0
whitelist /home/chiraag/.gtkrc.mine
whitelist /home/chiraag/.Xauthority
private-etc hosts,passwd,mime.types,fonts/,mailcap,iceweasel/,xdg/,gtk-3.0/,resolv.conf,X11/,pulse/,asound.conf,adobe/,gcrypt/,alternatives/
shell none
seccomp
````
where `/etc/firejail/firefox.profile` is the default that is shipped.

The two main areas I see a difference are with your whitelist (I don't include whitelist-common) and that you enable an additional protocol (netlink). Neither of these should be affecting your video playback, however. Ah...maybe the problem is that you're not whitelisting ~/.pulse? If you're using PulseAudio, you have to do that (I've had issues with video playback if the audio subsystem isn't working).
