### ISSUE TITLE
Warning - networking feature is disabled in Firejail configuration file @ Opera

### ISSUE THREAD

**Issue by cokeflash** [netblue30/firejail#2888]
Hi!

When I run opera with firejail command in terminal, terminal shows me:

Warning: networking feature is disabled in Firejail configuration file

Internet is working in Opera Browser.

How can I fix that?

**Comment by cokeflash** [comment]
# firejail --dns=127.0.0.1 opera

Warning: networking feature is disabled in Firejail configuration file

**Comment by Vincent43** [comment]
This may be caused by `restricted-network yes` in [/etc/firejail/firejail.config](https://github.com/netblue30/firejail/blob/b9fe3cca6a0921d35d919f234e3f9faf7910ce3f/etc/firejail.config#L96). I think it doesn't affect `--dns` option so you may ignore it. If for some reason you want to get rid of that message, please set `restricted-network yes` in above config file.

**Comment by cokeflash** [comment]
I set
restricted-network no

and the error is gone in terminal (output)

Can I leave it to 'no' or better to yes?

My internet is working with both: 'yes+no'

**Comment by rusty-snake** [comment]
firejail.config:
```
# Enable or disable restricted network support, default disabled. If enabled,
# networking features should also be enabled (network yes).
# Restricted networking grants access to --interface, --net=ethXXX and
# --netfilter only to root user. Regular users are only allowed --net=none.
```

`restricted-network = yes` means that a normal use can't use `--interface`, `--eth` (except of `--net=none`) and `--netfilter`. If you need no one of this, you can set it to yes without issues (and harden your system a little bit more).

**Comment by cokeflash** [comment]
I set it back to 'yes'...

Thanks for the help. :-)

**Comment by cokeflash** [comment]
(SOLVED)
