### ISSUE TITLE
[ssh profiles] Cannot perform git operation via SSH

### ISSUE THREAD

**Issue by exah-io** [netblue30/firejail#2910]
Hi there,
I've run into any issue with the ssh profile and git operations.

**Setup:**
Arch Linux
+
AppArmor
+
default profiles
+
firejail version 0.9.60
Compile time support:
	- AppArmor support is enabled
	- AppImage support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled`

**Steps to reproduce:**
- perform a git operation, such as clone, via SSH. eg. `git clone git@github.com:netblue30/firejail.git`

**Result:**
- The ssh process will hang at password input

After removing ssh and ssh-agent profiles, as well as ssh symlink in /usr/local/bin, the operation proceeded as expected.

Thanks!

**Comment by rusty-snake** [comment]
I doesn't have this issue, have you firejailed git?

**Comment by exah-io** [comment]
Started over from a fresh install and couldn't reproduce the issue.
Must have had something else conflicting. Sorry for the false positive. Thanks

**Comment by alexpyattaev** [comment]
Same issue here. I believe it has to do with kde SSH askpass GUI or similar, but either way allowing SSH to go through firejail breaks git. 
The fix for me seems to be commenting these out:
#dbus-user none
#dbus-system none

**Comment by SkewedZeppelin** [comment]
@alexpyattaev what distro are you on?
Fedora recently pushed a fix for broken connections to Debian servers.
https://src.fedoraproject.org/rpms/openssh/c/6a0769945432900cc01b395e5ba52cba33a2edee?branch=f33

**Comment by alexpyattaev** [comment]
Hi, I am on archlinux. firejail version 0.9.64.

**Comment by CvBeijsterveldt** [comment]
I'm experiencing the same issue on two different Arch Linux installations, both with KDE, since Firejail 0.9.64 (I didn't have the issue before). I'm using KeepassXC to add the SSH keys to the agent. This gives the following error whenever I try to do something with Git that requires repository access:

```
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

When I delete 'ssh' symlink from `/usr/local/bin/` the issue is 'solved'. After just removing the KeepassXC profile the problem still persists. The fix that works for @alexpyattaev does not seem to work for me (when done to the SSH profile). Also, interestingly, this problem does not occur on a Pinebook Pro running Manjaro Linux with the same setup (i.e. also using the same KeepassXC database and SSH-agent configuration).

Please let me know if I can do anything to provide more info.

**Comment by CvBeijsterveldt** [comment]
Disregard the above, this apparently has to do with the runuser (which KeepassXC is known not to work nicely with), disabling the following lines
```
whitelist ${RUNUSER}/keyring/ssh
whitelist ${RUNUSER}/gnupg/S.gpg-agent.ssh
include whitelist-runuser-common.inc
```
solves the issue.

**Comment by rusty-snake** [comment]
What does `echo $SSH_AUTH_SOCK` show?
