### ISSUE TITLE
Firefox and Chromium bugs 

### ISSUE THREAD

**Issue by meliaas** [netblue30/firejail#2924]
Hi. Default Firejail profiles for firefox and chromium have two issues.

Firefox doesn't open any page at all, I tried this in 2 different computers on Linux Mint, and I tried on another computer with Manjaro as well. None of them worked, but firefox works just as fine without firejail.

Chromium keeps asking for keyring authentication when it's opened, it happens in both Linux Mint installs but in Manjaro it was ok.

Brave on Manjaro has a sandbox issue, and in Linux Mint I can't install the default profile...

**Comment by rusty-snake** [comment]
chromium: 867c2bc

What version of firefox and firejail?

**Comment by meliaas** [comment]
firejail 0.9.52-2
firefox 68.0.2

now I can't even edit the profiles with gedit or leafpad... :\ don't know what's wrong but I'll try to fix it, unless anyone tells me any better text editor... but these worked before

**Comment by rusty-snake** [comment]
> unless anyone tells me any better text editor

vim  (_if you ask so general I can't resist_)

if you edit the files in /etc you need to be root (`sudo vim /etc/firejail/firefox.profile`, `gedit admin:///etc/firejail/firefox.profile`). Alternative you copy to `.config/firejail` (`mkdir -p ${HOME}/.config/firejail && cp /etc/firejail/firefox.profile $HOME/.config/firejail`)

> firejail 0.9.52-2

Since 0.9.52 there has been a huge of changes to firefox in firejail.
The biges important: https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions#firefox-60-problems
0.9.52 Is very old, can you updating?

**Comment by meliaas** [comment]
Hi! Thanks for the help, I can edit the files with gedit using that command. Usually opening /etc/firejail as root would suffice... But then, I don't see any nodbus command on chromium.profile. Adding that line breaks chromium completely.

Maybe the issue is using that old version of firejail, I installed it via the official Linux Mint software sources! How can I update it?

**Comment by rusty-snake** [comment]
Has Mint firejail? http://packages.linuxmint.com/search.php?release=any&section=any&keyword=firejail show nothing to me, but for examlple if I search for firefox I get results.

Because I don't know your Mint version (maybe upgrading is enought) and I can't find any informations about firejail in Mint (maybe using backports is enought) here is the command that definitely work.

```bash
sudo apt remove --autoremove --purge firejail # remove old firejail
wget "https://downloads.sourceforge.net/project/firejail/firejail/firejail_0.9.60_1_amd64.deb" # download firejail
# In the future you can find newer version here: https://sourceforge.net/projects/firejail/files/firejail/
sudo dpkg -i firejail_0.9.60_1_amd64.deb # install new firejail
```

_apt and dpkg may causing some side-effects, think while executing_

**Comment by meliaas** [comment]
Yeah Mint has firejail in Software Center. Doing your procedure fixed everything in the 3 browsers! Thank you very much. Cheers
