### ISSUE TITLE
Steam issue with internal browser

### ISSUE THREAD

**Issue by Hnaguski** [netblue30/firejail#3049]
I am running firejail 0.9.60 on Debian and am having a similar issue to what was described in https://github.com/netblue30/firejail/issues/1396 where the internal browser is just black.
![2019-11-20-234705_1920x1080_scrot](https://user-images.githubusercontent.com/29007712/69353247-34bbeb80-0c4c-11ea-9067-7de2713eb230.png)

 I am running the program with `firejail --private=~/.local/share/steam steam`, would this cause issues? I have checked the steam.profile and it does have tracelog commented out but the issue persists. I have found that commenting out `include disable-common.inc` in steam.profile does seem to fix it, but I am unsure if this is a good idea to leave disabled.

**Comment by rusty-snake** [comment]
> but I am unsure if this is a good idea to leave disabled.

In general removing `disable-common.inc` is a bad idea, since it protects files like .bashrc. That can end in sandbox-escape. Using `--private` is a mitigation against this, since the .bashrc read outside of the sandbox is an other .bashrc.

Sine `disable-common.inc` contains a lot of `read-only` and `blacklist` command, only one (or a bit more) `read-write`/`noblacklist`/`ignore` lines in steam.local would be needed to fix that. Can you find out which ro/bl line is the issue? (comment fist all ro (search and replace) and then all bl; or comment first the half file, and the the other half.) If steam starts with `tracelog`, you can also look in the syslog.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.
