### ISSUE TITLE
make mkdir  recursive

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#305]
This is a question-like issue currently, but I think a change is needed to avoid confusion:

Why isn't `mkdir` invoked by default when doing `whitelist`?
The possible pitfall I see with the current approach is that people might get confused:

* somebody takes his system, tests his new-created profile. Since directories exist on his computer, everything goes fine
* he submits the profile so it would be available for everyone
* people start to complain because this will not work on their fresh computers.

Thoughts?

**Comment by manevich** [comment]
Doing mkdir for everything whitelisted is wrong idea, there are many cases when whitlisted file/directory is used when available but not created by app.
Since new `mkdir` option implemented (see https://github.com/netblue30/firejail/commit/97a9d0186863f6afe1a003e7e390b1b369167531 and https://github.com/netblue30/firejail/commit/3a71eb2af9a2153c9d40d0e2f31093d8e7c87b01 commits) this is just about insufficient testing of profile.
You can use `--private` option in conjunction with your fresh profile to rule out such things, as in most cases it's about `$HOME/.something` directories.

**Comment by netblue30** [comment]
We build only the directories strictly necessary for the application. For example, for Firefox we have ~/.mozilla and ~/.cache/mozilla/firefox. All other directories are only necessary to run some extensions, and we will let the user build them. We also have an "include /etc/firejail/whitelist-common.inc". This file deals with system configuration such as fonts, gtk etc.

**Comment by vn971** [comment]
OK to close. One small question if you don't mind though:
how do you think, would it make sense to make `mkdir` recursive?

**Comment by netblue30** [comment]
Yes, I'll look into it.

**Comment by vn971** [comment]
Thanks!
