### ISSUE TITLE
--audit and shell=none

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3116]
Run `firejail --profile=any-profile-that-has-shell_none --audit` will end with
`Error: shell=none configured, but no program specified`. But it is not necessary to so specify a program if the profile is given with `--profile` and the program is never started because of `--audit`.

**Comment by glitsj16** [comment]
> But it is not necessary to so specify a program if the profile is given with --profile

I never interpreted the `--profile` option to imply a program name, it just loads a specific profile. In other words I'd consider that specific command to always be a no-op because it lacks a command (an application) the user wants to have audited. Do you regard this as a bug? I do agree that the specific error message could be more informative.

**Comment by rusty-snake** [comment]
`--audit` audits the profile. => If firejail knows the profile (by adding a program name or using --profile) it can audit the profile.

bug? yes.

**Comment by netblue30** [comment]
Fix is in, you can try it out.
