### ISSUE TITLE
How to make applications have access to a virtual filepath (like flatpak does)

### ISSUE THREAD

**Issue by Joe23232** [netblue30/firejail#3201]
So with flatpak if you download something like Steam, Steam has access to and virtual file paths, therefore games get installed in the virtual filepath, but with the download directory, it has access to the real download directory.

How would I do this with firejail?

**Comment by smitsohu** [comment]
I'm not really familiar with Steam, but you might want to take a look at the `--private=` option.

In a profile it could look like
```
mkdir ${HOME}/fakehome
private ${HOME}/fakehome
```
In this case the app would always see ~/fakehome instead of the real home directory.

**Comment by Joe23232** [comment]
@smitsohu So this creates a `fakehome` directory and what does `private ${HOME}/fakehome` this do exactly?

Can the application still see the root directory and external drives's contents that are connected to my PC?

**Comment by smitsohu** [comment]
> So this creates a fakehome directory and what does private ${HOME}/fakehome this do exactly?

It makes the app see ~/fakehome instead of the real home directory.
Just try it out :)

> Can the application still see the root directory and external drives's contents that are connected to my PC?

The `--private=` option is not sufficient to create a complete sandbox, obviously.

But it is my superficial understanding that all games and settings are stored in the user home directory. For everything else there are other precautions and other options (default read-only filesystem, blacklisting, `disable-mnt`, ...), and you can also use more of the private options (`private-bin`, `private-etc`, ...) to "virtualize" other parts of the file system.

**Comment by Joe23232** [comment]
Probably I want to virtualise everything but the downloads directory. So if the home directory is virtualised, is it possible to still allow the application to ONLY have access to the real Downloads' directory?

**Comment by smitsohu** [comment]
Ok, it is possible to get rather close to that end with the `--overlay` and `--chroot` options. For example, it could look like:

`firejail --private-tmp --private-dev --overlay-named=somename`

Unfortunately there is currently a bug in the overlay implementation (kernels > 4.19). So if a complete chroot is in scope, the answer is probably yes. Otherwise the answer is probably no.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you have more questions.
