### ISSUE TITLE
Cannot open downloaded file in external program from Firefox

### ISSUE THREAD

**Issue by ericschdt** [netblue30/firejail#3205]
When I download a PDF for example and try to open it from the download list in Firefox (Ctrl+Shit+Y), it says that the link has to be opened by an app and that's it. It won't open Okular for example.

I already added 
```
private-bin okular
```
to `firefox.profile`, so at least I already see a PDF icon in the download list.

##### System

FF 72.0.2
firejail 0.9.62
Archlinux

**Comment by glitsj16** [comment]
> When I download a PDF for example and try to open it from the download list in Firefox (Ctrl+Shit+Y), it says that the link has to be opened by an app and that's it.

If you have configured Firefox to use a specific application to read PDF files instead of using the built-in PDF viewer this is expected behavior. Adding 'private-bin okular' to firefox.profile is not enough to get the functionality you're after IMHO. In fact, I'm quite surprised that Firefox is even starting at all by doing so. The private-bin option isn't used in any of our default firefox-related profiles. Hence adding it would limit the set of acessable binaries to just 'okular'.

We have this in /etc/firejail/firefox-common.profile:

```
# Uncomment the following line (or put it in your firefox-common.local) to allow access to common programs/addons/plugins.
#include firefox-common-addons.inc
```

Do you have a ~/.config/firejail/firefox-common.local file referencing 'include firefox-common-addons.inc'?

**Comment by ericschdt** [comment]
> In fact, I'm quite surprised that Firefox is even starting at all by doing so

This is the full line I had in firefox.profile

```
private-bin bash,dbus-launch,dbus-send,env,firefox,sh,which,plasma-browser-integration-host,okular
```


> Do you have a ~/.config/firejail/firefox-common.local file referencing 'include firefox-common-addons.inc'?

Nope, not yet, but I am going to test it with the firefox-common-addons.inc :)

**Comment by glitsj16** [comment]
> This is the full line I had in firefox.profile
> private-bin bash,dbus-launch,dbus-send,env,firefox,sh,which,plasma-browser-integration-host,okular

That makes more sense :+1:.

I think you can solve this by including firefox-common-addons.inc. Feel free to close at your discretion. Good luck.

**Comment by ericschdt** [comment]
> I think you can solve this by including firefox-common-addons.inc. Feel free to close at your discretion.

I tried it but with no luck. What I can do though is to click on the button to manually pick the app to open a PDF, where I can navigate to /usr/local/bin/okular, but that's not the way it should work.

**Comment by matu3ba** [comment]
@ericschdt Changing the default behavior what firefox does is not possible?
@rusty-snake label Q:FAQ "how do I run application X from application Y"

**Comment by ericschdt** [comment]
I could solve it adding `okular` to private-bin, but FireFox kept asking me which program I wanted to use to open a PDF, though luckily okular was already in the list -- just its icon was missing.

Nonetheless, for the moment I disabled FireJail as it's way too time consuming for me to configure it correctly and to adjust all kind of profiles in the moment.
