### ISSUE TITLE
--private creates empty dirs on $HOME

### ISSUE THREAD

**Issue by aleprovencio** [netblue30/firejail#3217]
Hello,
even though running something like `firejail --private=/home/aleprovencio/sandbox/ electrum` will correctly use the private directory, it also creates an empty `/home/aleprovencio/.electrum` which will remain after the application closes.

Is this normal behavior? Is there a way to prevent it?

**Comment by glitsj16** [comment]
> Is this normal behavior?

It is 'normal' behavior yes, because of the [mkdir ${HOME}/.electrum](https://github.com/netblue30/firejail/blob/master/etc/electrum.profile#L23) in the default profile.

> Is there a way to prevent it?

You could try adding `ignore mkdir ${HOME}/.electrum` in a ~/.config/firejail/electrum.local file. Alternatively you could copy electrum.profile from /etc/firejail into ~/.config/firejail/electrum.profile and comment that line out. Just remember that future firejail updates might bring changes to the defaults and 'break' your workaround.

**Comment by aleprovencio** [comment]
That's awesome, thank you

**Comment by rusty-snake** [comment]
#903
