### ISSUE TITLE
Steam can't connect to the internet

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [netblue30/firejail#3376]
"firejail steam" gives me a popup saying I'm not connected to the internet.

I will not post the whole log but I think the key difference when using firejail is this line:

`opensslconnection.cpp (1519) : Assertion Failed: unable to load trusted SSL root certificates`

Second unrelated issue I need to solve is this line:
```
Could not create Vulkan instance : 
ERROR_EXTENSION_NOT_PRESENT
```

**Comment by rusty-snake** [comment]
Distro? firejail version? nVidia or AMD GPU? Any custom changes?

**Comment by GreatBigWhiteWorld** [comment]
opensuse leap 15.1 
version 0.9.62 from opensuse
nvidia latest version from opensuse
no custom change.

**Comment by glitsj16** [comment]
> opensslconnection.cpp (1519) : Assertion Failed: unable to load trusted SSL root certificates

The steam profile references both `ca-certificates` and `ssl` in `private-etc` (amongst others) because on most distros /etc/ssl/certs contains symlinks to pem files in /etc/ca-certificates/extracted. That should be enough to load the SSL root certs. Does opensuse have a different way of organizing these files? If so you might need additional entrees in private-etc. Easily tested by temporarily commenting private-etc and checking if that changes anything. On a side-note I noticed the private-etc line contains _alternatives_ twice. I'll rectify that in git master but I don't think this is related to your SSL issue.

> Could not create Vulkan instance

We have seen issues with noroot and Vulkan (e.g. #3012). Not sure why exactly, but you can try commenting that as well.

**Comment by GreatBigWhiteWorld** [comment]
Vulkan issue can be solved by commenting out "noroot".
But commenting out "private-etc..." line does not solve the connection problem, and the error 
`opensslconnection.cpp (1519) : Assertion Failed: unable to load trusted SSL root certificates`
still presents.

**Comment by glitsj16** [comment]
> Vulkan issue can be solved by commenting out "noroot".

Thanks for confirming that. We can add a note to the steam profile to inform users.

> ... commenting out "private-etc..." line does not solve the connection problem

A bit stumped on this one. Please inform us if it works when running `firejail --noprofile steam`. If that works there is something in our profile that needs fixing. If you get the same popup/error with that command the problem lies elsewhere. At the moment I can't think of anything besides `seccomp` that might be causing this, so it would be nice to know if commenting the seccomp line does anything to improve your steam connection troubles.

**Comment by GreatBigWhiteWorld** [comment]
commenting seccomp alone does not work.
--noprofile is the only way steam can launch without problem.

**Comment by rusty-snake** [comment]
I would tend to `include disable-*`. @GreatBigWhiteWorld is anything in the syslog? Can you start it with `--tracelog` and watch the syslog.

**Comment by GreatBigWhiteWorld** [comment]
Tried tracelog with or without --noprofile. I don't see any difference in the system log.
You mean add a line "include disable-*" in the steam.profile?

**Comment by rusty-snake** [comment]
> You mean add a line "include disable-*" in the steam.profile?

No, one (or more) of the disable-… includes disable something that is needed by steam. Try commenting all of them.

**Comment by GreatBigWhiteWorld** [comment]
Tried disabled them two by two, still no connection.

**Comment by rusty-snake** [comment]
No future idea what it could be. Looks like you need to comment option to find it.

**Comment by GreatBigWhiteWorld** [comment]
> No future idea what it could be. Looks like you need to comment option to find it.

Commenting on each line in the steam.profile to try?

**Comment by rusty-snake** [comment]
Yes, comment line for line and try after every comment to find the problematic line.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to reopen if you still have this issue.

**Comment by kevinlekiller** [comment]
OpenSuse Tumbleweed.

The issue is the files are not available under the `steam.profile`:

Without firejail:

    $ readlink -f /etc/ssl/certs
    /var/lib/ca-certificates/pem
    $ readlink -f /etc/ssl/ca-bundle.pem
    /var/lib/ca-certificates/ca-bundle.pem

With firejail, the links resolve to nothing ( overriding /usr/bin/steam with ~/.local/bin/steam that runs a terminal and running `firejail steam`):

    $ ls /var/lib/
    dbus

I haven't been able to figure out what in steam.profile prevents the files from showing up in /var/lib I'm guessing it's in one of the includes?

**Comment by rusty-snake** [comment]
> overriding /usr/bin/steam with ~/.local/bin/steam that runs a terminal and running firejail steam

simpler: `firejail --profile=steam bash`

> I haven't been able to figure out what in steam.profile prevents the files from showing up in /var/lib I'm guessing it's in one of the includes?

Hmm `private-etc` contains `ssl` and `include whitelist-var-common.inc` contains `whitelist /var/lib/ca-certificates`.

**Comment by kevinlekiller** [comment]
> Hmm private-etc contains ssl and include whitelist-var-common.inc contains whitelist /var/lib/ca-certificates. 

[That commit](https://github.com/netblue30/firejail/commit/90a4ca2b1c8785518b37062efa29270514a244fe) indeed fixes the issue, the package on OpenSuse is not using the latest version so doesn't include that fix yet, I've added it to steam.local for now.

Thanks.
