### ISSUE TITLE
qtox is missing from system tray

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#3392]
I'm not getting qtox in system tray.btw I'm using default firejail profile. 

Specs-
Os- Manjaro(KDE) Kernel-5.6.x Firejail-0.9.62 qtox-1.17.2

**Comment by glitsj16** [comment]
It might need D-Bus for the system-tray. You can check by either using `--ignore=nodbus` on the CLI or by adding `ignore nodbus` to ${HOME}/.config/firejail/qtox.profile. If the latter does not exist you'll need to create it.

**Comment by Neo00001** [comment]
> It might need D-Bus for the system-tray. You can check by either using `--ignore=nodbus` on the CLI or by adding `ignore nodbus` to ${HOME}/.config/firejail/qtox.profile. If the latter does not exist you'll need to create it.

yup. I have put ignore nodbus into qtox.local & it's working properly.Thanks

Can it be done by xdg portal? or D-bus is even needed to make call to xdg-portal

**Comment by glitsj16** [comment]
@Neo00001 I think I briefly saw a part of your reply via email that mentioned something about using XDG portal. There is important [work in progress](#3326) to offer more finegrained D-Bus control in firejail. But that's in testing, so you cannot use that with 0.9.62. Just some info I thought might be of interest, because the workaround here (ignoring nodbus) might stop working with a future Firejail release. With 0.9.62 the best you can do is what you already did.

**Comment by rusty-snake** [comment]
If you want to migrate automatic after the update of firejail, you can use this.
```bash
#!/bin/bash
sed -i -E \
    -e "/^nodbus$/c\\dbus-user none\ndbus-system none" \
    -e "/^ignore nodbus$/c\\ignore dbus-user filter\nignore dbus-system filter" \
    ~/.config/firejail/*

```
