### ISSUE TITLE
implement xdg-dbus-proxy --log / log denied D-Bus access tries

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3402]
Implement xdg-dbus-proxy --log to log blocked D-Bus calls. Without this it is difficult debug things like #3400 or #3399.

_Alternative we could log all calls for writing for writing profiles or simply forward the --log output (stdout of xdg-dbus-proxy) to a file (e.g. /tmp/pid_of_sandbox-dbus) and parse it with a python/bash/... program in contrib._

see also https://github.com/netblue30/firejail/pull/3265#issuecomment-609477194

cc @kris7t

**Comment by kris7t** [comment]
Sorry for not getting back to this earlier. I think capturing `xdg-dbus-proxy` output is the way forward, then post-processing it with a script (either to create a more human-readable log, or to generate profile line directly). The format of the logs looks way too annoying to process in a C program.

A complication is that `xdg-dbus-proxy` doesn't log separately for the session and system buses. Sometimes, interactive with the session and system buses is easily to filter out, but some names may be present on both buses. So to avoid confusion, I am now experimenting with single `--dbus-user.log` and `--dbus-session.log` options, as well as a `dbus-log=` option to direct output to a log file. A post-processing Python script may attempt to ingest a single log, connecting to the session and system buses to discern where each names belong (this can be somewhat of an approximation, if some names have disappeared since generating the log file), or take two logs (but then we have to run the application with logging two separate times).

In principle, we could even generate very fine-grained policies with `--call` and `--broadcast` filters that take bus name, interface member, object path triples. I added `--dbus-{user,system}.{call,broadcast}=` options to firejail to this end. However, these profiles can be unwieldy to write (hence the need for automatic generation from logs).

**Comment by rusty-snake** [comment]
Thanks for the explanations.

> I think capturing xdg-dbus-proxy output is the way forward, then post-processing it with a script (either to create a more human-readable log, or to generate profile line directly).

Going this way, would allow different scripts for different things (generate profile, warn on violation, ...)

> Another annoyance is that while filter rules are bound to well-known names, but communication on the bus might use unique names. See e.g.,

From that what I saw (with --log and `dbus-monitor`) the output still contains the addresses (at least one time).
