### ISSUE TITLE
seccomp.block-secondary

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#3417]
Are there any reasons why we don't use `seccomp.block-secondary`? It should work for almost all profiles (except wine and steam).

**Comment by glitsj16** [comment]
I have been running with `seccomp.block-secondary` in globals.local for as long as it exists without issues. But I don't use wine nor steam. The only other exception I encountered is when firejailing an **appimage** (which generally I try to avoid). We would need to determine how appimages react to the seccomp.block-secondary option, which I for one am not particularly looking forward to.

**Comment by rusty-snake** [comment]
> I have been running with seccomp.block-secondary in globals.local

I too

> The only other exception I encountered is when firejailing an appimage

Just this one? or also other appimages?

**Comment by glitsj16** [comment]
> Just this one? or also other appimages?

This is the only appimage I use because I couldn't create a reasonable profile for its non-appimage counterpart. It's not something I'm happy with, in general I avoid using snap/flatpak/appimage technology. So I cannot determine if it is something specific to this application or something in general with appimages. I'll try to test a few others, but to be conclusive we might ask @ [AppImageKit](https://github.com/AppImage/AppImageKit) I suppose.

**Comment by rusty-snake** [comment]
Tested KeePassXC and Cool-Retro-Term AI, both worked with sbs. We can go and add sbs to the most profiles.
