### ISSUE TITLE
Riot-desktop does not launch

### ISSUE THREAD

**Issue by blackpidgeon** [netblue30/firejail#3474]
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Riot/chrome-sandbox is owned by root and has mode 4755.

I have tried the tricks mentioned in #2946 with no success

**Comment by rusty-snake** [comment]
Is `force-nonewprivs yes` set in /etc/firejail/firejail.config?

What is your firejail version? distro?

**Comment by kortewegdevries** [comment]
Seems to be an issue regarding Electron and not Firejail perhaps, can you try checking the permissions of that file and setting it to root and/or the workaround(s) here https://github.com/vector-im/riot-web/issues/10509
For Xubuntu 20.04, things work fine with the default profiles and no extra config made.
`-rwsr-xr-x 1 root root 6259104 Jun 29 21:29 /opt/Riot/chrome-sandbox`
```
riot-web version: 1.6.7
olm version: 3.1.3
```

**Comment by rusty-snake** [comment]
@blackpidgeon Does it work with `--noprofile`?
BTW: It would be helpful if you put such error messages in quotes or code-blocks, since such error-messages have no "technical" things in it.

@kortewegdevries It's very likely that the file has the right permissions. (if it works without firejail we know it sure). Firejail features such as `nonewprivs` can "skip" the suid-bit.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
