### ISSUE TITLE
Firefox is already running, but is not responding.

### ISSUE THREAD

**Issue by michaepr** [netblue30/firejail#3626]
Hello,

I've recently done a full reinstall of my Arch Linux. I'm running Sway on Wayland (no XWayland) and I've installed firejail version 0.9.62.4. 

When I run firefox without firejail I can open two windows (belonging to the same instance) by just typing 'firefox' into two separate terminals. When I do the same with firejail, when opening the second window I get the error message: "Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile". That sounds to me like a new firefox instance is created even though I just want  to add a new window to the existing instance. Everything works fine if I create a firefox-common.local file with "ignore nodbus". 

I was wondering if this behaviour is expected and which potential security risks I have by enabling dbus connections. If it's not expected, do you know what could be causing it?

Thanks for your help!
Michael

**Comment by rusty-snake** [comment]
Duplicate of #3290 

Firefox uses D-Bus instead of IDK SystemV5-IPC? to talk to running instances if it runs as native Wayland client.

> I was wondering if this behaviour is expected

Knowed and fixed in the next release (in a few weeks)

> potential security risks I have by enabling dbus connections.

Full escape. Allowing full D-Bus access (not selective as possible with 0.9.64) allows to run any command outside of the sandbox. I suggest you to live with that restriction for now and wait for firejail 0.9.64. As an alternative you can install the firejail-git package from the AUR.
