### ISSUE TITLE
Lost email in claws-mail

### ISSUE THREAD

**Issue by a1346054** [netblue30/firejail#3743]
Updated firejail to 0.9.64-1~bpo10+1 from previous version, on debian stable using firejail from backports repository.

Ran `firecfg` to get new profiles.

Started claws-mail, saw completely empty inbox (all my emails were missing) and then new mail automatically downloaded. Using POP3 and delete on server when downloaded locally. Was worried that my mail was all gone, so I closed claws-mail, deleted `/usr/local/bin/claws-mail` that was generated by `firecfg`, started claws-mail, all my previous mail was there except the newly downloaded emails.

The newly downloaded emails are now permanently lost. Beware.

The location of my mailbox is `~/emails/claws/name-of-my-mailbox/`

**Comment by glitsj16** [comment]
> Started claws-mail, saw completely empty inbox (all my emails were missing) and then new mail automatically downloaded.

That is indeed expected behaviour when your mailbox diverges from the default ${HOME}/Mail, even when not sandboxing claws-mail. Our profile has a [note](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/email-common.profile#L12) stating as much...

> The location of my mailbox is ~/emails/claws/name-of-my-mailbox/

 You can follow the guidelines in the aforementioned note to support your custom mailbox location.

This is all very unfortunate, but besides taking out claws-mail in firecfg IMHO there's not much we can do to avoid this.

**Comment by rusty-snake** [comment]
I was already thinking of something like a MIGRATIONS.txt like

```
Important profile changes beteen 1.2.3 and 1.2.4
 - mua are now whitelisting profiles, if you store your mails in an own dir ...
 - enable chromium-hardened-common.inc if your kernel has unprivileged userns
 - …
```

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
