### ISSUE TITLE
Programs start without sandbox if /proc is mounted with hidepid

### ISSUE THREAD

**Issue by sjrabe** [netblue30/firejail#380]
If the `/proc` file system is mounted with `hidepid=1` or `hidepid=2`, firejail reports to have detected an existing sandbox (as it can't see the kernel processes), starting the program in a normal `/bin/sh` shell. While this can be avoided using `--force`, it looks like a security problem to me as the warning can't be seen unless firejail is started in a terminal, making it seem like the program is sandboxed when it really isn't.
1. Would it be possible to detect an existing sandbox without checking for kernel processes?
2. Instead of starting programs in an insecure `/bin/sh` shell, the default behavior in my opinion should be not to start the program unless a special command-line flag is used. Otherwise, people might restrict access to kernel processes, not realizing that their sandbox isn't being used anymore.

**Comment by jrabe** [comment]
Would you accept a pull request that changes the default behavior to require an `--allow-no-sandbox` option (or similar) for firejail to use an insecure `/bin/sh` shell, so that, when an existing sandbox is detected:
- **`--allow-no-sandbox`** uses a normal, insecure `/bin/sh` shell
- **`--force`** uses a sandbox (no change necessary)
- **Both options given**: use a sandbox (`--force` takes precedence)
- **None of the options given**: show an error message asking the user to specify one of the options; then exit

**Comment by netblue30** [comment]
I would leave it as is for now, probably there will be more changes in the future.

The question is this: you are in a sandbox, and you try to start another sandbox, what should happen? For Mozilla Thunderbird users this happens every time when they click a link in an email. So far the only idea I had was to start Firefox in the existing sandbox.

**Comment by jrabe** [comment]
You're right, I didn't think about that.
Do you have any idea how a sandbox could be detected other than by kernel processes? If not, let's close this issue?

**Comment by netblue30** [comment]
Probably there are other ways. The kernel gives out some inode numbers in /proc/self/ns, you can compare these numbers with a regular process and detect the namespaces.

**Comment by Sidnioulz** [comment]
@netblue30 not sure what exactly is the mechanics behind the Thunderbird situation, but on my fork I expect all my Xfce apps to use libxfce4ui's spawning function, and that function will detect if it is in a sandbox and then run "unsandboxed" (as in, not prepend firejail to the arguments being executed, resulting in the newly executed app being in the same container as its parent).

Assuming that you refer to Thunderbird running a .desktop file that does "firejail firefox", then the issue is that the .desktop file should embed that information another way (.desktop files have a special key in my fork indicating that Xfce should sandbox them) and the spawning utility used should be compatible (so that the initial run of the .desktop file in an unsandboxed environment properly runs it in a sandbox, and runs inside existing sandboxes put the new app inside that existing sandbox).

This is reliable and, as I see it, allows legitimate use of program helpers without raising security issues. But then again I have window decorations that clearly indicate the domain in which a windowed program is, you'd need that too to avoid user errors (using Thunderbird's firefox rather than another sandboxed firefox, when both are running).

**Comment by deathtrip** [comment]
I have /proc mounted with hidepid=2, and when i start a program from the terminal, everything seems ok.
No report of an existing sandbox.
However no sandbox can be seen by using "firemon --list" or by firetools.

**Comment by deathtrip** [comment]
here's the fstab entry:
proc						/proc		procfs		hidepid=2,gid=proc	0 0

**Comment by netblue30** [comment]
I'll give it a try, thanks.

**Comment by deathtrip** [comment]
any progress on this?

**Comment by netblue30** [comment]
> However no sandbox can be seen by using "firemon --list" or by firetools

Are you talking about this?

**Comment by deathtrip** [comment]
> Are you talking about this?
Yes.

**Comment by netblue30** [comment]
I'll try to bring in a fix.

**Comment by netblue30** [comment]
Fixed!
