### ISSUE TITLE
Cannot launch Teams on POP!_OS 20.10

### ISSUE THREAD

**Issue by etnx** [netblue30/firejail#3842]
Problem occurs in : Pop!_OS 20.10 (linux kernel is 5.8.0-7630-generic)
 
```
me@mypc:~$ firejail teams
Reading profile /etc/firejail/teams.profile
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Reading profile /etc/firejail/electron.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 10397, child pid 10398
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Blacklist violations are logged to syslog
Child process initialized in 74.58 ms
```

**No profile and disabling firejail**
- What changed calling `firejail --noprofile /path/to/program` in a terminal?
==> Everything OK

- What changed calling the program by path (check `which <program>` or `firejail --list` while the sandbox is running)?
Output : 
`12511:me::firejail --noprofile /usr/bin/teams `

**Environment**
```
etn@pc:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
```

Firejail version : 0.9.62.4

**Additional context**

Date :
The problem occured on november 18.
Before this date, I had no problem using teams with firejail.

In /var/log/syslog :
```
Dec 21 11:36:17 pc kernel: [ 3419.958239] audit: type=1400 audit(1608546977.495:30): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="firejail-default" pid=9704 comm="apparmor_parser"
Dec 21 11:36:25 pc kernel: [ 3427.762402] audit: type=1326 audit(1608546985.299:31): auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined pid=10413 comm="teams" exe="/usr/share/teams/teams" sig=31 arch=c000003e syscall=161 compat=0 ip=0x7f90087fa67d code=0x0
Dec 21 11:36:25 pc kernel: [ 3427.866610] traps: teams[10408] trap int3 ip:562e5eba27c5 sp:7ffd259bba60 error:0 in teams[562e5b890000+53c4000]
```

[debug.txt](https://github.com/netblue30/firejail/files/5723922/debug.txt)

**Comment by rusty-snake** [comment]
Very likely fixed on master by
- https://github.com/netblue30/firejail/commit/a37c7d4e7ee8a928744be509850c7b48ff31badc#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
- https://github.com/netblue30/firejail/commit/3e7c4830443b3c438df6968a050e813efbf28e0b#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
- https://github.com/netblue30/firejail/commit/f4f6767458208a127084e4c0103fab88761d9056#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7

Read #3795 for better understanding of these changes.

If POP!_OS has AppArmor, also https://github.com/netblue30/firejail/commit/9738b20511a08e1e2f8155a5bce585c52a0e45f6#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7.

**Comment by etnx** [comment]
I have updated (from Master branch) electron, firejail and firejail-for-linux profiles on my system (because of refactoring).
Now : `Warning: networking feature is disabled in Firejail configuration file`

[debug.txt](https://github.com/netblue30/firejail/files/5729652/debug.txt)

**Comment by rusty-snake** [comment]
> I have updated (from Master branch) electron, firejail and firejail-for-linux profiles on my system (because of refactoring).

You need to update firejail as well, if you copy the profiles from master.

**Comment by szemy** [comment]
I have a similar issue on Arch:
In firejail Log: [](https://pastebin.com/wKPHB7v6) dmesg: [](https://pastebin.com/p97DdYDD)
Version: 0.9.64
The teams.profile : [](https://pastebin.com/67xCJxqx)

**Comment by rusty-snake** [comment]
Fixed by:

 - https://github.com/netblue30/firejail/commit/a37c7d4e7ee8a928744be509850c7b48ff31badc#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
 - https://github.com/netblue30/firejail/commit/3e7c4830443b3c438df6968a050e813efbf28e0b#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
 - https://github.com/netblue30/firejail/commit/f4f6767458208a127084e4c0103fab88761d9056#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
 - https://github.com/netblue30/firejail/commit/f4f6767458208a127084e4c0103fab88761d9056#diff-046ffcfd2a399dd76a2a4d5220f83814a89dc2bd059b2e2c0fd089e1db06dec9

**Comment by rusty-snake** [comment]
Fixed by:

 - https://github.com/netblue30/firejail/commit/a37c7d4e7ee8a928744be509850c7b48ff31badc#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
 - https://github.com/netblue30/firejail/commit/3e7c4830443b3c438df6968a050e813efbf28e0b#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
 - https://github.com/netblue30/firejail/commit/f4f6767458208a127084e4c0103fab88761d9056#diff-535ce7031241d60504a4a23009358ed4ab07957e52cb45d9b8ac4bef9ff8c8b7
 - https://github.com/netblue30/firejail/commit/f4f6767458208a127084e4c0103fab88761d9056#diff-046ffcfd2a399dd76a2a4d5220f83814a89dc2bd059b2e2c0fd089e1db06dec9

**Comment by kris7t** [comment]
@rusty-snake Doesn't this defeat the point of using AppArmor along with Firejail? Instead of `ignore apparmor`, I think something like

```apparmor
/{,run/firejail/mnt/oroot/}usr/share/teams/** ix,
```

in an appropriate AppArmor profile would be more secure (although it does raise the question how to add and maintain such profile modifications, since it goes a bit against using a single AppArmor profile for all of firejail).

**Comment by glitsj16** [comment]
> [...] although it does raise the question how to add and maintain such profile modifications, since it goes a bit against using a single AppArmor profile for all of firejail

Perhaps we could add a note in teams.profile that AppArmor users better add your rule to their `/etc/apparmor.d/local/firejail-default,` which is the recommended AA override location.

**Comment by rusty-snake** [comment]
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.
