### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by SkewedZeppelin** [netblue30/firejail#3860]
Not a bug.

I wasn't happy with the existing videos about Firejail, so I made one. :rocket:
This is my 5th recording. It isn't perfect.
If you have any suggestions/corrections please tell me.
I'll record another take if need be.

https://divested.dev/index.php?page=videos#firejail-fedora33
http://adg2ps2d554gxiil7fv534liqppwd3wppobptur6klmhof3umxupryad.onion/index.php?page=videos#firejail-fedora33

:tada: Happy New Year! :tada:

**Comment by rusty-snake** [comment]
>  If you have any suggestions/corrections please tell me.

The profile.template has some extra notes like how to find out which files need to be whitelisted/noblacklisted compared to default.profile.

**Comment by reinerh** [comment]
That's really cool! Thanks for recording it!

**Comment by netblue30** [comment]
Thanks @SkewedZeppelin - best video I've seen in ages! I'll make it "official". So I'll cut it down to 720p for youtube, credits on the video such as:

* video and presentation @SkewedZeppelin 
* Divested Computing Group © 2014-2021
* https://divested.dev - CC BY-SA 4.0

Any problems, let me know.

**Comment by kmk3** [comment]
Nice; I usually use the whitelisting effect on Firefox as an example as well
when talking about firejail.

Suggestion: Put the video on PeerTube (e.g.: on
<https://peertube.linuxrocks.online/>).

This would allow people to find it more easily and also to comment on it
without having a BigCorp account.  For me, completing a captcha was required in
order to view the video, which I assume is due to hosting costs, which is
another thing that PeerTube can help with.  Especially with the content being
CC-BY-SA, which increases the chances of other instances/people seeding it
(e.g.: there are instances that only allow content that is under a Creative
Commons license).

**Comment by netblue30** [comment]
The videos are here:

youtube: https://www.youtube.com/watch?v=N-Mso2bSr3o  (720p)
bitchute backup: https://www.bitchute.com/video/A9DFO6oovYIw/  (480p)

Thanks @kmk3, I'll look into peertube, at least for backup. Currently our backup is on bitchute, but bitchute is under attack from various actors, we'll see how long the whole site stays up.

**Comment by reinerh** [comment]
Debian also hosts a PeerTube instance: https://peertube.debian.social/

**Comment by kmk3** [comment]
@netblue30 commented yesterday:

> The videos are here:
> 
> youtube: https://www.youtube.com/watch?v=N-Mso2bSr3o (720p)
> bitchute backup: https://www.bitchute.com/video/A9DFO6oovYIw/ (480p)

Interesting; what do you think about adding the channel links to README.md?
There already are thumbnails that link to videos, but I think that direct links
would make the official channels more discoverable/prominent.

> Thanks @kmk3, I'll look into peertube, at least for backup.

Nice, the more mirrors the merrier.  I think all you need for auto-syncing is
to give it a YouTube channel URL.

> Currently our backup is on bitchute, but bitchute is under attack from
> various actors, we'll see how long the whole site stays up.

That's unfortunate; is there anywhere I can read up on that?  Since video
hosting seems to be a problem these days, there's also <https://lbry.tv>, which
works similarly to BitChute (AFAICT) and can also auto-sync from YouTube.

@reinerh commented yesterday:

> Debian also hosts a PeerTube instance: https://peertube.debian.social/

User registration appears to be disabled though:

* https://peertube.debian.social/about/instance

I'm not sure if it means that no one should create new accounts or if they want
people to create Salsa accounts instead.  Also from the above:

> Why we created this instance
> 
> This instance is for users and developers of Debian to share videos that they
> create. The main topics are Debian and free software, although it's not
> limited to that.
> 
> This instance also hosts the DebConf video archives.

They do say it isn't limited to Debian stuff, but all of the local accounts
that I found are either from the Debian Project or by Debian developers.  To me
it looks to be more of an institutional instance, like
<https://video.blender.org/>, rather than being about technology/Free Software
in general.  This is just my first impression though, they might just allow it
anyway.

* https://peertube.linuxrocks.online/about/instance

By the way, I just noticed that the above also appears to support live
streaming, which I find nice to have.  In any case, you can create accounts on
many different instances.  The content posted on an account on a given instance
P should also appear on every instance that follows P:

* https://peertube.linuxrocks.online/about/follows
* https://peertube.debian.social/about/follows

**Comment by reinerh** [comment]
> User registration appears to be disabled though:
> 
>     * https://peertube.debian.social/about/instance
> 
> I'm not sure if it means that no one should create new accounts or if they want
> people to create Salsa accounts instead. Also from the above:

Yes, a Salsa account is needed, though anyone can register one. Salsa is used because only one account (SSO, single sign-on) is then needed for many other services (they also host e.g. a Matrix instance).

> > Why we created this instance
> > This instance is for users and developers of Debian to share videos that they
> > create. The main topics are Debian and free software, although it's not
> > limited to that.
> > This instance also hosts the DebConf video archives.
> 
> They do say it isn't limited to Debian stuff, but all of the local accounts
> that I found are either from the Debian Project or by Debian developers. To me
> it looks to be more of an institutional instance, like
> https://video.blender.org/, rather than being about technology/Free Software
> in general. This is just my first impression though, they might just allow it
> anyway.

The instance is still quite new and not so well-known, so it doesn't have much users.
But as the text mentions, anything free software related (not even really limited to that) is fine there (by anyone, not only Debian Developers).

But it was just a suggestion, as I don't know linuxrocks.online.

**Comment by kmk3** [comment]
> > User registration appears to be disabled though:
> > ```
> > * https://peertube.debian.social/about/instance
> > ```
> > 
> > 
> > I'm not sure if it means that no one should create new accounts or if they
> > want people to create Salsa accounts instead. Also from the above:
> 
> Yes, a Salsa account is needed, though anyone can register one. Salsa is used
> because only one account (SSO, single sign-on) is then needed for many other
> services (they also host e.g. a Matrix instance).
> 
> > > Why we created this instance
> > > This instance is for users and developers of Debian to share videos that they
> > > create. The main topics are Debian and free software, although it's not
> > > limited to that.
> > > This instance also hosts the DebConf video archives.
> > 
> > 
> > They do say it isn't limited to Debian stuff, but all of the local accounts
> > that I found are either from the Debian Project or by Debian developers. To me
> > it looks to be more of an institutional instance, like
> > https://video.blender.org/, rather than being about technology/Free Software
> > in general. This is just my first impression though, they might just allow it
> > anyway.
> 
> The instance is still quite new and not so well-known, so it doesn't have
> much users.  But as the text mentions, anything free software related (not
> even really limited to that) is fine there (by anyone, not only Debian
> Developers).

I see; thanks for the explanation.

> But it was just a suggestion, as I don't know linuxrocks.online.

Sure, no worries.  I mentioned that one because I've come across it a few
times, it's SFW and tech/linux-focused, with seemingly hands-off moderation and
I found nothing on it that I'd complain about.  But content still seems to be
rather spread out between the many networks of instances; there's hardly any
that I'd call a "go-to" instance.

---

By the way, did you add that code fence on the beginning or was it GitHub?  The
"Quote reply" feature usually adds non-existing spaces and blank lines for me,
but that one would be new.

**Comment by reinerh** [comment]
> By the way, did you add that code fence on the beginning or was it GitHub? The
> "Quote reply" feature usually adds non-existing spaces and blank lines for me,
> but that one would be new.

It was automatically added by Github.

**Comment by rusty-snake** [comment]
Can we close?

**Comment by reinerh** [comment]
Yes. :-)
