### ISSUE TITLE
Adding sara LSM library to Firejail Sandbox for w^x protection

### ISSUE THREAD

**Issue by osevan** [netblue30/firejail#3972]
https://sara.smeso.it/en/latest/

Sara library exists too

https://github.com/smeso/libsara

Maybe useful for firejail sandbox

Thanks and

Best regards

**Comment by topimiettinen** [comment]
Sara (or something like it) would be nice, though kernel support is not merged yet. Currently Firejail has a poor man's version of it with `memory-deny-write-execute` (mdwx). This is implemented with seccomp, so it's only capable of blocking `mprotect()` and `mmap()` system calls with `PROT_EXEC|PROT_WRITE` flag combination as well as `memfd()` system call. Because Sara would be part of the kernel, it can do further checks including the history of the pages. Firejail profiles can also complement Sara (and mdwx) with `noexec` and `read-only` options, by making sure that also file systems are mounted with W^X logic: no file system is executable which is also writable. Sara also tries to be compatible with trampolines without giving up entire protection: with seccomp it's not possible to identify the use case. Some class of programs won't be able to use Sara or mdwx, for example Java and probably they are the same programs which can't use `memory-deny-write-execute`.

When/if Sara gets merged, Firejail could simply enable it with `memory-deny-write-execute` automatically or with a new option(s) if finer control is needed.

**Comment by osevan** [comment]
Sara is already used by many guys...


We need a solutions easy one at compile time.--with-sara option and in profiles for specific apps .

Thanks and
Best regards

**Comment by Vincent43** [comment]
> Sara is already used by many guys...Sara is already used by many guys...

Does sara patches even compile against latest kernels? I didn't saw updated version for many months.

**Comment by osevan** [comment]
Author need update patch.

:-(

**Comment by rusty-snake** [comment]
S.A.R.A. had no releases/development activity for around 5 years. Closing for now.
