### ISSUE TITLE
Is this a bug or intended or a bug ??

### ISSUE THREAD

**Issue by Nokia808** [netblue30/firejail#3973]
Hi. 

Really I couldn't type a suitable title for this !

Dear developer, I noticed the following:

1) on my system I'm already set my Firefox to be run within firejail by editing icon launcher file of my Firefox to use the command "firejail firefox %u". I performed this by my application menu editor.
2) I'm already changed the default "security & privacy" setting of my Firefox. I'm already using a custom security & privacy setting, for ex: I set it to NOT accept any 3rd party cookies NOR to store any password so that it DOES NOT asking me to save any password because already I set it NOT to set any password.
3) when I run my Firefox from any where INCLUDING NON-FIREJAILED THUNDERBIRD (like by clicking a link within a message), the Firefox will opened & respecting my custom setting ....... This is very okay & no problem.
4) the problem started since I started to use Thunderbird with firejail. I edited it's icon launcher file in same way that I did for Firefox, so that it is currently using "firejail thunderbird %u". I noticed that when I click on a link within received email while I'm already running Thunderbird within Firejail, then my Firefox will open on that link BUT NOT RESPECTING MY CUSTOM SETTING !! Even sidebar that I'm already leaving it activated I will see it hidden & need to reactivate it ! If page is a login page, then Firefox will ask me if I like to save password or not ! So, I click "Preferences" of Firefox I shocked when I saw that it using the default setting !!!!

Kindly, to review this behavior to see if this is a bug or not !

Best.

**Comment by rusty-snake** [comment]
That's because firefox is then started inside the thunderbird sandbox and can not read it's profile, therefore it create a new one. This new one misses your custom settings, bookmarks, history (if not disable), ... . So it's expected.

Good to know:
- Firefox can not access it's profile because there is no `whitelist` for it (and thunderbird is a whitelisting profile), therefore all the things which get stored in this new profile will going to be destroyed when you close firefox and thunderbird.
- If you try this to reproduce with a blacklisting profile, firefox will abort with an error, because it can not access it's profile becuase it is `blacklist`ed and therefore it can not create a new one (which would be permanent).
- The thunderbird profile for firejail 0.9.64 allow to open links in a already running firefox:
https://github.com/netblue30/firejail/blob/3710a6874220699b41f7d9413520e6c73500d782/etc/profile-m-z/thunderbird.profile#L24-L27

**Comment by Nokia808** [comment]
@rusty-snake 
Thank you very much for your response & for your great program & all your hard efforts to evolute it !

Issue resolved !
