### ISSUE TITLE
Yarn profile causing error

### ISSUE THREAD

**Issue by skrat** [netblue30/firejail#4321]
version 0.9.64.4

running yarn with the bundled profile results in:

```
Error getpwuid: main.c:236 init_cfg: Success
```

That led me to issues #2547 and the workaround mentioned there, ie.

```
firejail --ignore=private-bin --private-etc=group,passwd
```

works for me, although I don't understand the security implication of those args.

**Comment by rusty-snake** [comment]
> --ignore=private-bin

yarn.profile does not have `private-bin` => `ignore`ing it is a no-op => no security implication

> --private-etc=group,passwd

yarn.profile has both => no security implication

(since 699a803f174662a8ec62442438bb0807e41d3971)

> running yarn with the bundled profile

FTR: yarn.profile is designed to be the base for user adaptation since you never know which package/project/workflow requires which permissions. Therefore is is not in firecfg.config

>  Error getpwuid: main.c:236 init_cfg: Success

How do you run it? Did you created symlinks for it?

**Comment by skrat** [comment]
@rusty-snake no in this case I have `yarn.local` in `~/.config/firejail` (with added whitelist) and I'm running it with `firejail yarn dev`

**Comment by skrat** [comment]
I see that `nodejs-common` has `passwd` in `private-etc`, mine doesn't (arch linux, latest package version) so that's the problem I assume. Build date of that package is Wed Feb 10, `passwd` was added on May 8th.
