### ISSUE TITLE
List of deprecated profiles

### ISSUE THREAD

**Issue by pirate486743186** [netblue30/firejail#4539]
I'm creating this issue, to keep track of the profiles that would need deleting in the future. I remind you, they are 1000+ profiles and we need to note down what is on it's way out. Propose suspect profiles.

- newsbeuter abandoned and superseded by newsboat, it will bit rot, in ubuntu 18.04
- straw-viewer/gtk-straw-viewer Abandoned and superseded by pipe-viewer, it will be useless when the invidious API changes.
- gtk2-youtube-viewer gtk2, probably depends on obsolete youtube API
- rtv abandoned, useless when reddit API changes

profiles with support for old versions

- mcomix  has support for the gtk2/python2 version, installable in ubuntu 18.04

**Comment by kmk3** [comment]
@pirate486743186 commented [on Sep 13](https://github.com/netblue30/firejail/issues/4539#issue-995005883):

> I'm creating this issue, to keep track of the profiles that would need
> deleting in the future. I remind you, they are 1000+ profiles. Propose
> suspect profiles.

What would be the "need" to delete profiles?

If the idea is about avoiding having >1000 files per directory (because of
GitHub file listing), how about moving certain profiles to an archive directory
instead (e.g.: "etc-archive")?

> * youtube-dl (probably abandoned)

Why do you consider that to be the case?  The latest commit is from July and it
still works.

> * newsbeuter (abandoned and superseded by newsboat)
> * rtv (abandoned)

These still exist in the AUR at least:

* newsbeuter: <https://aur.archlinux.org/packages/newsbeuter-git>
* rtv: <https://aur.archlinux.org/packages/rtv>

While rtv is likely to break (as suggested by the main author on
<https://github.com/michael-lazar/rtv/issues/696>) or to already be broken,
it's not like RSS is a moving target, so newsbeuter will probably keep working.

**Comment by pirate486743186** [comment]
you'll leave in profiles that are useless? You need to remove the dead stuff. I'm a bit surprised by the casual attitude regarding the profiles

These are not to be deleted immediately. Maybe i should detail the reasons in the list...

youtube-dl has many red flags. Yes exactly, last commit was 1 of July, but this is a fast moving project, that's incredibly long. A partial workaround was found for age restricted videos in youtube, that's still not implemented.  Also, youtube-dl is not just about youtube, it has downloaders for many other sites, you can't just see how it performs with youtube. If you are interested, yt-dlp seams to be the new youtube-dl. It's 90% certain at this point that youtube-dl is dead.

newsbeuter is not "really" abandoned, it just changed name. No one "maintains" it, because they maintain newsboat. newsbeuter will just accumulate bitrot until it can't compile. Arch is all bleeding edge, can you still  install newsbeuter? It was removed from debian. The only users must be from old versions of distributions that are still maintained.

rtv still works, until reddit changes their API or is left behind by python. Presumably a fork will succeed by then and we'll recycle the profile.

**Comment by crocket** [comment]
youtube-dl.profile doesn't need to be deleted so quickly.

**Comment by pirate486743186** [comment]
i'm not saying immediately. It will become almost useless very fast though.
you want to use yt-dlp.

**Comment by kmk3** [comment]
@pirate486743186 commented [on Sep 14](https://github.com/netblue30/firejail/issues/4539#issuecomment-919245374):

> you'll leave in profiles that are useless?

Useless to whom?  If a program still works and still has users, it by
definition has a use, and so does its profile.

> You need to remove the dead stuff.

Again, what would be the "need" to remove anything?

I see that you added redirects on some of the mentioned profiles, such as:

* yt-dlp -> youtube-dl
* newsbeuter -> newsboat

If you're worried about maintenance, we can just undo the redirects so that the
original programs don't affect and don't get affected by their forks.  This
would also make it easier to update fork profiles if they require
major/frequent changes.  And so the original profiles would mostly only get
updated by mass search/replace commits, which maintenance-burden-wise is not
too different from them being deleted.

Note: If a profile redirect starts being a nuisance, doing the above would
likely be helpful regardless of a project's maintenance status.

> I'm a bit surprised by the casual attitude regarding the profiles

I could say the same.  It takes effort to write a profile, especially one that
is a good combination of secure, usable and generic and it's hard to tell how
many users any given profile might have.

> These are not to be deleted immediately. Maybe i should detail the reasons in
> the list...

A timeframe would help clarify things.  It's not clear if the suggestion is to
remove a profile a day or years after you consider a program to be "dead".

> youtube-dl has many red flags. Yes exactly, last commit was 1 of July, but
> this is a fast moving project, that's incredibly long. A partial workaround
> was found for age restricted videos in youtube, that's still not implemented.

I agree that due to it depending on ever-changing web-based APIs, it requires
more constant care than not.  Though I can't remember the last time that it
failed on me due to YouTube API changes (other than for the age-restricted
videos).  IME it has been more solid in that regard than other YouTube
frontends at least.

> Also, youtube-dl is not just about youtube, it has downloaders for many other
> sites, you can't just see how it performs with youtube.

How come?  If we're still talking about "useless" programs: In a given program,
if half of its functionality stops working and you don't notice it (because you
never used such functionality), does the program stop being useful?

> If you are interested, yt-dlp seams to be the new youtube-dl.

I have planned on trying yt-dlp, though I'm not sure if I'll bother while
youtube-dl still works.  youtube-dl is integrated with other software (like
mpv), so I'd have to change config files and scripts and retest, which I have
no interest in doing at the moment.  Note also that options were removed and
that many defaults have changed (all of which may have to be evaluated), so it
is not a 100% drop-in replacement.

See also the following comment on a related issue:

---

@dirkf commented [on Sep 14](https://github.com/ytdl-org/youtube-dl/issues/29965#issuecomment-919346687):

> Supposing the current project owner and maintainers are not just on a summer
> break, or a death march project, it would have to be decided whether the
> project can attract enough support to continue with the same aims, either
> as-is, or in a fork, with new maintainers.
> 
> The yt-dlp project seems to be attracting most interest nowadays, but does
> not support Python 2, nor even Python < 3.6, which would seem to be the
> distinguishing feature between the two projects (there are quite few UI and
> other enhancements as well). Leading Linux distros that are still in extended
> support came with Python 2 and 3.5 as an option.
> 
> I would like to support a Python 2 platform (where the host is a set-top box
> for which Python 3.6+ may never be built), but it might be possible to do so
> by cherry-picking and adapting yt-dlp changes.

---

> It's 90% certain at this point that youtube-dl is dead.

I'd wager that most users will only notice that anything changed (or didn't
change fast enough) in youtube-dl if/when it actually stops working for
YouTube.  Other than that, I'd expect at least one of the following to happen
before making such a claim:

* It stops being packaged by distros
* Third-party software start using a fork instead

> newsbeuter is not "really" abandoned, it just changed name. No one
> "maintains" it, because they maintain newsboat.

While the UI is similar, newsboat has a massive additional dependency
(rust/cargo), so it's hardly the same project packaging-wise.  To me it might
as well have been a complete rewrite considering that.  Also, the maintainer of
newsboat considers it to be a fork.

> newsbeuter will just accumulate bitrot until it can't compile. Arch is all
> bleeding edge, can you still install newsbeuter?

I tested newsbeuter-git and all it takes is adding `-DTRUE=1 -DFALSE=0` to
CFLAGS, as json-c for some reason had macros for true and false.  It also works
fine.  Note that the latest commit is from 2017-09-20, so it still works after
being unchanged for almost 4 years.  I guess the dependencies were nicely
chosen.  Anyway, that was an interesting exercise; I'll send a patch to the AUR
maintainer later.

> It was removed from debian.  The only users must be from old versions of
> distributions that are still maintained.

Which by definition would mean that the profile is still useful.  Also, why
would the age of a distribution matter profile-wise if it's still maintained
and if firejail still works on it?  Right on the README.md firejail has
instructions for Ubuntu 18.04, for example.

**Comment by dirkf** [comment]
> Which by definition would mean that the profile is still useful. Also, why
> would the age of a distribution matter profile-wise if it's still maintained
> and if firejail still works on it? Right on the README.md firejail has
> instructions for Ubuntu 18.04, for example

Indeed.

Ubuntu 16.04 is in [ESM support until 2024](https://ubuntu.com/security/esm). 18.04 (ESM to 2028) is some bleeding edge OS in comparison.

**Comment by crocket** [comment]
I can't relate to ubuntu's bleding edge. I use gentoo linux. I also used to use artix linux which is a derivative of arch linux.

Arch linux is the bleeding edge. Gentoo linux is a little behind because of stabilization process.

**Comment by pirate486743186** [comment]
install yt-dlp, then make a symbolic link to it named youtube-dl in your path. A few things changed, for example the download filename format ("--compat-options filename" will give you the old one). So test things a bit, then take your time to change the configurations.

They are 1000+ profiles, you need to note down somewhere what is on it's way out. Stop freaking out.

**Comment by rusty-snake** [comment]
I don't think we need to track this in an issue.
