### ISSUE TITLE
Firefox 94 Has Broken the Ability to Open New Tabs via Firejail Command

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#4670]
Firejail version: 0.9.62

Kubuntu 20.04 recently auto-updated to Firefox 94. Ever since, I can no longer launch URLs via the command line like this:
`firejail firefox https://github.com &`

I posted this issue over at AskUbuntu :
https://askubuntu.com/questions/1373963/

Actually, it will launch fine if Firefox is completely closed, but none of my hot keys that launch additional pages work anymore.

This may not be a firejail bug, but I was hoping that posting here might lead to me finding a good work around. Please check out the link above. I appreciate it!

**Comment by kmk3** [comment]
@Lonniebiz commented [on Nov 6](https://github.com/netblue30/firejail/issues/4670#issue-1046586022):

> Kubuntu 20.04 recently auto-updated to Firefox 94. Ever since, I can no
> longer launch URLs via the command line like this: `firejail firefox
> https://github.com &`
> 
> I posted this issue over at AskUbuntu :
> https://askubuntu.com/questions/1373963/
> 
> Actually, it will launch fine if Firefox is completely closed, but none of my
> hot keys that launch additional pages work anymore.
> 
> This may not be a firejail bug, but I was hoping that posting here might lead
> to me finding a good work around. Please check out the link above. I
> appreciate it!

Please follow the bug template:

* <https://github.com/netblue30/firejail/issues/new?assignees=&labels=&template=bug_report.md&title=>

Does it help if both invocations use the same sandbox?  Example:

```sh
firejail --name=firefox1 firefox
firejail --join=firefox1 firefox https://github.com &
```

**Comment by Lonniebiz** [comment]
@kmk3 First of all, I really appreciate your attention to the matter. This issue (no matter what is causing it) is pretty important to my workflow. You see, I'm accustom to launching websites I frequent with hotkeys facilitated by [autokey](https://en.wikipedia.org/wiki/AutoKey).

So, I'm not typing these commands in directly, it is a python script within autokey that is sending the commands to the terminal. That script is only two lines:
```
import os
os.system("firejail firefox https://github.com/ &")
```
However, for the test you've requested, I'm going to copy and pasted those lines (one at a time) directly into the terminal:
```
firejail --name=firefox1 firefox
firejail --join=firefox1 firefox https://github.com &
```
**Result:** The first line launched the browser like normal. However, when I entered the second command, I got this error:
![errorFirefox](https://user-images.githubusercontent.com/151919/140660304-4127905f-bbad-48cf-8e33-6882ce8e5c04.png)

That was a good thing to try. You'd think that since the same sandbox was specified in both commands, that firejail is indeed sending the 2nd command exactly where it is supposed to go.

I don't think this is a firejail bug, because Firejail is not what changed; like I mentioned, this issue only began to happen after my system auto-upgraded my Firefox from version 93 to 94. Something changed in Firefox 94, where it no longer cooperates with firejail like it did before.

Given this fact, that's why I'm so grateful that you were willing to offer some advise on this matter.

Regarding the bug template you've provided, I'm struggling with this part of it:
```
user@pc1:~$ LC_ALL=C firejail PROGRAM` (`LC_ALL=C
bash: command substitution: line 2: syntax error: unexpected end of file
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file

** Note: you can use --noprofile to disable default.profile **

Parent pid 6889, child pid 6890
Warning: cleaning all supplementary groups
Child process initialized in 106.14 ms
/bin/bash: PROGRAMLC_ALL=C: command not found

Parent is shutting down, bye...
user@pc1:~$ `LC_ALL=C firejail PROGRAM` (`LC_ALL=C`
bash: syntax error near unexpected token ``LC_ALL=C`'
```

**Comment by Lonniebiz** [comment]
Submitted to Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1739919

**Comment by kmk3** [comment]
@Lonniebiz commented [on Nov 7](https://github.com/netblue30/firejail/issues/4670#issuecomment-962675191):

> firejail version 0.9.62

That version is old and potentially vulnerable to 3 CVEs; see:

* <https://github.com/netblue30/firejail/discussions/4663#discussioncomment-1592273>
* #4666

> Kubuntu 20.04
> 
> Firefox 94.0

There is more to the template than the environment section and I don't feel
like copy pasting parts of it here.

The generic advice would be to try commenting parts of the relevant profiles to
narrow down the issue.

Other than that, there are a few similar-looking issues that may be of help:

* #3471
* #3881
* #3919

**Comment by rusty-snake** [comment]
> firejail version 0.9.62

Does firefox 64 use the (native) Wayland backend?

**Comment by RolKau** [comment]
I had this exact problem using Firefox 94 under Ubuntu Focal 20.04. Firejail 0.9.62 is the version in the Ubuntu repository. Upgrading to Firejail 0.9.66 (through using the 'deki' PPA) seems to have fixed it.

**Comment by ibhagwan** [comment]
I'm having a similar issue, Firefox 94.0 and firejail 0.9.66:
```sh
~ ❯ firejail --version
firejail version 0.9.66

Compile time support:
        - always force nonewprivs support is disabled
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - firetunnel support is enabled
        - networking support is enabled
        - output logging is enabled
        - overlayfs support is disabled
        - private-home support is enabled
        - private-cache and tmpfs as user enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

~ ❯ firejail --join=firefox firefox --new-tab https://hover.com
Switching to pid 1511, the first child process inside the sandbox
Child process initialized in 6.71 ms
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

^C
```

Resulting in the below popup inside firefox:
![screenshot-1637106556](https://user-images.githubusercontent.com/59988195/142084414-13081117-819c-49ab-a5cc-fb1cc56cad20.png)

**Comment by RolKau** [comment]
@ibhagwan
Where do your Firejail profiles come from? For me, they are in a companion package named `firejail-profiles` that I also had to upgrade (if you are on a Debian-derivative system you can for instance see which version you have with a command like `apt-cache policy $(dpkg -S /etc/firejail/firefox.profile | cut -d: -f1)`)

**Comment by ibhagwan** [comment]
> @ibhagwan Where do your Firejail profiles come from? For me, they are in a companion package named `firejail-profiles` that I also had to upgrade (if you are on a Debian-derivative system you can for instance see which version you have with a command like `apt-cache policy $(dpkg -S /etc/firejail/firefox.profile | cut -d: -f1)`)

@RolKau, my profiles came with the default `firejail` package on void linux:
```sh
~ ❯ xbps-query -l | grep firejail
ii firejail-0.9.66_1                       SUID security sandbox program
~ ❯ xbps-query -f firejail  | grep firefox
/etc/firejail/firefox-beta.profile
/etc/firejail/firefox-common-addons.profile
/etc/firejail/firefox-common.profile
/etc/firejail/firefox-developer-edition.profile
/etc/firejail/firefox-esr.profile
/etc/firejail/firefox-nightly.profile
/etc/firejail/firefox-wayland.profile
/etc/firejail/firefox-x11.profile
/etc/firejail/firefox.profile
```

**Comment by RolKau** [comment]
The profiles that are in the Void Linux repository are from this repository, and they match the ones that I have on my installation (from the 'deki' PPA) exactly, so that rules them out as the culprit.

**Comment by RolKau** [comment]
The options and version from `firejail --version` are the same, *except* that my version has the option "SELinux support is enabled" whereas yours (@ibhagwan, that is) has "SELinux support is disabled". I am not qualified to say if that is relevant.

**Comment by Lonniebiz** [comment]
firejail version 0.9.64.4

@RolKau I'm having the exact same problem again, now with [LibreWolf](https://gitlab.com/librewolf-community/browser/appimage/-/releases).

**Comment by oo-san** [comment]
You must be using an old firefox profile. I encountered the same erorr, but it works when using the firefox profile bundled with the latest release of firejail (0.9.66).

Adding `ignore dbus-user none` to an older profile also fixed this problem for me.

**Comment by ibhagwan** [comment]
> You must be using an old firefox profile. I encountered the same erorr, but it works when using the firefox profile bundled with the latest release of firejail (0.9.66).
> 
> Adding `ignore dbus-user none` to an older profile also fixed this problem for me.

Unfortuntely that's not the case, I have firejail 0.9.66 and my firefox commands includes `--dbus-user=none`:
```sh
#!/bin/sh
GDK_DPI_SCALE=0.70 firejail --name=firefox --dbus-user=none --keep-config-pulse firefox
```

**Comment by glitsj16** [comment]
> Unfortuntely that's not the case, I have firejail 0.9.66 and my firefox commands includes --dbus-user=none:
GDK_DPI_SCALE=0.70 firejail --name=firefox --dbus-user=none --keep-config-pulse firefox

@ibhagwan By using `--dbus-user=none` in a shell script or on the command line you are breaking the `logic` of our firefox profiles (aka @oo-san is correct). Let me explain. Firefox uses D-Bus to open URLs in a running instance (instead of starting a second one). Firejail takes this into account in two steps. To tighten the sandbox we first disallow access to both user and system bus by having `dbus-user none` and `dbus-system none` in firefox-common.profile. To keep things like URL processing working in a reasonable way we grant access only to a very limited and specific subset of options. Have a look inside your firefox.profile. Near the bottom you'll see:

```
[...]
dbus-user filter
dbus-user.own org.mozilla.Firefox.*
dbus-user.own org.mozilla.firefox.*
dbus-user.own org.mpris.MediaPlayer2.firefox.*
[...]
ignore dbus-user none

# Redirect
include firefox-common.profile
```

The first four lines define that we want to grant access to these specific adressess on the user bus only). The `ignore dbus-user none` just before the redirect is needed to compensate fully disabling all D-Bus access from inside the sandbox. I hope this clears things up a bit. What happens when you use the below in your shell script?
```
GDK_DPI_SCALE=0.70 firejail --name=firefox --keep-config-pulse firefox
```

**Comment by ibhagwan** [comment]
@glitsj16 tysm for the explnation, it does help clear things up a bit.

I just tried running without the `--dbus-user=none` and then ran the following command:
```console
~ ❯ firejail --join=firefox firefox --new-tab https://hover.com
Switching to pid 1980, the first child process inside the sandbox
Child process initialized in 7.21 ms
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
^C
```

And this is what I get inside firefox (basically same result):
![screenshot-1639727921](https://user-images.githubusercontent.com/59988195/146510266-208b866b-2864-4c7f-8422-f82c666d7188.png)

**Comment by glitsj16** [comment]
@ibhagwan I don't have a straightforward do-this-and-it-will-work answer to your issue at the moment. IMO your firejail profiles are fine and you should keep avoiding --dbus-user=none as explained above. Two remarks for further consideration.
- The consecutive `Error: Can't find profile directory` messages are a bit unusual (at least to me). I assume your Firefox profile(s) setup is something you've already checked, but to rule this out you could do a quick test with a clean FF copy.
- Something we haven't touched upon is your desktop environment. I'm specifically interested to know if you happen to use a mixed X11/Wayland setup. If so, you can try adding `MOZ_DBUS_REMOTE=1` to the mix. See [this](https://mastransky.wordpress.com/2020/03/16/wayland-x11-how-to-run-firefox-in-mixed-environment/) short but very informative page from Firefox Guru Martin Stransky's blog. Either add `--env=MOZ_DBUS_REMOTE=1` on the command line/in your shell script or set `env MOZ_DBUS_REMOTE=1` in a firefox.local override file. Shouldn't take long to see if that does anything positive.

**Comment by ibhagwan** [comment]
>The consecutive Error: Can't find profile directory messages are a bit unusual (at least to me). I assume your Firefox profile(s) setup is something you've already checked, but to rule this out you could do a quick test with a clean FF copy.

I will try that.

>Something we haven't touched upon is your desktop environment. I'm specifically interested to know if you happen to use a mixed X11/Wayland setup. If so, you can try adding MOZ_DBUS_REMOTE=1 to the mix. See this short but very informative page from Firefox Guru Martin Stransky's blog. Either add --env=MOZ_DBUS_REMOTE=1 on the command line/in your shell script or set env MOZ_DBUS_REMOTE=1 in a firefox.local override file. Shouldn't take long to see if that does anything positive.

Not using wayland, X11/AwesomeWM straight forward setup.

It's worth noting the same setup worked for a long time and then one day stopped working, I can't pinpoint whether it was a firefox update or firejail update that caused this, since then I switched my `xdg-open` config to open in ungoogled-chromium instead which is also firejailed and works fine.

**Comment by glitsj16** [comment]
@ibhagwan Thanks for informing us on your specific setup. I do recognize what you describe. The feeling of noticing something broke and not being able to pinpoint stuff. Been there many times, and it keeps happening, no matter how many things one keeps logs of :-). If no one tunes in here with the 'magic bullet' fix and you'd like to return to Firefox in your xdg-open, you could check if [firejail-handler-http](https://github.com/glitsj16/firejail-handler-http) suits your needs. I wrote these shell scripts specifically to run Firefox in a firejail sandbox with `full blocking of D-Bus` before we integrated xdg-dbus-proxy into Firejail. They still work okay, if one can live with the usability/workflow impact...

**Comment by Lonniebiz** [comment]
Firejail, please fix this same issue as it is found in [LibreWolf version 95 AppImage](https://gitlab.com/librewolf-community/browser/appimage/-/releases) also.

**Comment by cockytrumpet** [comment]
> So, I'm not typing these commands in directly, it is a python script within autokey that is sending the commands to the terminal. That script is only two lines:
> 
> ```
> import os
> os.system("firejail firefox https://github.com/ &")
> ```
> 
> However, for the test you've requested, I'm going to copy and pasted those lines (one at a time) directly into the terminal:
> 
> ```
> firejail --name=firefox1 firefox
> firejail --join=firefox1 firefox https://github.com &
> ```
> 
> **Result:** The first line launched the browser like normal. However, when I entered the second command, I got this error:
> 
> > Firefox is already running, but is not responding. To use Firefox, you must first close the

does it work if you change your script to
```
firejail --join=firefox1 firefox --new-tab some-web-site &
```

I think I'm getting the behavior you are looking for. I don't know how to set this up in KDE, but maybe you can translate my gnome setup to your use.

### ~/.local/share/applications/Firejail-Firefox.desktop
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Icon=/home/username/Pictures/firejailed_firefox128.png
Exec=/home/username/bin/firefox.sh %u
Name=X11-Firejailed Firefox
Comment=X11-Firejailed Firefox
StartupWMClass=Xephyr
Terminal=false
MimeType=application/pdf;application/vnd.mozilla.xul+xml;application/xhtml+xml;text/html;text/mml;text/xml;x-scheme-handler/ftp;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Categories=Network;WebBrowser;
Keywords=web;browser;internet;
```
### ~/bin/firefox.sh
```
#!/bin/sh

no_jail=$(firejail --list | grep "name=firefox")

if $no_jail; then
	/usr/bin/firejail --x11=xephyr --name=firefox --net=br10 --profile=/etc/firejail/firefox.profile openbox --startup "/usr/lib64/firefox/firefox $1"&
	sleep 5
	firejail --join=firefox xmodmap -e 'keycode 64 = VoidSymbol VoidSymbol'
else
	/usr/bin/firejail --join=firefox /usr/lib64/firefox/firefox --new-tab $1
fi
```

Set Firejail-Firefox as the default application. xdg-open and right clicking a link in the terminal both work.

**Comment by Druco** [comment]
I am adding this here rather than opening a new bug report because I think it is pretty clearly the same problem.

### Description
Attempting to open a URL in Firefox 95 from a link in an email message in Thunderbird causes the same error message as described above (Firefox is already running, but is not responding...) when Firefox and Thunderbird are in sand boxes. Running the identical setup with Firefox 93 works properly so something has changed between FF93 and FF95.

### Steps to reproduce
1) firejail firefox
2) firejail thunderbird
3) In a message in thunderbird, click on a URL to open

### Expected behavior
The link opens in the existing firefox instance

### Actual behavior
Error message stating "Firefox is already running, but is not responding..."

### Environment
OpenSuse Tumbleweed 20220109
Firejail 0.9.66
Firefox 95.02
Thunderbird 91.4.1

### Behavior without a profile
Starting Firefox without a profile does not fix the problem, however starting Thunderbird without a profile does. As noted above however, if using Firefox 93 rather than Firefox 95 and the same Thunderbird, both with the same firejail profiles, everything works properly.

### Checklist
- [x] The issue is caused by firejail (sort of, in that FF93 works but FF95 does not, but it definitely works without firejail)
- [x] I can reproduce this without custom modifications
- [x] Both Firefox and Thunderbird have profiles
- [x] I (obviously) performed a short search to see if there are similar issues

### Notes
- I updated directly from Firefox 93 to 95 so I never tested FF 94.
- Almost certainly this is caused by the same issue as the original bug but it seems to me that it is a more common use case and may start affecting more people as they update to the newer Firefox.
- Attached are dbus-monitor files for a case with FF93 and FF95 if that helps.

[sendToFirefox95FromFirejail.txt](https://github.com/netblue30/firejail/files/7860489/sendToFirefox95FromFirejail.txt)
[sendToFirefox93FromFirejail.txt](https://github.com/netblue30/firejail/files/7860491/sendToFirefox93FromFirejail.txt)

**Comment by Druco** [comment]
As a followup to my above comment, I have found a "fix"/kludge that works at least for now in my setup. Using wireshark to monitor the dbus when firefox and thunderbird were started both with and without firejail, I discovered that when a link was being opened from thunderbird it makes an OpenURL() call with a destination of "org.mozilla.firefox.ZGVmYXVsdA__" so I tried putting:
`dbus-user.talk org.mozilla.firefox.ZGVmYXVsdA__`
in my local firejail/thunderbird.profile and it worked with firejail.

Now I have no idea where the "ZGVmYXVsdA__" comes from, if it will remain constant across upgrades, or would be different for another user/machine, but for now it works.

I also did a wireshark monitor when using FF 93 (which works without the kludge) and I didn't find this call being made. In fact, I have no idea how FF 93 even got the URL it opened because I couldn't find it in any of the dbus messages in that case. So there was definitely a change between FF 93 and FF 95.

Hopefully this might give a hint to anyone who has a similar problem and more knowledge of dbus messaging than I do.

**Comment by glitsj16** [comment]
> dbus-user.talk org.mozilla.firefox.ZGVmYXVsdA__
Now I have no idea where the "ZGVmYXVsdA__" comes from, if it will remain constant across upgrades, or would be different for another user/machine, but for now it works.

You can use globbing to make things persistent:
` dbus-user.talk org.mozilla.firefox.*`

**Comment by rusty-snake** [comment]
> dbus-user.talk org.mozilla.firefox.ZGVmYXVsdA__
in my local firejail/thunderbird.profile and it worked with firejail.

Did you set `dbus-user filter`? Or where does it come from? 

> > - [x] I can reproduce this without custom modifications

> Now I have no idea where the "ZGVmYXVsdA__" comes from, if it will remain constant across upgrades, or would be different for another user/machine, but for now it works.

It's the hash of your profile (and possible firefox installation).

> In fact, I have no idea how FF 93 even got the URL it opened because I couldn't find it in any of the dbus messages in that case.

System-V-IPC / X11-Magic

**Comment by Lonniebiz** [comment]
@RolKau If you have time, please take a look at this [related issue](https://github.com/netblue30/firejail/issues/4891).

**Comment by ibhagwan** [comment]
Not really sure why the old versions of firefox were able to open links properly even with `--dbus-user=none` but after the explantion from @glitsj16  I started exploring the dbus angle and after reading #3769 I was able to solve this by removing `--dbus-user=none` and making sure that I have `$DBUS_SESSION_BUS_ADDRESS` properly set.

My dbus socket was located in `~/.dbus/session-bus/LONG-ID` but I had two files there named `<ID>-0` and `<ID>-1` (`0` being the correct session file) so I added the below to my firefox firejail starting script and now I can open links again in FF:
```sh
#!/bin/sh
. `ls ~/.dbus/session-bus/*-0`
export DBUS_SESSION_BUS_ADDRESS
GDK_DPI_SCALE=0.70 firejail --name=firefox --keep-config-pulse firefox
```
