### ISSUE TITLE
LibreWolf can't detect my Timezone

### ISSUE THREAD

**Issue by Lonniebiz** [netblue30/firejail#4696]
firejail version 0.9.64.4

**Librewolf 94.0-1 AppImage:**
[https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/94.0-1/LibreWolf.x86_64.AppImage](https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/94.0-1/LibreWolf.x86_64.AppImage)

**Librewolf profile**
[https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/librewolf.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/librewolf.profile)

**Command:**
`firejail --appimage --profile=/home/user/.config/firejail/librewolf.profile /path/to/AppImages/LibreWolf.x86_64.AppImage`

My issue is that Librewolf doesn't know my local timezone. I verified that by going [here](http://browserspy.dk/date.php) with LibreWolf.
This causes web-email-clients to report the wrong time for when messages were sent and received.

I probably just need to edit the profile to allow the browser to see my timezone, but I'm not sure how to do that.

**Comment by SkewedZeppelin** [comment]
I'm pretty sure that is because Librewolf enables privacy.resistFingerprinting
not because of firejail.

**Comment by rusty-snake** [comment]
WFM

```console
$ date +%Z
CET
$ firejail --quiet --profile=librewolf date +%Z
CET
$ firejail --quiet --profile=librewolf --blacklist=/etc/localtime date +%Z
UTC
```

You can try to `env TZ=CST6CDT` but RFP will just override it.

**Comment by simon-ging** [comment]
One way to fix the timezone in Librewolf is to disable resistFingerprinting, instead enable fingerprintingProtection, and override the settings there. Librewolf does not recommend this since it goes against the entire point of RFP as they explain [here](https://librewolf.net/docs/faq/#what-are-the-most-common-downsides-of-rfp-resist-fingerprinting). However if you absolutely want to change it, you can do it like this in about:config

```
privacy.resistFingerprinting = false
privacy.fingerprintingProtection = true
privacy.fingerprintingProtection.overrides = +AllTargets,-JSDateTimeUTC
```

**Comment by pjotrek-b** [comment]
I'm happy to have found this thread!

I understand why one wants RFP - but in this very short time I've switched to LibreWolf's I've spent already several hours - today **again** - debugging "weird issues" just to find out, again it's - because of the browser claiming **a plain-wrong timezone**.

(@simon-ging: Thanks for the options to take timezone-spoofing out of fingerprintingProtection, btw.)

I've found some threads mentioning "privacy.resistFingerprinting.exemptedDomains", which led me to this:
[Apply fine-grained control of the RFP Timezone Spoofing](https://bugzilla.mozilla.org/show_bug.cgi?id=1709867#c21), which mentions this (marked as `RESOLVED -> fixed`):

> We're introducing a new pref: privacy.resistFingerprinting.testing.setTZtoUTC. When this pref is false (as it is on Nightly) we will no longer set the TZ enviroment variable, which is how we previously made the browser spoof timezones. 

Haven't tried it yet.
