### ISSUE TITLE
No internet access with  etc/firejail/whitelist-run-common.inc enabled running openSUSE Leap 15.3 and Firejail version 0.9.68

### ISSUE THREAD

**Issue by Kebron718** [netblue30/firejail#4954]
firejail version: 0.9.68 (installed from official repos)  
problem did not exist in earlier versions
Linux distro: openSUSE Leap 15.3

I updated from version 0.9.66 yesterday and lost internet access with e.g. Chromium, Firefox and Thunderbird. The programs seemed to load correctly but there was no network access whatsoever. 

Switched between 0.9.68 and 0.9.64 (0.9.66 was not available any more in the openSUSE repos) and discovered that I had to uncomment every entry in 

**etc/firejail/whitelist-run-common.inc**

in order to get internet access back. 

I noticed that there is no such file in 0.9.64.

I don’t know whether this problem is limited to openSUSE.

**Comment by reinerh** [comment]
> I guess that could easily be fixed in the SUSE repos ...

That can also be fixed in firejail upstream. :-)
There are probably other distributions using netconfig.
Do you want to open a Pull Request that adds the whitelist?

**Comment by powerjungle** [comment]
Same issue is in OpenSUSE Tumbleweed and this fixes it, thanks!

**Comment by sebix** [comment]
Hi,

firejail-package-maintainer in openSUSE here.

Thanks for reporting, debugging and fixing the issue!

> Same issue is in OpenSUSE Tumbleweed and this fixes it, thanks!

See status update in https://bugzilla.opensuse.org/show_bug.cgi?id=1196542
I added the patch to the experimental repo, if this problem is fixed for the affected users, I will submit it to Tumbleweed official packages.

btw: firejail 0.9.68 is not part of Leap 15.3 official packages, only as experimental package, same source as for tumbleweed.

**Comment by kmk3** [comment]
Closing this as it seems to have been fixed by commit bb334a8fd ("openSUSE
Leap - whitelist-run-common.inc (#4954)", 2022-02-22).
