### ISSUE TITLE
Update seccomp groups

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/firejail#5188]
Related: #3106

Since your last seccomp groups update Linux got new syscalls like `clone3` (`@process`), `close_range` (`@basic-io`) or `move_mount`,`open_tree`,`fsconfig`,`fsmount`,`fsopen`,`fspick` (`@mount`). We should update the group definitions to include newly added syscalls.

**Comment by rusty-snake** [comment]
@smitsohu can we close?

**Comment by smitsohu** [comment]
Closing!

**Comment by kmk3** [comment]
Misc: These commits seem to be related:

* fbceab90a ("refresh and sort syscall tables", 2022-07-15)
* f4f44a5f9 ("refresh syscall groups (#5188)", 2022-07-17)

And I made a few WIP commits related to the first one.

Since this issue appears to be the most relevant one to that commit, I renamed
this issue to be about the syscalls too.

**Comment by kmk3** [comment]
(Late review)

@smitsohu

* fbceab90a ("refresh and sort syscall tables", 2022-07-15)

Please try to avoid doing both sorting and logical changes on the same commit,
as that can make it really hard to see what was changed (and I was interested
to see what syscalls were added/removed in this case).

Considering that the tables weren't fully sorted (by syscall name), the diffs
would have been clearer by splitting the changes like this:

1. sort syscall tables (by name)
2. refresh syscall tables
3. sort syscall tables (by number)

Or like this:

1. sort syscall tables (by number)
2. refresh syscall tables
