### ISSUE TITLE
Skype cannot save credentials

### ISSUE THREAD

**Issue by ibahnasy** [netblue30/firejail#5226]
Every time I start Skype it asks for credentials, however I whitelisted it's config dir:
`firejail --nodbus --whitelist=~/.config/skypeforlinux/ /usr/bin/skypeforlinux %U`

firejail version 0.9.66

**Comment by glitsj16** [comment]
> firejail version 0.9.66

Try `upgrading` your firejail installation ASAP. There have been important changes since version 0.9.66 (CVE vulnerability, --nodbus deprecated, etcetera). Current [skypeforlinux.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/skypeforlinux.profile) has everything you tried on the CLI.

If your issue still exists after upgrading, please show us a more informative output of commands you run. Without that we're just blind readers who cannot actually offer much help.

**Comment by rusty-snake** [comment]
1. Follow the issue template (or I ignore your issue as a waste of time).
2. You very likely shoot yourself in the foot with `--nodbus`.
