### ISSUE TITLE
polly - not running under firejail control ?

### ISSUE THREAD

**Issue by frank-github** [netblue30/firejail#531]
try to run polly under firejail control
application run and works, but seems not to be controlled by firejail, isn't ?

```
ubuntu:~/.config/firejail$ firejail --private=/media/daten/frank/Firejail/Polly polly
Reading profile /media/daten/frank/.config/firejail/polly.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Parent pid 15068, child pid 15069

Warning: --protocol not supported on this platform
Child process initialized

parent is shutting down, bye...
ubuntu:~/.config/firejail$ firejail --list
ubuntu:~/.config/firejail$ 
```

**Comment by netblue30** [comment]
Probably Polly is a single-instance program. When you start it, it checks if another instance is already running. If one is found, it sends a message and it shuts down. The existing instance will then open the application windows.

Lots of programs do this, among them Firefox. Make sure the first instance of polly is started under firejail.

**Comment by frank-github** [comment]
hupps, I never noticed polly didn't quit, if I close it by X button
thanks, if polly not running, everything works fine  :-)

**Comment by frank-github** [comment]
need another polly related tip  
application uses old original homepath, but firejail was run with --private=/newdir
maybe read user home directory from /etc/passwd ??

`ubuntu:$ firejail --private=/media/daten/user/Firejail/Polly polly`

cache path: /media/daten/**user**/.cache/polly
config path: /media/daten/**user**/.config/polly
data home: /media/daten/**user**/.local/share/polly
/usr/bin/polly:332: GtkWarning: Attempting to store changes into `/media/daten/user/.local/share/recently-used.xbel', but failed: Datei »/media/daten/user/.local/share/recently-used.xbel.GARBIY« konnte nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
  Gtk.main()
/usr/bin/polly:332: GtkWarning: Attempting to set the permissions of `/media/daten/user/.local/share/recently-used.xbel', but failed: Datei oder Verzeichnis nicht gefunden
  Gtk.main()

any hint or tip is welcome

**Comment by netblue30** [comment]
You need to create the directories in the new home:
`````
$ mkdir /media/daten/user/Firejail/Polly/.cache
$ mkdir /media/daten/user/Firejail/Polly/.config
$ mkdir -p /media/daten/user/Firejail/Polly/.local/share
`````
It is strange, most programs do this by default. If they don't find a ~/.config directory they just create it.

**Comment by frank-github** [comment]
I did create this folders in "new firejail" home, but polly still try to access old locations :-1:

**Comment by netblue30** [comment]
It means polly is already running in the background somewhere.

**Comment by frank-github** [comment]
for sure, no polly instance running on this maschine, if I start it with firejail and got this output !

**Comment by netblue30** [comment]
I'll give it a try.

**Comment by netblue30** [comment]
Polly runs as a daemon. You start it for the first time and shut it down, and polly goes in the background instead of shutting down. You will no see anything on your screen, but polly is there waiting for commands.

When you start it the second time, the new polly instance sends a message to the one in the background, and the background instance opens the application window. Then, the second instance  shuts down.

The fix is to make sure the first instance is started in firejail. I would add a symbolic link in /usr/local/bin:
`````
$ sudo ln -s /usr/bin/firejail /usr/local/bin/polly
`````
This way, polly is always sandboxed, including the first instance. You will need to reboot the computer after you add the link. After the computer starts up, use Dash (the top icon in the Launcher to find polly, and click on the polly icon - it should start polly in firejail. You can use "firejail --list" in a terminal to see if polly is sandboxed.
