### ISSUE TITLE
PulseAudio/Sound is broken when running Chromium

### ISSUE THREAD

**Issue by SShrike** [netblue30/firejail#548]
On Arch Linux using PulseAudio 8.0, Chromium 51 (also happened on 50) and Firejail 0.9.40, the PulseAudio server is broken once Chromium is launched. Sounds still works through Chromium, but any other applications trying to output sound either stop working or are stuck going through the wrong output (I have two outputs). I've confirmed it's an issue with Firejail, as when I'm not using it everything works fine.

Sorry the vague bug report, I'm not that familiar with Linux's sound architecture and I only use Firejail casually with my browsers.

**Comment by Impyy** [comment]
Did you try https://firejail.wordpress.com/support/known-problems/#pulseaudio?

**Comment by netblue30** [comment]
The workaround on that page should solve the problem, thanks @Impyy

**Comment by maces** [comment]
for me the workaround worked (also pulseaudio 8 on archlinux) but I had to enable it in the global config file "/etc/pulse/client.conf" (other option could be to adjust the common profile).
Otherwise when starting firefox jailed and qmms non jailed and then opening pavucontrol the later would hang, not beeing able to open /dev/shm.
