### ISSUE TITLE
Firecfg does not work for programmes in /usr/local/bin

### ISSUE THREAD

**Issue by Fred-Barclay** [netblue30/firejail#667]
This isn't exactly firecfg's fault, but whenever a programme is already installed to /usr/loca/bin, then firecfg fails to create a link/launcher for it. 
For example, the debian package for gitter installs to /usr/local/bin/gitter by default. Even though gitter is listed in src/firecfg/firecfg.config, firecfg does not (re)create /usr/local/bin/gitter.

I don't know what to suggest about this but just wanted to point it out. :smile: 
Cheers!

**Comment by reinerh** [comment]
That is also a bug in the package. They are not supposed to place files in /usr/local.

**Comment by netblue30** [comment]
Bug!

**Comment by chiraag-nataraj** [comment]
I ran into this issue recently as well, since I have both a distro-installed version of a program as well as a self-compiled (updated) version from Github (incidentally enough, it was because I patched the program to honor `$TMPDIR` so that I could use it with firejail!). I don't see how we can solve it though, at least not nicely. We could move the offending binary to `/usr/bin`, but that has issues in e.g. my case (where I have the same binary in two different places and _want_ both versions). Or, we could emit a warning and skip it. How about we emit a warning and proceed without doing anything?
