### ISSUE TITLE
HOME environment variable not adjusted when using --user

### ISSUE THREAD

**Issue by lheckemann** [netblue30/firejail#720]
```
$ sudo firejail --user=$USER sh
$ echo $HOME
/root
```

**Comment by Fred-Barclay** [comment]
I believe this from the README.md might help:
"--user option was deprecated, please use "sudo -u username firejail application" instead."
:smile_cat:

**Comment by lheckemann** [comment]
Oops. But I guess there's no way to give an unprivileged jail capabilities then?

**Comment by Fred-Barclay** [comment]
I don't know about that; maybe @netblue30 or someone else with more experience could answer that better than I could. It will probably also depend on *which* capabilities you want to give the jail. :wink: 
But my guess would be `sudo -u root firejail <application>`.

**Comment by lheckemann** [comment]
But I don't want to run it as root, I want to run it as an unprivileged user gaining just certain capabilities like `net_bind_service`.

**Comment by netblue30** [comment]
I had to remove --user because it was equivalent with "sudo -u username firejail application". 

If you need a program to keep certain capabilities, the standard way is to use "setcap" command.  Here is an example of how they do it for ping: https://linux-audit.com/linux-capabilities-hardening-linux-binaries-by-removing-setuid/

**Comment by lheckemann** [comment]
Ah right, thanks!
