### ISSUE TITLE
Firejail.service

### ISSUE THREAD

**Issue by amarildojr** [netblue30/firejail#754]
Hello Netblue,

With intentions of making Linux more secure for everyone, I'd like to know if it's possible to create a firejail service that automatically firejails every executable opened, since your profiles have been proven to work very well for everyone, and because new users don't find it attractive to edit launchers. This way, distros could enable such service and make it automatic start/enable upon firejail installation.

Cheers,
Amarildo

**Comment by Fred-Barclay** [comment]
Would `firecfg` be what you're looking for?
It "allows the user to sandbox applications automatically, just by clicking on a regular desktop menus and icons." 

See `man firecfg` for details on how to use it.

**Comment by amarildojr** [comment]
Thanks, but this suggestion is not for _my_ use :) Most newcomers don't even want a Terminal to work on, much less understand how to work with Firejail or Firecfg. That's why I think that a trully automated "firejail.service" (similar in operation to firecfg) would be a good idea. This service wouldn't require any user intervention.

**Comment by xahare** [comment]
This wouldnt be a service, just some symlinks. you could make something for a settings panel like "auto firejail: on off" that runs the same command.

this is a bad idea, unless the user is aware that firejail is running. for example, if you save an image from the browser to your home folder, it will only exist in the context of the firejail. the browser will not tell the user otherwise. the profiles would need to change to explicit about what browsers can and can't do, but those changes could break cases where the browser should think it can write somewhere. 

you could borrow from qubes-os and bring the window manager into the picture, making different borders. for example, a fire themed window decorations, maybe of different colors if your separating contexts.

**Comment by Fred-Barclay** [comment]
@amarildojr I see. Well, since firejail *is* a terminal program :wink: anyone who uses it is probably at least somewhat comfortable with the terminal. 
I wonder if `firecfg` could be integrated with [firetools](https://github.com/netblue30/firetools) so that you could have a graphical interface to initially launch firecfg? Of course, after the initial `firecfg` (or whatever the graphical equivalent would be when launched from firetools) the user will never have to do any intervention--all programs with a firejail profile will start automatically in firejail under most circumstances.

**Comment by netblue30** [comment]
The closest you can get to this, would be an x11 Xephyr setting, where you start in firejail a light window manager like openbox - https://firejail.wordpress.com/documentation-2/x11-guide/#configurexephyr

Then, all the applications started by Xephyr would be automatically sandboxed.

**Comment by amarildojr** [comment]
@netblue30 So distros could already implement this if they wanted?

**Comment by xahare** [comment]
one distro, subgraphos https://subgraph.com/sgos/ already does this. they use their own sandbox, which is similar to firejail.

**Comment by netblue30** [comment]
> So distros could already implement this if they wanted?

Yes.

**Comment by amarildojr** [comment]
Thanks. I'm closing this issue then.
