### ISSUE TITLE
[enhancement] Document abstract sockets and what to do about them

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#801]
I wonder if it would be a good idea to start documenting all the different abstract sockets and how to disable them. Notably, it might be a good idea because not everyone can create a new network namespace. I'll start the thread off with two major ones:
1. X11 - as discussed in [this](https://github.com/netblue30/firejail/issues/770) thread, you can disable X11 abstract sockets by appending `-nolisten local` to the relevant config file (some examples are given at http://tstarling.com/blog/2016/06/x11-security-isolation/ as well as in the thread).
2. DBus - as discussed in [this](https://github.com/netblue30/firejail/issues/796) thread, you can disable DBus abstract sockets by editing DBus config files. The key is to look for lines like `<listen>unix:tmpdir=/tmp</listen>` and change it to something like `<listen>unix:path=/tmp/blah</listen>` (obviously replacing "blah" with a more descriptive name). As noted in that same thread, there may be multiple DBus configuration files lying around, since some programs like to control exactly what the configuration is. In order to eliminate these kinds of sockets, you will have to find and edit **all** of the DBus configuration files.

Also note that you can check if you have abstract sockets set up by looking at the output of `sudo netstat -xap | grep '@'`.

**Comment by lheckemann** [comment]
I don't think documenting specific cases of abstract sockets is really sufficient for secure isolation. Instead, it would make more sense to block DBus completely (by default? Not sure about that) and document very clearly that permitting it will often allow jail escapes.

**Comment by lheckemann** [comment]
"the session bus assumes that all connecting processes have the same privileges" so applications simply should not have access to the session bus. See comment on #796 for details

**Comment by chiraag-nataraj** [comment]
Sure. The problem is that it's super hard to restrict access when DBus is listening over an abstract socket. Forcing DBus to use regular sockets makes it far easier to restrict access.

**Comment by lheckemann** [comment]
It's not super hard, you just need to create a new network namespace. Not creating a new network namespace leaves the possibility that other programs that listen on abstract sockets allow a vulnerability, and requires non-standard config for D-Bus. Do we really want to default to an insecure config, rather than documenting that not isolating the network is usually insecure and the issues that isolating the network can cause?

**Comment by chiraag-nataraj** [comment]
Again, there are many scenarios (in my own case, at least), where it is not possible for me to create a new network namespace. I spend a lot of time at school, and hence use wifi (a new network namespace only works with an ethernet connection). Even at home I usually use wifi, and hence have the same problem. If the program doesn't require the internet, that's great, but I have several (e.g. Firefox), which *need* access.

> Not creating a new network namespace leaves the possibility that other programs that listen on abstract sockets allow a vulnerability, and requires non-standard config for D-Bus.

That's precisely the point. In the cases when creating a new network namespace is not possible or practical, what am I supposed to do? Just give up? Why not document how to change the configurations for whichever programs (X11, DBus, etc.)? Yes, it's non-standard, but that's much more a reflection of insecure defaults and idiocy than anything else.

**Comment by lheckemann** [comment]
Is there a good reason to bridge interfaces rather than setting the host machine up as a router which will then forward traffic as appropriate, regardless of it being through wifi or ethernet? That also makes it stable over changes in the network configuration, e.g. switching between wifi and ethernet, or multiple interfaces.

**Comment by netblue30** [comment]
You can definitely set up a bridge, enable ip forwarding, configure NAT in iptables and push all your sandboxes on the bridge.

**Comment by lheckemann** [comment]
Would this perhaps be a sensible default?

**Comment by netblue30** [comment]
No, because this would require to mess up with the main netfilter configuration the user has running on the system.

**Comment by lheckemann** [comment]
I can't help but feel that the firewall mechanism isn't very well suited for any sort of application that needs to NAT stuff... That was always an issue with Docker too.

**Comment by netblue30** [comment]
Yes, Docker does it by default. Also LXC installs a bridge device in the system. Somehow it is a mater of packaging, since the bridge is created when docker and lxc are installed. I don't know how they deal with NAT or port forwarding for running servers.

**Comment by testbird** [comment]
Router and nat setup may not have to be a mess.
1) Document how to set up a named bridge that firejail assumes to be active (for package maintainers can automate this at install time). Let's say configuring firejail-br0 and 127.0.0.4x.
2) Ship simple firewall and routing rules with as few host rules as possible, so that the host firewall may be managed however desired. However, depending on firehol, the basic firejail filter and router configuration could look simply similar to this:

```
# rules for the sandbox
interface firewall-br0 hostonly-net
    source firewall-rules.local
    client all accept dst not 127.0.0.40
```

```
# routing rules for the bridge on the host
router firejail2internet inface firejail-br0 outface $gatewaydev
    masquerade
    route all accept
```
https://firehol.org

**Comment by chiraag-nataraj** [comment]
Moot for dbus (at least on systemd systems) because they moved to socket activation and regular (file-based) unix sockets.
