### ISSUE TITLE
{,/usr}/sbin warnings are shown with --quiet

### ISSUE THREAD

**Issue by clawoflight** [netblue30/firejail#889]
Reading #708 , I thought this may need to be reported:

The warnings

    Warning: /sbin directory link was not blacklisted
    Warning: /usr/sbin directory link was not blacklisted

are shown even with `--quiet`.

**Comment by netblue30** [comment]
Fixed, thank you for the report.

**Comment by clawoflight** [comment]
I am still having this issue with `0.9.44.8`...
What commit was this fixed in?

**Comment by netblue30** [comment]
I think the problem was fixed after 0.9.44.8. It was fixed on mainline branch - kind of difficult to find the commit.

I keep an updated bugfix branch for 0.9.44 here: https://github.com/netblue30/firejail/tree/0.9.44-bugfixes

The commit on this branch is https://github.com/netblue30/firejail/commit/f90ae0aab518fe5c102ffcd25f7d646151f5f7f4

I tested it on Arch Linux.
